[Polygon Edge]Add extra env parameters to Blockscout
maticnetwork/matic-docs pull request #1013
Opened 2022-07-26 08:57 UTC by laviniat1996

2022-07-26 18:59 UTC, DannyS03 commented
@laviniat1996 feel free to use the Edge label for PRs regarding Edge content

2022-07-27 16:43 UTC, zivkovicmilos commented on docs/edge/additional-features/blockscout.md
> +INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
@laviniat1996 @ZeljkoBenovic 

We should probably note that some of these are changeable, while others are not

2022-07-27 16:43 UTC, zivkovicmilos requested changes
Looks okay, left a minor suggestion

2022-07-27 18:54 UTC, laviniat1996 commented
> @laviniat1996 feel free to use the Edge label for PRs regarding Edge content

@DannyS03  Thank you for the tip 👍

2022-07-27 19:05 UTC, cerberushades approved these changes

2022-07-27 19:05 UTC, cerberushades commented on docs/edge/additional-features/blockscout.md
> +INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
ok guys, should we merge it @laviniat1996 @zivkovicmilos

2022-07-27 20:26 UTC, zivkovicmilos commented
Hey @cerberushades,

I believe you gave us contributor access to the repo, meaning we can squash and merge PRs.

We usually have thorough internal discussions on open documentation PRs, and don't merge anything until everything is resolved and everyone is satisfied 🙂

You can leave the squash and merge of Edge PRs to the Edge team, we won't leave them hanging as they're accounted for in our internal task tracking system 🍻 

I wouldn't want for these PRs to get merged by someone from outside of the Edge team.

2022-08-02 10:29 UTC, ZeljkoBenovic commented on docs/edge/additional-features/blockscout.md
> +INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
@laviniat1996 Maybe just add a comment above these three env vars like:
`# these environment variables disable debug tracing as it is not currently supported in Polygon Edge`

2022-08-02 10:29 UTC, ZeljkoBenovic approved these changes

2022-08-02 11:16 UTC, laviniat1996 commented on docs/edge/additional-features/blockscout.md
> +INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
@ZeljkoBenovic Done 24bb49b18da67709d975b5cb5bc4dd00dddb84ad

2022-08-02 11:17 UTC, zivkovicmilos approved these changes
Looks good now, thank you for clarifying the env file 🙏

2022-08-02 11:27 UTC, merged