[Polygon Edge] Add FAQ
maticnetwork/matic-docs pull request #1017
Opened 2022-07-27 13:39 UTC by laviniat1996

This PR creates an FAQ section for Polygon Edge.

2022-07-27 14:41 UTC, zivkovicmilos commented on docs/edge/faq/Contracts.md
> +description: "FAQ for Polygon Edge smart contracts"
I would capitalize this to `Smart Contracts`

2022-07-27 14:41 UTC, zivkovicmilos commented on docs/edge/faq/Contracts.md
> +description: "FAQ for Polygon Edge smart contracts"
Not just here, but everywhere in the doc

2022-07-27 14:43 UTC, zivkovicmilos commented on docs/edge/faq/Contracts.md
> +Yes. You can deploy a smart contract in the same manner as Ethereum.
Why not specifically state that we support ERC20, ERC721...?

2022-07-27 14:44 UTC, zivkovicmilos commented on docs/edge/faq/Contracts.md
> +Yes. You can deploy a smart contract in the same manner as Ethereum.
I would also rephrase this to be:

`Yes. Polygon Edge networks are Ethereum compatible blockchains, so Smart Contracts that are deployable on Ethereum, are also deployable on Polygon Edge chains. `

2022-07-27 14:46 UTC, zivkovicmilos commented on docs/edge/faq/Gas.md
> +This sets a premined balance of 1000eth to 0x3956E90e632AEbBF34DEB49b71c28A83Bc029862 (the amount from the argument is in gwei).
The amount is **not** in gwei, it's actually in wei.

Please correct this 🙏

2022-07-27 14:47 UTC, zivkovicmilos commented on docs/edge/faq/Validators.md
> +Polygon Edge has PoA and PoS as consensus mechanisms. PoA is the default one. For a new cluster, to switch to PoS, you will need to add the `--pos` flag when generating the genesis file. If you have
How does this answer the question `How do I add a validator`?

2022-07-27 14:48 UTC, zivkovicmilos commented on docs/edge/faq/Validators.md
> +Adding/removing validators is done by voting. You can find [here](/docs/edge/consensus/poa) a full guide about this.
Typo, should be `You can find a full guide about this here.`

2022-07-27 14:48 UTC, zivkovicmilos commented on docs/edge/faq/Validators.md
> +You can find [here](/docs/edge/consensus/pos-stake-unstake) a guide on how to stake funds, so that a node can become a validator, and how to unstake (remove the validator).
Typo, should be `You can find a guide on how to stake funds here...`

2022-07-27 14:48 UTC, zivkovicmilos commented on docs/edge/faq/Validators.md
> +Obs:
What is `0bs`?

2022-07-27 14:49 UTC, zivkovicmilos commented on docs/edge/faq/Validators.md
> +- Be aware that there is a default threshold of `1 ETH` for becoming a validator.
It's not `1 ETH`. It's 1 unit of native network (gas) currency.

2022-07-27 14:49 UTC, zivkovicmilos commented on docs/edge/faq/Validators.md
> +We recommend starting with 100G as a conservatively estimated runway, and making sure that it is possible to scale the disk afterwards.
@ZeljkoBenovic

Where did we get this number?

2022-07-27 14:50 UTC, zivkovicmilos commented on sidebars.js
> +
Nitpick: there is an empty space here

2022-07-27 14:50 UTC, zivkovicmilos commented on sidebars.js
> +
Nitpick: there is an empty space here

2022-07-27 14:51 UTC, zivkovicmilos requested changes
Looks good 👍 

There are some things that need to be changed, however

2022-07-27 15:29 UTC, laviniat1996 commented on docs/edge/faq/Gas.md
> +This sets a premined balance of 1000eth to 0x3956E90e632AEbBF34DEB49b71c28A83Bc029862 (the amount from the argument is in gwei).
fixed 3aece441bf8e53b34bcd8c47487e61bb57f1efeb

2022-07-27 15:35 UTC, laviniat1996 commented on docs/edge/faq/Contracts.md
> +description: "FAQ for Polygon Edge smart contracts"
fixed daf63233adcbfa43e630fea32a5e945dc5f835c4

2022-07-27 15:35 UTC, laviniat1996 commented on docs/edge/faq/Contracts.md
> +Yes. You can deploy a smart contract in the same manner as Ethereum.
fixed daf63233adcbfa43e630fea32a5e945dc5f835c4

2022-07-27 15:42 UTC, laviniat1996 commented on docs/edge/faq/Gas.md
> +This sets a premined balance of 1000eth to 0x3956E90e632AEbBF34DEB49b71c28A83Bc029862 (the amount from the argument is in gwei).
Thank you for noticing this.

2022-07-27 15:43 UTC, laviniat1996 commented on docs/edge/faq/Contracts.md
> +Yes. You can deploy a smart contract in the same manner as Ethereum.
Totally agree.

2022-07-27 15:56 UTC, laviniat1996 commented on docs/edge/faq/Validators.md
> +- Be aware that there is a default threshold of `1 ETH` for becoming a validator.
Thank you. Fixed the mistake cbea01b269bdb2416a68ad1b7534d2be9e6c9232

2022-07-27 15:56 UTC, laviniat1996 commented on docs/edge/faq/Validators.md
> +Obs:
Obs would be short for observations, but you are right that it is confusing. Fixed cbea01b269bdb2416a68ad1b7534d2be9e6c9232

2022-07-27 15:57 UTC, laviniat1996 commented on docs/edge/faq/Validators.md
> +You can find [here](/docs/edge/consensus/pos-stake-unstake) a guide on how to stake funds, so that a node can become a validator, and how to unstake (remove the validator).
Agree. Fixed cbea01b269bdb2416a68ad1b7534d2be9e6c9232

2022-07-27 15:57 UTC, laviniat1996 commented on docs/edge/faq/Validators.md
> +Adding/removing validators is done by voting. You can find [here](/docs/edge/consensus/poa) a full guide about this.
Agree. Fixed cbea01b269bdb2416a68ad1b7534d2be9e6c9232

2022-07-27 15:58 UTC, laviniat1996 commented on docs/edge/faq/Validators.md
> +Polygon Edge has PoA and PoS as consensus mechanisms. PoA is the default one. For a new cluster, to switch to PoS, you will need to add the `--pos` flag when generating the genesis file. If you have
I wanted to give some context, but you are right that it's not on point. I've removed that part. Fixed cbea01b269bdb2416a68ad1b7534d2be9e6c9232

2022-07-27 16:02 UTC, laviniat1996 commented on sidebars.js
> +
It bothers me too tbh. Fixed b4645794bc3b8f7f5c6b5bdfc27f94094f27e936

2022-07-27 16:02 UTC, laviniat1996 commented on sidebars.js
> +
Fixed b4645794bc3b8f7f5c6b5bdfc27f94094f27e936

2022-07-27 16:02 UTC, laviniat1996 commented on sidebars.js
> +
Fixed b4645794bc3b8f7f5c6b5bdfc27f94094f27e936

2022-07-27 16:10 UTC, laviniat1996 commented
@zivkovicmilos Do you think that this 14b2dee2f28e54907f694195415f2c82ea367e2e addition would be useful?

2022-07-27 16:36 UTC, zivkovicmilos commented on sidebars.js
> +
This empty space is still there 🙂

2022-07-27 16:37 UTC, zivkovicmilos commented on docs/edge/faq/Validators.md
> +## Is there a maximum number of validators?
I would rephrase this to 
`Is there a limit to the number of validators`?

2022-07-27 16:55 UTC, laviniat1996 commented on sidebars.js
> +
:( fixed for good b5cecb2a5b5df07552f12f7f504ef7f0d5a8c9cc

2022-07-27 16:56 UTC, laviniat1996 commented on docs/edge/faq/Validators.md
> +## Is there a maximum number of validators?
Fixed 55cb236ff67bf9e3e1f3bf0e6725a5ad90e845df

2022-07-28 08:31 UTC, zivkovicmilos commented on docs/edge/faq/Validators.md
> +We recommend starting with 100G as a conservatively estimated runway, and making sure that it is possible to scale the disk afterwards.
Discussed this internally so I'm resolving

2022-07-28 08:33 UTC, zivkovicmilos approved these changes
Thank you for resolving the comments 🙏 

Looks good 💯

2022-07-28 08:34 UTC, merged