Add documentation on SC predeployment
maticnetwork/matic-docs pull request #1028
Opened 2022-08-04 15:51 UTC by zivkovicmilos

# Description

This PR adds support to the Edge documentation on the newly added SC predeployment functionality.

2022-08-15 11:41 UTC, ZeljkoBenovic requested changes
Since you're adding a new page, a `sidebars.js` entry is missing.

2022-08-15 11:41 UTC, ZeljkoBenovic commented on docs/edge/additional-features/predeployment.md
> +Smart Contracts to be present and queriable from block `1`, at a certain address they specify.
Typo here, should be `queryable` .

2022-08-26 08:57 UTC, Kourin1996 commented
I can't see new page because sidebars is not updated

2022-08-26 09:11 UTC, Kourin1996 commented on docs/edge/additional-features/predeployment.md
> +import "hardhat/console.sol";
Why import "hardhat/console.sol";?

2022-08-26 09:14 UTC, Kourin1996 commented on docs/edge/additional-features/predeployment.md
> +`polygon-edge genesis predeploy --chain ./genesis.json --predeploy-address "0x01110" --constructor-args "[[a],[b]]" --constructor-args "[123, 456]" --constructor-args "myArg"`
Doesn't this example need `--artifacts-path`?

2022-10-07 01:49 UTC, laviniat1996 commented
@zivkovicmilos You forgot to add in sidebars.js the new page "edge/additional-features/predeployment". It won't show up otherwise.

2022-10-07 10:05 UTC, zivkovicmilos commented on docs/edge/additional-features/predeployment.md
> +Smart Contracts to be present and queriable from block `1`, at a certain address they specify.
Good catch 💯 

Fixed:

[76a9f91](https://github.com/maticnetwork/matic-docs/pull/1028/commits/76a9f91a4c6c68f218e4eeaceae00ec1bad66ee1)

2022-10-07 10:06 UTC, zivkovicmilos commented on docs/edge/additional-features/predeployment.md
> +import "hardhat/console.sol";
It's leftover 🤦‍♂️ 

[a0556c7](https://github.com/maticnetwork/matic-docs/pull/1028/commits/a0556c7cc2b87fc702a8d0100463afbd940ed7d0)

2022-10-07 10:09 UTC, zivkovicmilos commented on docs/edge/additional-features/predeployment.md
> +`polygon-edge genesis predeploy --chain ./genesis.json --predeploy-address "0x01110" --constructor-args "[[a],[b]]" --constructor-args "[123, 456]" --constructor-args "myArg"`
Good catch 💯 

Added:
[2ba616d](https://github.com/maticnetwork/matic-docs/pull/1028/commits/2ba616dd94af0991a2f2ffb74de717cf3a59f3f0)

2022-10-07 10:11 UTC, zivkovicmilos commented
@laviniat1996 @Kourin1996 

Added the missing sidebars entry 🤦‍♂️ 
[082d74a](https://github.com/maticnetwork/matic-docs/pull/1028/commits/082d74af0892367538ad8cd3fd5e970f7b9ade60)

2022-10-07 10:12 UTC, Kourin1996 approved these changes

2022-10-07 10:41 UTC, ZeljkoBenovic approved these changes
LGTM

2022-10-07 10:45 UTC, merged