Add covalent reference doc
maticnetwork/matic-docs pull request #1046
Opened 2022-08-15 07:28 UTC by DannyS03

- adds guide for using covalent api with polygon
- references covalent content

2022-08-15 14:23 UTC, cerberushades requested changes

2022-08-15 14:23 UTC, cerberushades commented on docs/develop/data/covalent.md
> +with PoS based side chains that provides a solution for faster and extremely
```suggestion
with PoS based sidechains that provides a solution for faster and extremely 
```

2022-08-15 14:23 UTC, cerberushades commented on docs/develop/data/covalent.md
> +Check out **[this introduction video](https://www.youtube.com/watch?v=qhibXxKANWE)**
```suggestion
Check out **[<ins>this introduction video</ins>](https://www.youtube.com/watch?v=qhibXxKANWE)** 
```

2022-08-15 14:23 UTC, cerberushades commented on docs/develop/data/covalent.md
> +are available on the [Covalent API documentation](https://www.covalenthq.com/docs/api/).
```suggestion
are available on the [<ins>Covalent API documentation</ins>](https://www.covalenthq.com/docs/api/).
```

2022-08-15 14:23 UTC, cerberushades commented on docs/develop/data/covalent.md
> +Covalent maintains an on-chain real-time mapping of token addresses between Ethereum mainnet and the Matic chain. These addresses are used to reverse-lookup prices on Matic and also to return the rig
```suggestion
Covalent maintains an on-chain real-time mapping of token addresses between the Ethereum mainnet and the Matic chain. These addresses are used to reverse-lookup prices on Matic and also to return the right token logo URLs.
```

2022-08-15 14:23 UTC, cerberushades commented on docs/develop/data/covalent.md
> +Covalent maintains an on-chain real-time mapping of token addresses between Ethereum mainnet and the Matic chain. These addresses are used to reverse-lookup prices on Matic and also to return the rig
Are we keeping this "Matic chain"?

2022-08-15 14:23 UTC, cerberushades commented on docs/develop/data/covalent.md
> +* [GetBlock](../../service-providers/getblock)
@DannyS03 they're all broken.

2022-08-16 12:51 UTC, DannyS03 commented on docs/develop/data/covalent.md
> +* [GetBlock](../../service-providers/getblock)
removed links as they are redundant

2022-08-17 18:37 UTC, cerberushades approved these changes

2022-08-17 18:37 UTC, merged