[Polygon Edge] Add BLS feature description
maticnetwork/matic-docs pull request #1066
Opened 2022-08-22 07:19 UTC by Kourin1996

This PR adds the description of BLS feature in Polygon Edge, being implemented in https://github.com/0xPolygon/polygon-edge/pull/649.

2022-08-25 22:19 UTC, laviniat1996 commented on docs/edge/configuration/manage-private-keys.md
> +BLS feature is optional and you can choose whether to use BLS or not. Refer [BLS](/docs/edge/consensus/bls) for more details.
I would suggest "**The** BLS feature" instead of "BLS feature". Also, a comma after and: "..is optional**,** and"

2022-08-25 22:29 UTC, laviniat1996 commented on docs/edge/consensus/bls.md
> +BLS is a signing algorithm that can aggregate multiple signatures into a single bytes array signature. In Polygon Edge, BLS can be used to generate `CommittedSeals` and `ParentCommittedSeals` in IBFT
I would suggest using "arrays" instead of "array".  

"The ECDSA key" instead of "ECDSA key".

I would suggest "...whether the BLS mode is enabled or not, because `ProposerSeal`, which is signed by Block Proposer, is signed by ECDSA in both modes. "

2022-08-25 22:34 UTC, laviniat1996 commented on docs/edge/consensus/bls.md
> +As mentioned above, `secrets init` with `--bls` flag can generate BLS key. In order to keep existing ECDSA and Network key and add a new BLS key, `--ecdsa` and `--network` needs to be disabled.
I would suggest "generate **the** BLS key".
"keep **the** existing"
"need" instead of "needs"

2022-08-25 22:37 UTC, laviniat1996 commented on docs/edge/consensus/bls.md
> +
I would suggest "specify **the** validator" instead of "specify validator".
Also "**The** Address and BLS Public Keys" instead of "Address and BLS Public Keys"

2022-08-25 22:39 UTC, laviniat1996 commented on docs/edge/consensus/bls.md
> +After fork is added and validators are restarted, each validator needs to call staking contract to register BLS Public Key. This must be done after the height specified in `--deployment` before the h
I would suggest "After **the** fork" instead of "After fork".

2022-08-25 22:40 UTC, laviniat1996 commented on docs/edge/consensus/bls.md
> +The following command register BLS Public Key given in `.env` to the contract.
I would suggest "registers the BLS" instead of "register BLS".

2022-08-25 22:42 UTC, laviniat1996 commented on docs/edge/consensus/bls.md
> +If the data directories are not in locally, you can specify validator address and BLS Public Key for `--ibft-validator` flag. The format of the value is `[ADDRESS_HEX]:[BLS_PUBLIC_KEY_HEX]` whose val
I would suggest "you can specify **the** validator address" instead of "you can specify validator address".

2022-08-25 22:43 UTC, laviniat1996 commented on docs/edge/consensus/bls.md
> +As mentioned above, `secrets init` with `--bls` flag can generate BLS key. In order to keep existing ECDSA and Network key and add a new BLS key, `--ecdsa` and `--network` needs to be disabled.
I would suggest "`--ecdsa` and `--network` need" instead of "`--ecdsa` and `--network` needs".

2022-08-26 10:34 UTC, Kourin1996 commented on docs/edge/configuration/manage-private-keys.md
> +BLS feature is optional and you can choose whether to use BLS or not. Refer [BLS](/docs/edge/consensus/bls) for more details.
Fixed f8592ed9b0b55af5c64d9eacf501711c94ca425e

2022-08-26 10:38 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +BLS is a signing algorithm that can aggregate multiple signatures into a single bytes array signature. In Polygon Edge, BLS can be used to generate `CommittedSeals` and `ParentCommittedSeals` in IBFT
Fixed 4d9cf4e06756f63282b5d0e116da8f987b4abd8d

2022-08-26 10:39 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +As mentioned above, `secrets init` with `--bls` flag can generate BLS key. In order to keep existing ECDSA and Network key and add a new BLS key, `--ecdsa` and `--network` needs to be disabled.
Fixed 29002bb2c80dbaa4be40545ce90fc62aa3d82062

2022-08-26 10:42 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +
Fixed d3556bf189f279aeae285338c4178fca791eb343

2022-08-26 10:45 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +After fork is added and validators are restarted, each validator needs to call staking contract to register BLS Public Key. This must be done after the height specified in `--deployment` before the h
Fixed e3263396a6f8ff3b8eb093941010f439e104172f

2022-08-26 10:45 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +The following command register BLS Public Key given in `.env` to the contract.
Fixed f3da66a031a326ee097ee8b7d26be9e60b476a5f

2022-08-26 10:46 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +If the data directories are not in locally, you can specify validator address and BLS Public Key for `--ibft-validator` flag. The format of the value is `[ADDRESS_HEX]:[BLS_PUBLIC_KEY_HEX]` whose val
Fixed d3556bf189f279aeae285338c4178fca791eb343

2022-08-26 10:47 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +As mentioned above, `secrets init` with `--bls` flag can generate BLS key. In order to keep existing ECDSA and Network key and add a new BLS key, `--ecdsa` and `--network` needs to be disabled.
Fixed 7703b3012b74005d7144ecca9179260b060e0fb2

2022-08-26 10:59 UTC, laviniat1996 approved these changes

2022-08-28 20:40 UTC, Aleksao998 requested changes
Some flags that we have introduced with BLS PR are missing in CLI-commands doc

example:
`ibft.go propose --bls`

Can you please double check if all commands are added :)

2022-08-28 22:01 UTC, Aleksao998 commented on docs/edge/consensus/bls.md
> +`ibft switch` command adds fork setting, which enables BLS in the middle, into `genesis.json`.
Do you think it would be useful to have a separate page inside consensus just for forks? There we can have an explanation of what forks are, and why we need them. And also which forks we support.

Just opening a topic for a discussion

@zivkovicmilos @laviniat1996

2022-08-28 22:02 UTC, Aleksao998 commented on docs/edge/consensus/bls.md
> +## How to migrate from an existing PoA chain
I would rename title to be more specific. Something like:

How to migrate from an existing PoA ECDSA chain to the PoA BLS chain. 

Just a suggestion? What do you think

2022-08-28 22:04 UTC, Aleksao998 reviewed
The default mode is going to be BLS. We should point out that in the Local Setup and Cloud Setup.

2022-08-31 22:27 UTC, laviniat1996 commented on docs/edge/consensus/pos-stake-unstake.md
> +* **BLS_PUBLIC_KEY** - BLS public key of the staker. Only needed if the network is running with the BLS
@Aleksao998  Maybe here would be better "running with BLS" instead of "with the BLS". Not sure tho, up to you.

2022-08-31 22:34 UTC, laviniat1996 commented on docs/edge/get-started/set-up-ibft-locally.md
> +
I would suggest "which **it** does by default, **the** BLS public key is **required**" . Required is misspelled.

2022-08-31 22:35 UTC, laviniat1996 commented on docs/edge/get-started/set-up-ibft-on-the-cloud.md
> +
Same here. I would suggest "which it does by default, the BLS public key is required" . Required is misspelled.

2022-09-01 10:27 UTC, Aleksao998 approved these changes

2022-09-01 10:36 UTC, Aleksao998 commented on docs/edge/get-started/set-up-ibft-on-the-cloud.md
> +
Fixed 4057ca079823ce8d66b57dc5c893e04bb2b4e6c3

2022-09-01 10:36 UTC, Aleksao998 commented on docs/edge/get-started/set-up-ibft-locally.md
> +
Fixed 4057ca079823ce8d66b57dc5c893e04bb2b4e6c3

2022-09-01 10:37 UTC, Aleksao998 commented on docs/edge/consensus/pos-stake-unstake.md
> +* **BLS_PUBLIC_KEY** - BLS public key of the staker. Only needed if the network is running with the BLS
Fixed 4057ca079823ce8d66b57dc5c893e04bb2b4e6c3

2022-09-01 20:08 UTC, zivkovicmilos commented on docs/edge/configuration/manage-private-keys.md
> +The private key file mentioned about BLS is used in the consensus layer to aggregate committed seals. The size of committed seals aggregated by BLS is less than the committed seals signed by ECDSA.
What private key file?

It's the BLS private key, not the key file

2022-09-01 20:09 UTC, zivkovicmilos commented on docs/edge/configuration/manage-private-keys.md
> +The private key file mentioned about BLS is used in the consensus layer to aggregate committed seals. The size of committed seals aggregated by BLS is less than the committed seals signed by ECDSA.
`is less than the committed ECDSA signatures` -> `is less than the aggregated committed ECDSA signatures`.

ECDSA is a signing scheme, not an entity that can do signing

2022-09-01 20:11 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +description: "Explanation and instructions regarding BLS mode."
Why the period in the title?

2022-09-01 20:21 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +BLS is a signing algorithm that can aggregate multiple signatures into a signature. In Polygon Edge, BLS is used by default, and can be used to generate `CommittedSeals` and `ParentCommittedSeals` in
BLS is not a signing algorithm, it's a signature scheme

2022-09-01 20:22 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +BLS is a signing algorithm that can aggregate multiple signatures into a signature. In Polygon Edge, BLS is used by default, and can be used to generate `CommittedSeals` and `ParentCommittedSeals` in
I would completely rephrase this second sentence:

`In Polygon Edge, BLS signatures are used for signature aggregation in order to provide better security in the IBFT consensus mode.`

2022-09-01 20:24 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +BLS is a signing algorithm that can aggregate multiple signatures into a signature. In Polygon Edge, BLS is used by default, and can be used to generate `CommittedSeals` and `ParentCommittedSeals` in
There are so many typos in this paragraph, that I've literally rewritten it, take a look:

BLS is a signature scheme that can aggregate multiple signatures. In Polygon Edge, BLS is used by default in order to provide better security in the IBFT consensus mode. BLS can aggregate signatures into a single byte array and reduce the block header size. Each chain can choose whether to use BLS or not. The ECDSA key is used regardless of whether the BLS mode is enabled or not.

2022-09-01 20:24 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +All validators must sign `CommittedSeal` in BLS mode. On the other hand, all validators must sign `CommittedSeal` by ECDSA in the chain that doesn't use BLS.
Drop this sentence entirely

2022-09-01 20:24 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +## How to setup new chain using BLS
Typo, `How to setup a new chain using BLS`

2022-09-01 20:25 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +To start a new network with the BLS refer the [Local Setup](/docs/edge/get-started/set-up-ibft-locally)
Typo here, it shouldn't be `the BLS`

2022-09-01 20:25 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +To start a new network with the BLS refer the [Local Setup](/docs/edge/get-started/set-up-ibft-locally)
`Refer to the`

2022-09-01 20:25 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +/ [Cloud Setup](/docs/edge/get-started/set-up-ibft-on-the-cloud) sections for detailed setup
detailed setup what? `detailed setup instructions`

2022-09-01 20:25 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +This section describes how to use BLS mode in existing PoA chain.
`the BLS mode`

2022-09-01 20:26 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +This section describes how to use BLS mode in existing PoA chain.
`in an existing`

2022-09-01 20:26 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +the following steps are required in order to enable BLS in PoA chain.
`in a PoA chain`

2022-09-01 20:26 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +2. Generate BLS keys for validators
`Generate the BLS keys`

2022-09-01 20:26 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +4. Confirm block generatation after the `from` block
Please rephrase this, I have no idea what this even means, and I've seen the code behind it

2022-09-01 20:27 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +```
Do we seriously need this explanation? I'm pretty sure people know how to kill their nodes

2022-09-01 20:27 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +As mentioned above, `secrets init` with `--bls` flag can generate the BLS key. In order to keep the existing ECDSA and Network key and add a new BLS key, `--ecdsa` and `--network` need to be disabled
Mentioned where?
I haven't seen it mentioned anywhere

2022-09-01 20:28 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +As mentioned above, `secrets init` with `--bls` flag can generate the BLS key. In order to keep the existing ECDSA and Network key and add a new BLS key, `--ecdsa` and `--network` need to be disabled
Typo, `with the...`

2022-09-01 20:28 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +`ibft switch` command adds fork setting, which enables BLS in the middle, into `genesis.json`.
`adds a fork setting`

2022-09-01 20:28 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +`ibft switch` command adds fork setting, which enables BLS in the middle, into `genesis.json`.
In the middle of what?

2022-09-01 20:30 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +For PoA chain, validators need to be given in the command. As with the way of `genesis` command, `--ibft-validators-prefix-path` or `--ibft-validator` flags can be used to specify the validator.
`For PoA networks`

2022-09-01 20:30 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +For PoA chain, validators need to be given in the command. As with the way of `genesis` command, `--ibft-validators-prefix-path` or `--ibft-validator` flags can be used to specify the validator.
This entire paragraph needs to be rewritten, it literally doesn't make sense

2022-09-01 20:31 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +Specify the height from which the chain starts BLS mode for `--from`.
`Specify the height from which the chain starts using BLS with --from.`

2022-09-01 20:32 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +Run server command to restart all validators and make sure block production happens after `from` you specified in the previous step.
How is this even a step?

Make sure your network doesn't crap out after the `from` block. What happens if it does?

Just drop this section completely

2022-09-01 20:33 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +## How to migrate from an existing ECDSA PoS chain to BLS PoS chain
`to a BLS PoS chain`

2022-09-01 20:33 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +The following steps are required in order to enable BLS in PoS chain.
`in the PoS chain`

2022-09-01 20:33 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +5. Confirm block generatation after the `from` block
Useless step

2022-09-01 20:34 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +```
Again, do we seriously need a detailed explanation on how to kill nodes?

2022-09-01 20:34 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +### 2. Generate BLS key
`Generate the BLS key`

2022-09-01 20:34 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +As mentioned above, `secrets init` with `--bls` flag can generate BLS key. In order to keep existing ECDSA and Network key and add a new BLS key, `--ecdsa` and `--network` need to be disabled.
Mentioned where?

2022-09-01 20:34 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +`ibft switch` command adds fork setting, which enables BLS in the middle, into `genesis.json`.
`adds a fork setting`

2022-09-01 20:34 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +`ibft switch` command adds fork setting, which enables BLS in the middle, into `genesis.json`.
Again, in the middle of what??

2022-09-01 20:35 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +In the PoS chain, `--ibft-validators-prefix-path` or `--ibft-validator` are not used because validator info (address and BLS Public Key) is stored in the staking contract.
Drop this paragraph entirely

2022-09-01 20:35 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +Specify the height from which the chain starts BLS mode for `--from`, and the height at which the contract is updated for `--deployment`.
`starts using the BLS mode with the from flag`

2022-09-01 20:35 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +Specify the height from which the chain starts BLS mode for `--from`, and the height at which the contract is updated for `--deployment`.
`and the height at which the contract is updated with`

2022-09-01 20:36 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +After the fork is added and validators are restarted, each validator needs to call staking contract to register BLS Public Key. This must be done after the height specified in `--deployment` before t
`call the staking contract method`. Which method?

2022-09-01 20:36 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +The following command register the BLS Public Key given in `.env` to the contract.
`registers`

2022-09-01 20:37 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +:::warning Validators need to register BLS Public Key manually
`register the`

2022-09-01 20:37 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +In BLS mode, validators must have their own address and BLS public key. The consensus layer ignores the validators that have not registered BLS public key in the contract when the consensus fetches v
`the BLS public key`

`fetches validator info`

2022-09-01 20:38 UTC, zivkovicmilos commented on docs/edge/consensus/bls.md
> +### 5. Confirm block generatation after the `from` block
Just remove this useless section...

2022-09-01 20:39 UTC, zivkovicmilos commented on docs/edge/consensus/poa.md
> +BLS public key is only neccecary if the network is running with the BLS, for the network running with the ecdsa `--bls` is unnecessary
Typo here, `necessary`

2022-09-01 20:39 UTC, zivkovicmilos commented on docs/edge/consensus/poa.md
> +BLS public key is only neccecary if the network is running with the BLS, for the network running with the ecdsa `--bls` is unnecessary
`running in BLS mode`....`not running in BLS mode`

2022-09-01 20:39 UTC, zivkovicmilos commented on docs/edge/consensus/poa.md
> +BLS public key is only neccecary if the network is running with the BLS, for the network running with the ecdsa `--bls` is unnecessary
Same as my previous 2 comments

2022-09-01 20:40 UTC, zivkovicmilos commented on docs/edge/consensus/pos-stake-unstake.md
> +* **PRIVATE_KEYS** - private keys of the staker address. Validator's key is stored under the data directory, `[DATA_DIRECTORY]/consensus/validator.key`
Why do you need to mention the directory structure?

2022-09-01 20:41 UTC, zivkovicmilos commented on docs/edge/consensus/pos-stake-unstake.md
> +If the network is running with the BLS, in order to become a validator, after staking, you need to register BLS public key.
Just put this instead
`If the network is running in BLS mode, in order for nodes to become validators, they need to register their BLS public keys after staking`

2022-09-01 20:41 UTC, zivkovicmilos commented on docs/edge/consensus/pos-stake-unstake.md
> +To do so run the command:
`This can be done with the following command:`

2022-09-01 20:42 UTC, zivkovicmilos commented on docs/edge/get-started/cli-commands.md
> +Specifies the verification type of CommittedSeals and ParentCommittedSeals in IBFT.  Possible values: `[ecdsa, bls]`. Default: `bls`.
Rephrase this so I can understand it like I'm 5.

Why even mention specific fields in the `ExtraData`?

2022-09-01 20:43 UTC, zivkovicmilos commented on docs/edge/get-started/cli-commands.md
> +2. If the network is running with BLS, the format is  `--ibft-validator [ADDRESS][BLS_PUBLIC_KEY]`.
Isn't there a `:` between the address and the BLS public key?

2022-09-01 20:44 UTC, zivkovicmilos commented on docs/edge/get-started/cli-commands.md
> +Specifies the verification type of CommittedSeals and ParentCommittedSeals in IBFT.  Possible values: `[ecdsa, bls]`. Default: `bls`.
Again, simplify this

2022-09-01 20:45 UTC, zivkovicmilos commented on docs/edge/get-started/cli-commands.md
> +Prefix path for folder directory of as IBFT validators used after the fork. Needs to be present if the flag `ibft-validator` is omitted. Available only in PoA mode.
I had an aneurysm reading the first sentence.
Please rephrase it completely so it actually has meaning and is understandable

2022-09-01 20:47 UTC, zivkovicmilos commented on docs/edge/get-started/set-up-ibft-locally.md
> +:::warning Save BLS public key
`Save the BLS public key`

2022-09-01 20:48 UTC, zivkovicmilos commented on docs/edge/get-started/set-up-ibft-locally.md
> +If the network is running with BLS, which it does by default, the BLS public key is required for proposing in the PoA mode and for staking in the PoS mode. Polygon Edge only saves BLS private key, it
`which it is`

2022-09-01 20:48 UTC, zivkovicmilos commented on docs/edge/get-started/set-up-ibft-locally.md
> +If the network is running with BLS, which it does by default, the BLS public key is required for proposing in the PoA mode and for staking in the PoS mode. Polygon Edge only saves BLS private key, it
`Polygon Edge only saves the BLS private key`

2022-09-01 20:48 UTC, zivkovicmilos commented on docs/edge/get-started/set-up-ibft-locally.md
> +If the network is running with BLS, which it does by default, the BLS public key is required for proposing in the PoA mode and for staking in the PoS mode. Polygon Edge only saves BLS private key, it
`it is the responsibility of the user to preserve the BLS public key`

2022-09-01 20:49 UTC, zivkovicmilos commented on docs/edge/get-started/set-up-ibft-locally.md
> +If the network is running with BLS, which it does by default, the BLS public key is required for proposing in the PoA mode and for staking in the PoS mode. Polygon Edge only saves BLS private key, it
Also, what does this even mean? Don't we literally have commands that will derive the public key upon request?

2022-09-01 20:49 UTC, zivkovicmilos commented on docs/edge/get-started/set-up-ibft-on-the-cloud.md
> +If the network is running with BLS, which it does by default, the BLS public key is required for proposing in the PoA mode and for staking in the PoS mode. Polygon Edge only saves BLS private key, it
Exact same comments as before

2022-09-01 20:49 UTC, zivkovicmilos approved these changes
God help us

2022-09-02 08:16 UTC, Kourin1996 commented on docs/edge/configuration/manage-private-keys.md
> +The private key file mentioned about BLS is used in the consensus layer to aggregate committed seals. The size of committed seals aggregated by BLS is less than the committed seals signed by ECDSA.
Fixed 09734aa3efa61afcac9c2af74ecf25da0eaa8079

2022-09-02 08:17 UTC, Kourin1996 commented on docs/edge/configuration/manage-private-keys.md
> +The private key file mentioned about BLS is used in the consensus layer to aggregate committed seals. The size of committed seals aggregated by BLS is less than the committed seals signed by ECDSA.
Fixed 1df5d04e507314ea88fc1e406c199a76c546c2f5

2022-09-02 08:19 UTC, Kourin1996 commented on docs/edge/configuration/manage-private-keys.md
> +The BLS feature is optional and, you can choose whether to use BLS or not. Refer [BLS](/docs/edge/consensus/bls) for more details.
Fixed 18b08620f6e9ef22e459af0edf2a945a305114c6

2022-09-02 08:20 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +description: "Explanation and instructions regarding BLS mode."
Other pages' title has period. If you want to remove it, please create a PR to remove all periods after merge this.

2022-09-02 08:26 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +BLS is a signing algorithm that can aggregate multiple signatures into a signature. In Polygon Edge, BLS is used by default, and can be used to generate `CommittedSeals` and `ParentCommittedSeals` in
Fixed 0b76e958f2ec7ef87a8af9d057445bd08aa6cd35

2022-09-02 08:29 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +BLS is a signing algorithm that can aggregate multiple signatures into a signature. In Polygon Edge, BLS is used by default, and can be used to generate `CommittedSeals` and `ParentCommittedSeals` in
Fixed 9ae9523b399a89ceb113b67deb02c51f06e10c4f

2022-09-02 08:29 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +BLS is a signing algorithm that can aggregate multiple signatures into a signature. In Polygon Edge, BLS is used by default, and can be used to generate `CommittedSeals` and `ParentCommittedSeals` in
Fixed 9ae9523b399a89ceb113b67deb02c51f06e10c4f

2022-09-02 08:30 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +All validators must sign `CommittedSeal` in BLS mode. On the other hand, all validators must sign `CommittedSeal` by ECDSA in the chain that doesn't use BLS.
Removed 306bff6e56eeb38175c000101991dd5c73f68026

2022-09-02 08:33 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +To start a new network with the BLS refer the [Local Setup](/docs/edge/get-started/set-up-ibft-locally)
Fixed b381eef66b7231297904e3be7410d2e0cc2cc71b

2022-09-02 08:33 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +/ [Cloud Setup](/docs/edge/get-started/set-up-ibft-on-the-cloud) sections for detailed setup
Fixed b381eef66b7231297904e3be7410d2e0cc2cc71b

2022-09-02 08:33 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +/ [Cloud Setup](/docs/edge/get-started/set-up-ibft-on-the-cloud) sections for detailed setup
Fixed b381eef66b7231297904e3be7410d2e0cc2cc71b

2022-09-02 08:34 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +This section describes how to use BLS mode in existing PoA chain.
Fixed 50d50e6eebd01c99d1f579f2bc31abe9dec9018a

2022-09-02 08:36 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +the following steps are required in order to enable BLS in PoA chain.
Fixed 94604324143e9079d4b25dbc0cb30ffb560f205f

2022-09-02 08:36 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +This section describes how to use BLS mode in existing PoA chain.
Fixed 94604324143e9079d4b25dbc0cb30ffb560f205f

2022-09-02 13:10 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +4. Confirm block generatation after the `from` block
Fixed 50c1f18f05e94f6fe61e0eb560c46d04cc5e73ca

2022-09-02 13:10 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +```
Removed 50c1f18f05e94f6fe61e0eb560c46d04cc5e73ca

2022-09-02 13:10 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +As mentioned above, `secrets init` with `--bls` flag can generate the BLS key. In order to keep the existing ECDSA and Network key and add a new BLS key, `--ecdsa` and `--network` need to be disabled
Removed

2022-09-02 13:11 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +As mentioned above, `secrets init` with `--bls` flag can generate the BLS key. In order to keep the existing ECDSA and Network key and add a new BLS key, `--ecdsa` and `--network` need to be disabled
Fixed 50c1f18f05e94f6fe61e0eb560c46d04cc5e73ca

2022-09-02 13:11 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +`ibft switch` command adds fork setting, which enables BLS in the middle, into `genesis.json`.
Fixed 50c1f18f05e94f6fe61e0eb560c46d04cc5e73ca

2022-09-02 13:11 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +`ibft switch` command adds fork setting, which enables BLS in the middle, into `genesis.json`.
Fixed 50c1f18f05e94f6fe61e0eb560c46d04cc5e73ca

2022-09-02 13:11 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +For PoA chain, validators need to be given in the command. As with the way of `genesis` command, `--ibft-validators-prefix-path` or `--ibft-validator` flags can be used to specify the validator.
Fixed 50c1f18f05e94f6fe61e0eb560c46d04cc5e73ca

2022-09-02 13:11 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +Specify the height from which the chain starts BLS mode for `--from`.
Fixed 50c1f18f05e94f6fe61e0eb560c46d04cc5e73ca

2022-09-02 13:13 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +For PoA chain, validators need to be given in the command. As with the way of `genesis` command, `--ibft-validators-prefix-path` or `--ibft-validator` flags can be used to specify the validator.
@zivkovicmilos Could you tell me your suggestion?

2022-09-02 13:13 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +For PoA chain, validators need to be given in the command. As with the way of `genesis` command, `--ibft-validators-prefix-path` or `--ibft-validator` flags can be used to specify the validator.
I have no idea what the best explanation for you is

2022-09-02 13:14 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +Run server command to restart all validators and make sure block production happens after `from` you specified in the previous step.
Fixed the description 50c1f18f05e94f6fe61e0eb560c46d04cc5e73ca

2022-09-02 13:15 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +## How to migrate from an existing ECDSA PoS chain to BLS PoS chain
Fixed 9ba9789f2af32d5878ac00f7dce0508aafc16db2

2022-09-02 13:16 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +5. Confirm block generatation after the `from` block
Changed the step 50c1f18f05e94f6fe61e0eb560c46d04cc5e73ca

2022-09-02 13:16 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +```
Removed 50c1f18f05e94f6fe61e0eb560c46d04cc5e73ca

2022-09-02 13:17 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +As mentioned above, `secrets init` with `--bls` flag can generate BLS key. In order to keep existing ECDSA and Network key and add a new BLS key, `--ecdsa` and `--network` need to be disabled.
Fixed 50c1f18f05e94f6fe61e0eb560c46d04cc5e73ca

2022-09-02 13:17 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +`ibft switch` command adds fork setting, which enables BLS in the middle, into `genesis.json`.
Fixed 50c1f18f05e94f6fe61e0eb560c46d04cc5e73ca

2022-09-02 13:18 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +### 2. Generate BLS key
Fixed a0051af6d4928ba3b7477158ddce02b294027cab

2022-09-02 13:18 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +The following steps are required in order to enable BLS in PoS chain.
Fiexd a0051af6d4928ba3b7477158ddce02b294027cab

2022-09-02 13:18 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +This section describes how to use BLS mode in existing PoS chain.
Fixed a0051af6d4928ba3b7477158ddce02b294027cab

2022-09-02 13:19 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +In the PoS chain, `--ibft-validators-prefix-path` or `--ibft-validator` are not used because validator info (address and BLS Public Key) is stored in the staking contract.
Removed 37b2f527d04fccea96425488709e94d63ed9c001

2022-09-02 13:23 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +### 5. Confirm block generatation after the `from` block
Changed 50c1f18f05e94f6fe61e0eb560c46d04cc5e73ca

2022-09-02 13:24 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +In BLS mode, validators must have their own address and BLS public key. The consensus layer ignores the validators that have not registered BLS public key in the contract when the consensus fetches v
Fixed 3a236c2eeb4df2b68f4f28609675ee097f2e812a

2022-09-02 13:24 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +The following command register the BLS Public Key given in `.env` to the contract.
Fixed 3a236c2eeb4df2b68f4f28609675ee097f2e812a

2022-09-02 13:24 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +After the fork is added and validators are restarted, each validator needs to call staking contract to register BLS Public Key. This must be done after the height specified in `--deployment` before t
Fixed 3a236c2eeb4df2b68f4f28609675ee097f2e812a

2022-09-02 13:24 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +Specify the height from which the chain starts BLS mode for `--from`, and the height at which the contract is updated for `--deployment`.
Fixed 3a236c2eeb4df2b68f4f28609675ee097f2e812a

2022-09-02 13:24 UTC, Kourin1996 commented on docs/edge/consensus/bls.md
> +Specify the height from which the chain starts BLS mode for `--from`, and the height at which the contract is updated for `--deployment`.
Fixed 3a236c2eeb4df2b68f4f28609675ee097f2e812a

2022-09-02 13:27 UTC, Kourin1996 commented on docs/edge/consensus/poa.md
> +BLS public key is only neccecary if the network is running with the BLS, for the network running with the ecdsa `--bls` is unnecessary
Fixed 514fe64720a9ffe731a6880248f0c75fb1f9461c

2022-09-02 13:28 UTC, Kourin1996 commented on docs/edge/consensus/poa.md
> +BLS public key is only neccecary if the network is running with the BLS, for the network running with the ecdsa `--bls` is unnecessary
Fixed 514fe64720a9ffe731a6880248f0c75fb1f9461c

2022-09-02 13:29 UTC, Kourin1996 commented on docs/edge/consensus/pos-stake-unstake.md
> +* **PRIVATE_KEYS** - private keys of the staker address. Validator's key is stored under the data directory, `[DATA_DIRECTORY]/consensus/validator.key`
Removed f5bde4d3f74ad2577a23baf851db9aecf938a2d3

2022-09-02 13:32 UTC, Kourin1996 commented on docs/edge/consensus/pos-stake-unstake.md
> +If the network is running with the BLS, in order to become a validator, after staking, you need to register BLS public key.
Fixed a0a84c107f9a3e45bf895b22e6b2399e5a1f7130

2022-09-02 13:32 UTC, Kourin1996 commented on docs/edge/consensus/pos-stake-unstake.md
> +To do so run the command:
Fixed a0a84c107f9a3e45bf895b22e6b2399e5a1f7130

2022-09-02 13:34 UTC, Kourin1996 commented on docs/edge/get-started/cli-commands.md
> +2. If the network is running with BLS, the format is  `--ibft-validator [ADDRESS][BLS_PUBLIC_KEY]`.
Fixed 0c0932b577bd9ad96637bdecca92de1fd0cbb7e7

2022-09-02 13:37 UTC, Kourin1996 commented on docs/edge/get-started/set-up-ibft-locally.md
> +If the network is running with BLS, which it does by default, the BLS public key is required for proposing in the PoA mode and for staking in the PoS mode. Polygon Edge only saves BLS private key, it
Right now, yes. No, after a week

2022-09-02 13:37 UTC, Kourin1996 commented on docs/edge/get-started/set-up-ibft-on-the-cloud.md
> +If the network is running with BLS, which it does by default, the BLS public key is required for proposing in the PoA mode and for staking in the PoS mode. Polygon Edge only saves BLS private key, it
Fixed bb76ccfd5480be43bb63a4ea544a503d9e56a3c5

2022-09-02 13:37 UTC, Kourin1996 commented on docs/edge/get-started/set-up-ibft-locally.md
> +If the network is running with BLS, which it does by default, the BLS public key is required for proposing in the PoA mode and for staking in the PoS mode. Polygon Edge only saves BLS private key, it
Fixed bb76ccfd5480be43bb63a4ea544a503d9e56a3c5

2022-09-02 13:37 UTC, Kourin1996 commented on docs/edge/get-started/set-up-ibft-locally.md
> +:::warning Save BLS public key
Fixed bb76ccfd5480be43bb63a4ea544a503d9e56a3c5

2022-09-02 13:37 UTC, Kourin1996 commented on docs/edge/get-started/set-up-ibft-locally.md
> +If the network is running with BLS, which it does by default, the BLS public key is required for proposing in the PoA mode and for staking in the PoS mode. Polygon Edge only saves BLS private key, it
Fixed bb76ccfd5480be43bb63a4ea544a503d9e56a3c5

2022-09-02 13:45 UTC, Kourin1996 commented on docs/edge/get-started/cli-commands.md
> +Specifies the verification type of CommittedSeals and ParentCommittedSeals in IBFT.  Possible values: `[ecdsa, bls]`. Default: `bls`.
Fixed f96916b6c5c175c6028827f2f181bda793346b34

2022-09-02 13:45 UTC, Kourin1996 commented on docs/edge/get-started/cli-commands.md
> +Specifies the verification type of CommittedSeals and ParentCommittedSeals in IBFT.  Possible values: `[ecdsa, bls]`. Default: `bls`.
Fixed f96916b6c5c175c6028827f2f181bda793346b34

2022-09-02 17:10 UTC, Aleksao998 approved these changes

2022-09-02 20:23 UTC, laviniat1996 approved these changes

2022-09-04 20:37 UTC, zivkovicmilos approved these changes

2022-09-05 07:47 UTC, merged