Fix broken links in getting started markdown
maticnetwork/matic-docs pull request #1081
Opened 2022-09-03 18:08 UTC by oleksis

- Added the [lychee-action](https://github.com/lycheeverse/lychee-action) GitHub Action to check for broken links in Markdown

Can check the [checklinks branch](https://github.com/oleksis/matic-docs/blob/checklinks/.github/workflows/links-fail-fast.yml) for check all the links in Markdown files

2022-09-03 21:48 UTC, oleksis commented
[links_fail_fast.yml](https://github.com/oleksis/matic-docs/blob/linkchecker-py/.github/workflows/links_fail_fast.yml) version using LinkChecker for Pyhon

2022-09-05 05:51 UTC, DannyS03 requested changes
thank you for the contribution @oleksis

2022-09-05 05:51 UTC, DannyS03 commented on .github/workflows/links-fail-fast.yml
> +          args: --verbose --no-progress './docs/develop/getting-started.md'
`args: --verbose --no-progress './docs/'`?

2022-09-05 09:10 UTC, DannyS03 commented on .github/workflows/links-fail-fast.yml
> +          args: --verbose --no-progress './docs/develop/getting-started.md'
```suggestion
          args: --verbose --no-progress './docs/
```

2022-09-05 09:10 UTC, DannyS03 approved these changes

2022-09-05 09:12 UTC, DannyS03 commented on .github/workflows/links-fail-fast.yml
> +          args: --verbose --no-progress './docs/
```suggestion
          args: --verbose --no-progress './docs
```

2022-09-05 09:16 UTC, oleksis commented on .github/workflows/links-fail-fast.yml
> +          args: --verbose --no-progress './docs/
the args in docs dir need 2 apostrofe './docs'

2022-09-05 09:21 UTC, DannyS03 commented on .github/workflows/links-fail-fast.yml
> +          args: --verbose --no-progress './docs
```suggestion
          args: --verbose --no-progress './docs/'
```

2022-09-05 09:29 UTC, oleksis commented
If [some files](https://github.com/maticnetwork/matic-docs/runs/8185517033?check_suite_focus=true#step:3:1904) builded in the build workflow the Link workflow will run after

2022-09-05 19:37 UTC, DannyS03 commented on .github/workflows/links-fail-fast.yml
> +  pull_request:
```suggestion
```

2022-09-05 19:37 UTC, DannyS03 commented on .github/workflows/links-fail-fast.yml
> +  pull_request:
```suggestion
  workflow_dispatch:
```

2022-09-05 19:38 UTC, DannyS03 commented on .github/workflows/links-fail-fast.yml
> +  push:
```suggestion
```

2022-09-05 19:44 UTC, merged