[Polygon Edge] Edit wrongly spelled PoA/ PoS/ BlockScout
maticnetwork/matic-docs pull request #1083
Opened 2022-09-05 10:42 UTC by laviniat1996

2022-09-07 10:19 UTC, Aleksao998 requested changes
Have you checked whole repo, i used find replace and found a lot of POA/POS not changed

2022-09-09 12:31 UTC, laviniat1996 commented
> Have you checked whole repo, i used find replace and found a lot of POA/POS not changed

Did you check in docs/edge or the whole repo? I

2022-09-14 20:16 UTC, zivkovicmilos approved these changes

2022-10-05 12:54 UTC, Aleksao998 approved these changes
LGTM

2022-10-05 12:55 UTC, merged