Add Crust into dStorage section
maticnetwork/matic-docs pull request #1092
Opened 2022-09-08 08:58 UTC by badkk

2022-09-08 22:51 UTC, DannyS03 requested changes
thank you for the contribution @badkk! left some suggestions. Some of the other pages will likely be updated soon too

2022-09-08 22:51 UTC, DannyS03 commented on docs/develop/crusthelpers.md
> +> To learn more about Crust, check its [Decentralized Storage market](https://wiki.crust.network/docs/en/DSM) and [Cross-chain Storage Solution](https://wiki.crust.network/docs/en/buildCrossChainSolu
```suggestion
:::info Learn more about Crust
Check out the [Decentralized Storage market](https://wiki.crust.network/docs/en/DSM) and [Cross-chain Storage Solution](https://wiki.crust.network/docs/en/buildCrossChainSolution#ii-native-ipfs-integration) documentation. You can also start building with Crust Storage by following the [Crust Build-101](https://wiki.crust.network/docs/en/build101) guide.
:::
```

2022-09-08 22:51 UTC, DannyS03 commented on docs/develop/crusthelpers.md
> +[Crust](https://crust.network) provides a decentralized storage network for Web3. It is designed to realize core values of decentralization, privacy and assurance. Crust supports multiple storage-lay
```suggestion
[Crust Network](https://crust.network) provides a decentralized storage network for web3. It is designed to realize the core values of decentralization, privacy and assurance. Crust supports multiple storage-layer protocols such as IPFS, and exposes instantly accessible on-chain storage functions to users.
```

2022-09-08 22:51 UTC, DannyS03 commented on docs/develop/crusthelpers.md
> +The Crust protocol is 100% compatible with the [IPFS](https://ipfs.io/) protocol, and it matches people who have hard drive space to spare with those who need to store data or host content. Crust sup
```suggestion
The protocol matches people who have hard drive space to spare with those who need to store data or host content. Crust supports most smart contract platforms with its cross-chain solution, including Polygon. Find out all the platforms that Crust storage supports on their [official website](https://crust.network/).
```

2022-09-08 22:51 UTC, DannyS03 commented on docs/develop/crusthelpers.md
> +- [Crust Files](https://crustfiles.io): the 1st web3 personal cloud storage build by Crust community, supports multi-web3 wallet login and provide fully decentralized and privacy storage function for
```suggestion
- [Crust Files](https://crustfiles.io): Built by the Crust community, Crust Files is first web3 personal cloud storage that supports multi-web3 wallet login and provides fully decentralized and privacy storage function for all web3 users.
```

2022-09-08 22:51 UTC, DannyS03 commented on docs/develop/crusthelpers.md
> +- [IPFS W3Auth Gateway](https://docs.ipfs.tech/concepts/ipfs-gateway/#authenticated-gateways): Web3 authenticated IPFS gateway, support all the IPFS *WRITE* functions, that helps users upload file or
```suggestion
- [IPFS W3Auth Gateway](https://docs.ipfs.tech/concepts/ipfs-gateway/#authenticated-gateways): A web3 authenticated IPFS gateway that supports all the IPFS *WRITE* functions and helps users upload files or host content after passing the W3Auth verification.
```

2022-09-08 22:51 UTC, DannyS03 commented on docs/develop/crusthelpers.md
> +- [IPFS W3Auth Pinning Service](https://wiki.crust.network/docs/en/buildIPFSW3AuthPin): A standard IPFS pinning service with web3 authentication, it allows users access Crust storage resources withou
```suggestion
- [IPFS W3Auth Pinning Service](https://wiki.crust.network/docs/en/buildIPFSW3AuthPin): A standard IPFS pinning service with web3 authentication that allows users to access Crust storage resources without needing to interact with the Crust blockchain.
```

2022-09-08 22:51 UTC, DannyS03 commented on docs/develop/crusthelpers.md
> +- [Crust Github Action](https://github.com/marketplace/actions/crust-ipfs-pin): A standard github action which can involve the fully decentralized hosting CI/CD with Crust.
```suggestion
- [Crust Github Action](https://github.com/marketplace/actions/crust-ipfs-pin): A standard GitHub action which can include fully decentralized CI/CD hosting with Crust.
```

2022-09-08 22:51 UTC, DannyS03 commented on docs/home/blockchain-basics/basics-consensus-mechanism.md
> +This kind of consensus mechanism is useful in decentralized file storage applications like storj.io, filecoin, crust, where nodes prove they have legitimate capacity in their hardware. Sometimes also
```suggestion
This kind of consensus mechanism is useful in decentralized file storage applications like in Storj.io, Filecoin, and Crust, where nodes prove they have legitimate capacity in their hardware. Sometimes also referred as PoStorage or PoCapacity.
```

2022-09-13 09:51 UTC, badkk commented
> thank you for the contribution @badkk! left some suggestions. Some of the other pages will likely be updated soon too

Thank you so much for your comments @DannyS03 ! I've already changed and updated, please take a look!

2022-09-13 16:51 UTC, DannyS03 requested changes
thanks @badkk! Just a few more minor suggestions

2022-09-13 16:51 UTC, DannyS03 commented on docs/develop/crusthelpers.md
```suggestion
:::
```

2022-09-13 16:51 UTC, DannyS03 commented on docs/develop/crusthelpers.md
> +Check its [Decentralized Storage market](https://wiki.crust.network/docs/en/DSM) and [Cross-chain Storage Solution](https://wiki.crust.network/docs/en/buildCrossChainSolution#ii-native-ipfs-integrati
```suggestion
Check out the [Decentralized Storage market](https://wiki.crust.network/docs/en/DSM) and [Cross-chain Storage Solution](https://wiki.crust.network/docs/en/buildCrossChainSolution#ii-native-ipfs-integration) offered by Crust Network. Also, you can start building with [Crust Build-101](https://wiki.crust.network/docs/en/build101).
```

2022-09-13 16:51 UTC, DannyS03 commented on docs/develop/crusthelpers.md
> +- [Crust Files](https://crustfiles.io): Built by the Crust community, Crust Files is first web3 personal cloud storage that supports multi-web3 wallet login and provides fully decentralized and priva
```suggestion
- [Crust Files](https://crustfiles.io): Built by the Crust community, Crust Files is the first personal cloud storage for web3 that supports multi-web3 wallet login and provides fully decentralized and privacy storage function for all users.
```

2022-09-14 04:31 UTC, badkk commented
> thanks @badkk! Just a few more minor suggestions

Sure! @DannyS03 Already solved!

2022-09-14 04:34 UTC, DannyS03 commented
cheers @badkk

2022-09-14 13:58 UTC, DannyS03 approved these changes

2022-09-14 13:58 UTC, merged