subgraph docs
maticnetwork/matic-docs pull request #1093
Opened 2022-09-08 15:23 UTC by chidubemokeke

Detailed subgraph documentation that defines the entities, explains how to query the subgraph, and lists examples of queries. This is helpful for any data consumer that intends to use your subgraph

2022-09-09 22:08 UTC, DannyS03 requested changes
Thank you for the contribution @chidubemokeke! 

- The descriptions for the entires seem to be missing.
- Can we also an additional note on how to use the explorer and the playground?
- Let's also change the metadata to follow [this format](https://wiki.polygon.technology/docs/contribute/writing-style#static-site-generator).

2022-09-09 22:08 UTC, DannyS03 commented on docs/develop/data/subgraph-data.md
> +This subgraph is can be used to query Polygon data.
```suggestion
This subgraph can be used to query on-chain Polygon data. The subgraph data is serviced by a decentralized group of server operators called [Indexers](https://thegraph.com/docs/en/network/indexing/).

```

2022-09-09 22:08 UTC, DannyS03 commented on docs/develop/data/subgraph-data.md
> +Subgraph information is serviced by a decentralized group of server operators called Indexers.
```suggestion
:::tip Get started
Learn more about how subgraphs work by checking out [The Graph's official documentation](https://thegraph.com/docs/en/). 
:::
```

2022-09-09 22:08 UTC, DannyS03 commented on docs/develop/data/subgraph-data.md
> +## Ethereum Mainnet
```suggestion
## Helpful resources
```

2022-09-09 22:08 UTC, DannyS03 commented on docs/develop/data/subgraph-data.md
> +## Helpful Links
```suggestion
```

2022-09-09 22:08 UTC, DannyS03 commented on docs/develop/data/subgraph-data.md
> +
```suggestion
```

2022-09-09 22:08 UTC, DannyS03 commented on docs/develop/data/subgraph-data.md
> +[Querying from an Application](https://thegraph.com/docs/en/developer/querying-from-your-app/)
```suggestion
- [Querying from an application](https://thegraph.com/docs/en/developer/querying-from-your-app/)
```

2022-09-09 22:08 UTC, DannyS03 commented on docs/develop/data/subgraph-data.md
> +
```suggestion
```

2022-09-09 22:08 UTC, DannyS03 commented on docs/develop/data/subgraph-data.md
> +[Managing your API Key & Setting your indexer preferences](https://thegraph.com/docs/en/studio/managing-api-keys/)
```suggestion
- [Managing your API Key & setting your indexer preferences](https://thegraph.com/docs/en/studio/managing-api-keys/)
```

2022-09-09 22:08 UTC, DannyS03 commented on docs/develop/data/subgraph-data.md
> +
```suggestion
```

2022-09-09 22:08 UTC, DannyS03 commented on docs/develop/data/subgraph-data.md
> +
```suggestion
```

2022-09-09 22:08 UTC, DannyS03 commented on docs/develop/data/subgraph-data.md
> +[Creating an API Key Video Tutorial](https://www.youtube.com/watch?v=UrfIpm-Vlgs)
```suggestion
[Video tutorial on creating an API Key](https://www.youtube.com/watch?v=UrfIpm-Vlgs)
```

2022-09-14 20:08 UTC, DannyS03 requested changes
thanks @chidubemokeke! seems like we are only missing the reference in `sidebars.js` + a modification to the `id` name. For *entities.md*, it can be something like `id: graph-entities`, for queries: `id: graph-queries`, data: `graph-data`.

We may have forgotten to mention this in the contributor guide, but follows [this](https://docusaurus.io/docs/sidebar).

2022-09-15 16:00 UTC, chidubemokeke commented on docs/develop/data/queries.md
> +Below are some sampl queries you can use to gather information from polygon root subgraph
Done

2022-09-15 16:00 UTC, chidubemokeke commented on docs/develop/data/subgraph-data.md
> +Subgraph information is serviced by a decentralized group of server operators called Indexers.
Done

2022-09-15 16:01 UTC, chidubemokeke commented on docs/develop/data/subgraph-data.md
> +## Helpful Links
Done

2022-09-15 17:38 UTC, DannyS03 commented on docs/develop/data/graph-data.md
> +id: Subgraph data
```suggestion
id: graph-data
```

2022-09-15 17:39 UTC, DannyS03 commented on docs/develop/data/graph-entities.md
> +id: Subgraph entities
```suggestion
id: graph-entities
```

2022-09-15 17:39 UTC, DannyS03 commented on docs/develop/data/graph-queries.md
> +id: Query subgraphs
```suggestion
id: graph-queries
```

2022-09-15 17:50 UTC, DannyS03 approved these changes
thanks again @chidubemokeke! Just changed the file ids which didn't match the ids in `sidebars.js`.

2022-09-15 17:51 UTC, merged