Updated Running Node from Binaries Docs
maticnetwork/matic-docs pull request #1096
Opened 2022-09-12 12:26 UTC by ashucoder9

1. Updated the Running Node from Binaries Documentation.

2. Also made a minuscule change to getting-started.md

2022-09-12 21:00 UTC, DannyS03 requested changes
thanks @ashucoder9! Added suggestions. Based on our discussion we can also separate the networks with tabs.

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +- You will need to add a few details in the `config.toml` file. To open the `config.toml` file, run the following command `vi ~/.heimdalld/config/config.toml`
```suggestion
- You will need to add a few details in the `config.toml` file. To open and edit the `config.toml` file, run the following command: `vi ~/.heimdalld/config/config.toml`.
```

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +- Install Heimdall and Bor binaries on the Full Node Machine
```suggestion
- Install Heimdall and Bor binaries on the full node machine
```

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +- Set up Heimdall and Bor services on the Full Node Machine
```suggestion
- Set up Heimdall and Bor services on the full node machine
```

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +- Start the Full Node Machine
```suggestion
- Start the full node machine
```

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +- Check Node health with the community
```suggestion
- Check node health with the community
```

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +This is **required** for your full node. In order to install, run the below command:
```suggestion
This is **required** for your full node. In order to install, run the following command:
```

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +### **Install GO**
```suggestion
### **Install Go**
```

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +This is also **required** for running your full node. Installing **v1.18 or above** is recommended.
```suggestion
This is also **required** for running your full node. Installing Go **v1.18 or above** is recommended.
```

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +RabbitMQ is a message-queueing software also known as a message broker or queue manager. Simply said, it is a software where queues are defined to which applications connect, in order to transfer a m
```suggestion
RabbitMQ is a message-queueing software (also known as a message broker or queue manager), where queues are defined for applications to transfer messages.
```

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +A helper service called `bridge` which is embedded into Heimdall codebase requires `rabbit-mq` to queue transactions to multiple networks. Installing it should be pretty straightforward.
```suggestion
A helper service called `bridge` is embedded into the Heimdall codebase, which requires `rabbit-mq` to queue transactions to multiple networks. Installing it should be pretty straightforward.
```

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +# For eg: git checkout v0.2.1-mumbai
```suggestion
# For e.g: git checkout v0.2.1-mumbai
```

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +Install the latest version of Bor. Make sure you git checkout the correct [released version](https://github.com/maticnetwork/bor/releases) via Git.
```suggestion
Install the latest version of Bor. Make sure you git checkout to the correct [released version](https://github.com/maticnetwork/bor/releases).
```

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +Install the latest version of Heimdall. Make sure you git checkout the correct [release version](https://github.com/maticnetwork/heimdall/releases).
```suggestion
Install the latest version of Heimdall. Make sure you git checkout to the correct [release version](https://github.com/maticnetwork/heimdall/releases).
```

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +This will install the `bor` binary and `bootnode` binary. Verify that everything is OK:
```suggestion
This will install the `bor` and `bootnode` binaries. Verify the installation by checking the Bor version on your machine:
```

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +To set up the network directory, network name and type of node are required.
```suggestion
To set up the network directory, the network name and type of node are required.
```

2022-09-12 21:00 UTC, DannyS03 commented on docs/develop/network-details/full-node-binaries.md
> +Logs are managed by `journalctl` linux tool. Here is a link for advanced usage: [How To Use Journalctl to View and Manipulate Systemd Logs](https://www.digitalocean.com/community/tutorials/how-to-use
```suggestion
Logs can be managed by the `journalctl` linux tool. Here is a tutorial for advanced usage: [How To Use Journalctl to View and Manipulate Systemd Logs](https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs).
```

2022-09-13 04:57 UTC, ashucoder9 commented on docs/develop/network-details/full-node-binaries.md
> +- Install Heimdall and Bor binaries on the Full Node Machine
Shouldn't we keep the Full Node in caps?

2022-09-13 05:13 UTC, ashucoder9 commented on docs/develop/network-details/full-node-binaries.md
> +Install the latest version of Heimdall and services. Make sure you checkout the correct [released version](https://github.com/maticnetwork/heimdall/releases) on Git. Note that the latest version, [He
Yeah, I got the same notion but there is a detailed description for enhancements. So I believe it fits well in the paragraph.

2022-09-13 05:19 UTC, ashucoder9 reviewed
Added the changes requested @DannyS03

2022-09-13 21:27 UTC, DannyS03 commented
@ashucoder9 did we want to add tabs too?

2022-09-14 13:18 UTC, ashucoder9 commented
I'll add the changes along with removing the tabs. Will create a new PR for that. Closing this one for now and syncing the changes that you requested into the branch.

2022-09-14 15:32 UTC, cerberushades submitted a review, later dismissed

2022-09-14 15:32 UTC, cerberushades commented on docs/develop/network-details/full-node-binaries.md
> +This section guides you through starting and running a full node on a binary. For the system requirements, see the [Minimum Technical Requirements](https://docs.polygon.technology/docs/develop/networ
```suggestion
This section guides you through starting and running a full node on a binary. For the system requirements, see the [Minimum Technical Requirements](docs/develop/network-details/technical-requirements) guide.
```

2022-09-15 18:01 UTC, merged