[Polygon Edge] Add index for server and genesis commands
maticnetwork/matic-docs pull request #1118
Opened 2022-10-04 19:05 UTC by laviniat1996

2022-10-05 14:19 UTC, Kourin1996 requested changes

2022-10-05 14:19 UTC, Kourin1996 commented on docs/edge/get-started/cli-commands.md
> +| [block-time](/docs/edge/get-started/cli-commands#block-time) | [access-control-allow-origins](/docs/edge/get-started/cli-commands#access-control-allow-origins) |
Is this required? They look inconsistent because all flags are in a table. I don't disagree with putting links for the all flags but, please consider using different style like bullet points

2022-10-05 14:51 UTC, laviniat1996 commented on docs/edge/get-started/cli-commands.md
> +| [block-time](/docs/edge/get-started/cli-commands#block-time) | [access-control-allow-origins](/docs/edge/get-started/cli-commands#access-control-allow-origins) |
@Kourin1996 I know the code looks messy, I kept thinking what would be the best option. I thought a list would be two long and wouldn't look pleasing to the eye. This is why I chose a table, to put everything in two rows.

2022-10-06 14:11 UTC, Kourin1996 approved these changes

2022-10-20 13:53 UTC, Aleksao998 approved these changes

2022-10-20 14:45 UTC, merged