Update "New To Matic" to include examples on how to query data from Polygon blockchain.
maticnetwork/matic-docs pull request #1154
Opened 2022-10-14 19:52 UTC by deric-alchemy

As discussed with Rahat Chowdhury, Polygon DevRel. Showing examples on querying basic blockchain data for new Polygon users.

Full list of changes: https://docs.google.com/document/d/1t2lOd8XEW5Bdu-3YuNl5_lv4wb-MjNaycLJw7q_VwXs/edit#

2022-10-25 18:22 UTC, DannyS03 requested changes
thank you @deric-alchemy, left a few comments.

2022-10-25 18:22 UTC, DannyS03 commented on sidebars.js
> +        "develop/network-details/access-node-alchemy",
need to remove in this PR as the file doesn't exist here

2022-10-25 18:22 UTC, DannyS03 commented on docs/home/new-to-matic.md
> +80% of web3 developers don't need to write a single smart contract - instead, most interaction with the blockchain involves reading its current state.
```suggestion
Most blockchain interactions involve reading its state.
```

2022-10-25 18:22 UTC, DannyS03 commented on docs/home/new-to-matic.md
> +If you're in that 80%, here are some examples on how to make basic requests to the blockchain.
```suggestion
Alchemy offers a reference guide on how to make basic requests to the blockchain.
Check out their guide on [how  to query Polygon](https://docs.alchemy.com/reference/polygon-sdk-examples).
```

2022-10-25 18:23 UTC, DannyS03 commented on sidebars.js
> +        "develop/network-details/access-node-alchemy",
CI will fail as a result

2022-10-31 21:33 UTC, deric-alchemy commented on sidebars.js
> +        "develop/network-details/access-node-alchemy",
resolved

2022-10-31 21:55 UTC, DannyS03 commented on docs/home/new-to-matic.md
> +* [How to Query the Polygon Blockchain](https://docs.alchemy.com/reference/polygon-sdk-examples)
```suggestion
```

2022-11-01 01:52 UTC, DannyS03 approved these changes

2022-11-01 01:52 UTC, DannyS03 commented on docs/home/new-to-matic.md
> +## Query the Blockchain
```suggestion
## Query the blockchain

```

2022-11-01 01:52 UTC, DannyS03 approved these changes

2022-11-02 12:37 UTC, merged