[Polygon Nightfall] update SDK
maticnetwork/matic-docs pull request #1166
Opened 2022-10-21 10:12 UTC by velkoskis

Updating the SDK documentation with the User API

2022-10-21 19:30 UTC, daveroga approved these changes

2022-10-24 20:44 UTC, cerberushades requested changes

2022-10-26 08:20 UTC, velkoskis commented on docs/nightfall/tools/nightfall-sdk.md
> +To learn more about how all these functionalities are working on a Protocol level, you can head to the [Protocol Docs](https://docs.polygon.technology/docs/category/nightfall-protocol/).
Great, thank you for your suggestion!

2022-10-27 18:09 UTC, cerberushades approved these changes

2022-10-27 21:08 UTC, merged