Graph docs update
maticnetwork/matic-docs pull request #1168
Opened 2022-10-23 09:23 UTC by chidubemokeke

Added new information to the subgraph-data page and fixed the anchor links on the entities page.

2022-10-23 22:56 UTC, DannyS03 commented on docs/develop/data/graph-entities.md
> +id: Subgraph entities
we can keep the same id as the sidebars won't pick up this syntax

2022-10-23 22:56 UTC, DannyS03 requested changes
thanks @chidubemokeke, just a comment on the id in the metadata

2022-10-24 04:01 UTC, chidubemokeke commented
> thanks @chidubemokeke, just a comment on the id in the metadata

Fixed.

2022-10-24 04:53 UTC, ashucoder9 approved these changes

2022-10-24 08:46 UTC, DannyS03 approved these changes

2022-10-24 08:46 UTC, merged