Update alchemy docs
maticnetwork/matic-docs pull request #1189
Opened 2022-11-03 19:42 UTC by shelleyolivia

Hey there - Shelley from Alchemy here. Added more details about our developer platform's tooling, added in our Mumbai faucet, and linked to additional smart contract / Polygon quickstart docs that readers might find helpful. Lmk of any questions, thanks!

2022-11-03 20:38 UTC, cerberushades requested changes

2022-11-03 20:38 UTC, cerberushades commented on docs/develop/alchemy.md
> +description:  Guide to deploy smart contracts using Alchemy. It's free
```suggestion
description:  Guide to deploy smart contracts using Alchemy.
```

2022-11-03 20:38 UTC, cerberushades commented on docs/develop/alchemy.md
> +There are several ways to make requests to the Polygon PoS chain. Rather than running your own node, you will use a free account on Alchemy's developer platform and interact with the Alchemy Polygon
```suggestion
There are several ways to make requests to the Polygon PoS chain. Rather than running your own node, you will use a free account on Alchemy's developer platform and interact with the Alchemy Polygon PoS API to communicate with the Polygon PoS chain. The platform consists of a full suite of developer tooling – this includes the ability to monitor requests, data analytics that demonstrates what happens under the hood during smart contract deployment, enhanced APIs (Transact, NFTs, etc), and an ethers.js SDK. 
```

2022-11-03 21:10 UTC, shelleyolivia commented on docs/develop/alchemy.md
> +description:  Guide to deploy smart contracts using Alchemy. It's free
Sounds good, thanks. For context, some users had asked us if it costs anything to sign up but I think it's clear enough :)

2022-11-03 21:11 UTC, shelleyolivia commented on docs/develop/alchemy.md
> +There are several ways to make requests to the Polygon PoS chain. Rather than running your own node, you will use a free account on Alchemy's developer platform and interact with the Alchemy Polygon
Sg, thanks

2022-11-04 08:33 UTC, ashucoder9 approved these changes

2022-11-06 15:35 UTC, DannyS03 approved these changes

2022-11-06 15:35 UTC, merged