Update Token Mapper guide and Polygon Wiki thumbnail
maticnetwork/matic-docs pull request #1192
Opened 2022-11-04 12:03 UTC by ashucoder9

2022-11-04 19:10 UTC, DannyS03 requested changes

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +The Tokens that will be minted on Polygon first and subsequently migrated to Ethereum are called **Mintable Tokens**. Meanwhile, Tokens that already exist on Ethereum but have to be moved to Polygon
```suggestion
The tokens to be minted on Polygon and subsequently migrated to Ethereum are called **mintable tokens**, whereas tokens that already exist on Ethereum and are migrated over to Polygon are referred to as **non-mintable tokens**.

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +  - PoS Bridge
```suggestion
- pos bridge
```

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +Polygon PoS Bridge is available for both Mainnet as well as Mumbai Testnet. More information about the PoS Bridge can be found [<ins>here</ins>](/docs/develop/ethereum-polygon/pos/getting-started).
```suggestion
The Polygon PoS bridge is available for both mainnet as well as Mumbai testnet. More information about the bridge can be found [<ins>here</ins>](/docs/develop/ethereum-polygon/pos/getting-started).

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +## How To Submit A Mapping Request
```suggestion
## How to submit a mapping request
```

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +Polygon PoS Bridge is available for both Mainnet as well as Mumbai Testnet. More information about the PoS Bridge can be found [<ins>here</ins>](/docs/develop/ethereum-polygon/pos/getting-started).
```suggestion
The Polygon PoS bridge is available for both mainnet as well as Mumbai testnet. More information about the bridge can be found [<ins>here</ins>](/docs/develop/ethereum-polygon/pos/getting-started).

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +## How To Submit A Mapping Request
```suggestion
## How to submit a mapping request
```

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +In case of a custom token mapping, you can visit our [Fx-Portal](/docs/develop/l1-l2-communication/fx-portal) and use the data provided to build your custom token.
```suggestion
In the case where you require custom token mapping, you can visit the [Fx-Portal](/docs/develop/l1-l2-communication/fx-portal) and use the data provided to build your custom token.

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +## Mapping Checklist
```suggestion
## Mapping checklist
```

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +### Mintable Tokens
```suggestion
### Mintable tokens
```

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +## Mapping Checklist
```suggestion
## Mapping checklist
```

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +### Mintable Tokens
```suggestion
### Mintable tokens
```

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +Checkout the documentation for Mintable tokens available at [<ins>https://wiki.polygon.technology/docs/develop/ethereum-polygon/mintable-assets</ins>](/docs/develop/ethereum-polygon/mintable-assets)
```suggestion
Checkout the documentation for mintable tokens available at [<ins>https://wiki.polygon.technology/docs/develop/ethereum-polygon/mintable-assets</ins>](/docs/develop/ethereum-polygon/mintable-assets).
```

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +4.  The mint function on the root contract can only be called by the corresponding token, **PredicateProxyAddress**. (PredicateProxyAddress for each token type can be found [here](/docs/develop/ether
```suggestion
4. The `mint` function on the *root* contract can only be called by the corresponding token, **PredicateProxyAddress**. (PredicateProxyAddress for each token type can be found [here](/docs/develop/ethereum-polygon/mintable-assets#contract-to-be-deployed-on-ethereum)).

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +  - PoS Bridge
```suggestion
- pos bridge
```

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +4.  The mint function on the root contract can only be called by the corresponding token, **PredicateProxyAddress**. (PredicateProxyAddress for each token type can be found [here](/docs/develop/ether
```suggestion
4. The `mint` function on the *root* contract can only be called by the corresponding token, **PredicateProxyAddress**. (PredicateProxyAddress for each token type can be found [here](/docs/develop/ethereum-polygon/mintable-assets#contract-to-be-deployed-on-ethereum)).
```

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +### Non-Mintable Tokens
```suggestion
### Non-mintable tokens
```

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +1. The deposit and withdraw functions are present in the child token contract. (Reference Template Contract - [ERC20](https://github.com/maticnetwork/pos-portal/blob/master/flat/ChildERC20.sol#L1492-
1. The `deposit` and `withdraw` functions are present in the *child* token contract. (Reference template contract - [ERC20](https://github.com/maticnetwork/pos-portal/blob/master/flat/ChildERC20.sol#L1492-#L1508), [ERC721](https://github.com/maticnetwork/pos-portal/blob/master/flat/ChildERC721.sol#L2157-#L2238), [ERC1155](https://github.com/maticnetwork/pos-portal/blob/master/flat/ChildERC1155.sol#L1784-#L1818)).
```

2022-11-04 19:10 UTC, DannyS03 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +## Video Guide
```suggestion
## Video guide
```

2022-11-05 05:12 UTC, ashucoder9 commented
Added changes @DannyS03

2022-11-05 14:42 UTC, DannyS03 approved these changes

2022-11-05 14:43 UTC, DannyS03 commented
nice:) feel free to merge when ready @ashucoder9

2022-11-07 08:43 UTC, merged