Update zkEVM support links
maticnetwork/matic-docs pull request #1202
Opened 2022-11-08 19:55 UTC by Nazeim

2022-11-08 20:32 UTC, DannyS03 approved these changes

2022-11-08 20:34 UTC, DannyS03 requested changes

2022-11-08 20:34 UTC, DannyS03 commented on docs/zkEVM/develop.md
> +If you need help with anything related to the Polygon zkEVM, you can raise a ticket on the [Polygon Support](https://support.polygon.technology/support/solutions/folders/82000694871) portal. Addition
```suggestion
If you need help with anything related to the Polygon zkEVM, you can raise a ticket on the Polygon Support](https://support.polygon.technology/support/tickets/new) portal, and check out the [Knowledge base](https://support.polygon.technology/support/solutions/folders/82000694871) to view the most common queries about the zkEVM. Additionally, you can reach out to the support team available on the **#zkevm-support** channel on the [Polygon Discord server](https://discord.com/invite/XvpHAxZ). Instructions for raising a zkEVM testnet support ticket are as follows:
```

2022-11-09 07:27 UTC, ashucoder9 approved these changes

2022-11-09 07:31 UTC, merged