Audits Bridges
maticnetwork/matic-docs pull request #1204
Opened 2022-11-11 01:33 UTC by cerberushades

2022-11-11 11:07 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/getting-started.md
> +| **Short description**                | DApp Developers looking for flexibility and faster withdrawals with POS system security. | DApp Developers looking for increased security guarantees with Plas
```suggestion
| **Short description**                | dApp Developers looking for flexibility and faster withdrawals with PoS system security | dApp Developers looking for increased security guarantees with Plasma exit mechanism  |
```

2022-11-11 11:08 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/getting-started.md
>  | **Withdrawal\(Polygon → Ethereum\)** | 1 checkpoint = ~ 30 mins to 6 hours                                                      | Call to the process-exit procedure on Ethereum's contract.
```suggestion
| **Withdrawal\(Polygon → Ethereum\)** | 1 checkpoint = ~ 30 mins to 6 hours                                                      | Call to the process-exit procedure on Ethereum's contract                               |
```

2022-11-11 11:10 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/erc20.md
> +Create a new file in root directory named process.env, with the following content:
```suggestion
Create a new file in the root directory named `process.env`, with the following content:
```

2022-11-11 11:12 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/erc20.md
>  **Approve**: This is a normal ERC20 approval so that **_depositManagerContract_** can call **_transferFrom_** function. Polygon Plasma client exposes **_erc20Token.approve_** method to make this call
```suggestion
**Approve**: This is a normal ERC20 approval, so `depositManagerContract` can call the `transferFrom()` function. Polygon Plasma client exposes the `erc20Token.approve()` method to make this call.
```

2022-11-11 11:24 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/erc20.md
> +User can call the **_withdraw_** function of **_getERC20TokenContract_** child token contract. This function should burn the tokens. Polygon Plasma client exposes **_withdrawStart_** method to make t
```suggestion
Users can call the `withdraw()` function of the `getERC20TokenContract` child token contract. This function should burn the tokens. Polygon Plasma client exposes the `withdrawStart()` method to make this call.
```

2022-11-11 11:28 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/erc721.md
> +Create a new file in root directory named process.env, with the following content:
```suggestion
Create a new file in the root directory named `process.env`, with the following content:
```

2022-11-11 11:28 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/erc721.md
>  **_safeDeposit_** method to make this call.
```suggestion
`safeDeposit()` method to make this call.
```

2022-11-11 11:29 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/erc721.md
> +Deposits from Ethereum to Polygon happen using a state sync mechanism and takes about ~22-30 minutes. After waiting for this time interval, it is recommended to check the balance using web3.js/matic.
```suggestion
Deposits from Ethereum to Polygon happen using a state sync mechanism and take about 22-30 minutes. After waiting for this time interval, it is recommended to check the balance using the web3.js/matic.js library or using Metamask. The explorer will show the balance only if at least one asset transfer has happened on the child chain. This [link](/docs/develop/ethereum-polygon/plasma/deposit-withdraw-event-plasma) explains how to track the deposit events.
```

2022-11-11 11:29 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/erc721.md
> +User can call **_startExitWithBurntTokens_** function of **_erc721Predicate_** contract. Polygon Plasma client exposes **_withdrawConfirm_** method to make this call. This function can be called only
```suggestion
Users can call `startExitWithBurntTokens` function of `erc721Predicate` contract. Polygon Plasma client exposes `withdrawConfirm` method to make this call. This function can be called only after the checkpoint is included in the main chain. The checkpoint inclusion can be tracked by following this [guide](/docs/develop/ethereum-polygon/plasma/deposit-withdraw-event-plasma#checkpoint-events).
```

2022-11-11 11:30 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/erc721.md
> +A user should call the **_processExits_** function of **_withdrawManager_** contract and submit the proof of burn. Upon submitting valid proof, tokens are transferred to the user. Polygon Plasma clie
```suggestion
A user should call the `processExits` function of `withdrawManager` contract and submit the proof of burn. Upon submitting valid proof, tokens are transferred to the user. Polygon Plasma client exposes `withdrawExit` method to make this call.
```

2022-11-11 11:34 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/erc721.md
> +A checkpoint, which is a representation of all transactions happening on Polygon to the ERC721 chain every 30 minutes, is regularly submitted to the mainchain erc721 contract.
```suggestion
A checkpoint, which is a representation of all transactions happening on Polygon to the ERC721 chain every 30 minutes, is regularly submitted to the main chain ERC721 contract.
```

2022-11-11 11:34 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/eth.md
> +Create a new file in root directory named process.env, with the following content:
```suggestion
Create a new file in the root directory named `process.env`, with the following content:
```

2022-11-11 11:35 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/eth.md
>  **deposit**: Deposit can be done by calling **_depositEther_** on depositManagerContract contract.
```suggestion
**deposit**: Deposit can be done by calling `depositEther()` on `depositManagerContract` contract.
```

2022-11-11 11:36 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/eth.md
> +User can call the **_withdraw_** function of **_getERC20TokenContract_** child token contract. This function should burn the tokens. Polygon Plasma client exposes **_withdrawStart_** method to make t
```suggestion
Users can call the `withdraw` function of `getERC20TokenContract` child token contract. This function should burn the tokens. Polygon Plasma client exposes `withdrawStart` method to make this call.
```

2022-11-11 11:37 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/eth.md
> +User can call the **_startExitWithBurntTokens_** function of **_erc20Predicate_** contract. Polygon Plasma client exposes the **_withdrawConfirm_** method to make this call. This function can be call
```suggestion
Users can call the `startExitWithBurntTokens()` function of `erc20Predicate` contract. Polygon Plasma client exposes the `withdrawConfirm()` method to make this call. This function can be called only after the checkpoint is included in the main chain. The checkpoint inclusion can be tracked by following this [guide](/docs/develop/ethereum-polygon/plasma/deposit-withdraw-event-plasma.md#checkpoint-events).
```

2022-11-11 11:38 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/eth.md
> +A user should call the **_processExits_** function of **_withdrawManager_** contract and submit the proof of burn. Upon submitting valid proof, tokens are transferred to the user. Polygon Plasma clie
```suggestion
A user should call the `processExits()` function of the `withdrawManager` contract and submit the proof of burn. Upon submitting valid proof, tokens are transferred to the user. Polygon Plasma client exposes `withdrawExit` method to make this call.
```

2022-11-11 11:39 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/getting-started.md
> +1. [Create a wallet](/docs/develop/metamask/hello): If you are new to wallets, then set tup a Metamask Account.
```suggestion
1. [Create a wallet](/docs/develop/metamask/hello): If you are new to wallets, then set up a Metamask Account.
```

2022-11-11 11:40 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/plasma/getting-started.md
> +   The `TEST` token, taken as an example for this tutorial, can be configured in Metamask so as to easily visualise account balances. Again note this is **optional**. You can very easily query the to
```suggestion
   The `TEST` token, taken as an example for this tutorial, can be configured in Metamask so as to easily visualize account balances. Again note this is **optional**. You can very easily query the token balances and other variables using [web3.js](https://web3js.readthedocs.io/en/1.0/)
```

2022-11-11 11:42 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/calling-contracts/erc1155.md
> +Call the **_depositFor_** function of **_RootChainManager_** contract. This function takes 3 arguments userAddress, rootToken and depositData. **_userAddress_** is the address of the user that will r
```suggestion
Call the `depositFor` function of `RootChainManager` contract. This function takes 3 arguments: `userAddress`, `rootToken`, and `depositData`. `userAddress` is the address of the user that will receive the deposit on the Polygon chain. `rootToken` is the address of the token on the main chain. `depositData` is the ABI-encoded list of ids, list of tokens and bytes data.
```

2022-11-11 11:47 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/calling-contracts/erc1155.md
> +Exit function on **_RootChainManager_** contract has to be called to unlock and receive the tokens back from **_ERC1155Predicate_**. This function takes a single bytes argument that proves the burn t
```suggestion
The exit function on `RootChainManager` contract has to be called to unlock and receive the tokens back from `ERC1155Predicate`. This function takes a single bytes argument that proves the burn transaction. Wait for the checkpoint containing the burn transaction to be submitted before calling this function. The Proof is generated by RLP encoding the following fields -
```

2022-11-11 11:49 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/calling-contracts/erc20.md
> +Call the **_depositFor_** function of **_RootChainManager_** contract. This function takes 3 arguments userAddress, rootToken and depositData. **_userAddress_** is the address of the user that will r
```suggestion
Call the `depositFor()` function of `RootChainManager` contract. This function takes 3 arguments: `userAddress`, `rootToken`, and `depositData`. `userAddress` is the address of the user that will receive the deposit on the Polygon chain. `rootToken` is the address of the token on the main chain. `depositData` is the ABI-encoded amount.
```

2022-11-11 11:49 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/calling-contracts/erc20.md
> +Exit function on **_RootChainManager_** contract has to be called to unlock and receive the tokens back from **_ERC20Predicate_**. This function takes a single bytes argument that proves the burn tra
```suggestion
The exit function on `RootChainManager` contract has to be called to unlock and receive the tokens back from `ERC20Predicate`. This function takes a single bytes argument that proves the burn transaction. Wait for the checkpoint containing the burn transaction to be submitted before calling this function. The Proof is generated by RLP encoding the following fields -
```

2022-11-11 11:50 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/calling-contracts/erc721.md
> +Note that the token needs to be mapped and tokenId has to be approved for deposit before making this call.
```suggestion
Note that the token needs to be mapped and `tokenId` has to be approved for a deposit before making this call.  
```

2022-11-11 11:51 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/calling-contracts/erc721.md
> +Call the **_depositFor_** function of **_RootChainManager_** contract. This function takes 3 arguments userAddress, rootToken and depositData. **_userAddress_** is the address of the user that will r
```suggestion
Call the `depositFor()` function of `RootChainManager` contract. This function takes 3 arguments: `userAddress`, `rootToken`, and `depositData`. `userAddress` is the address of the user that will receive the deposit on the Polygon chain. `rootToken` is the address of the token on main chain. `depositData` is the abi-encoded `tokenId`.
```

2022-11-11 11:51 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/calling-contracts/erc721.md
> +Tokens can be burned on Polygon chain by calling the **_withdraw_** function on child token contract. This function takes a single argument, **_tokenId_** indicating the token to be burned. Proof of
```suggestion
Tokens can be burned on the Polygon chain by calling the `withdraw` function on the child token contract. This function takes a single argument, `tokenId` indicating the token to be burned. Proof of this burn needs to be submitted in the exit step. So store the transaction hash.
```

2022-11-11 11:52 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/calling-contracts/erc721.md
> +Completing the cycle means calling the **exit** function on the **RootChainManager** contract which unlocks and receives the tokens back from the **ERC721Predicate**. This function takes a single byt
```suggestion
Completing the cycle means calling the `exit` function on the `RootChainManager` contract which unlocks and receives the tokens back from the `ERC721Predicate`. This function takes a single-byte argument from the `withdraw` function and uses it as proof of burn for the transaction. It's important that we wait for the checkpoint containing the burn transaction to be submitted before calling this function. The proof of burn is generated by RLP-encoding the following fields:
```

2022-11-11 11:53 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/calling-contracts/ether.md
> +Call the **_depositEtherFor_** function of **_RootChainManager_** contract. This function takes 1 argument **_userAddress_**, which is the address of the user that will receive the deposit on Polygon
```suggestion
Call the `depositEtherFor` function of `RootChainManager` contract. This function takes 1 argument - `userAddress`, which is the address of the user that will receive the deposit on the Polygon chain. The amount of ether to be deposited has to be sent as the value of the transaction.
```

2022-11-11 11:54 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/calling-contracts/ether.md
> +Since Ether is an ERC20 token on Polygon chain, its withdraw process is the same as ERC20 withdraw. Tokens can be burned by calling the **_withdraw_** function on child token contract. This function
```suggestion
Since Ether is an ERC20 token on the Polygon chain, its withdrawal process is the same as ERC20 withdrawal. Tokens can be burned by calling the `withdraw` function on the child token contract. This function takes a single argument, `amount` indicating the number of tokens to be burned. Proof of this burn needs to be submitted in the exit step. So store the transaction hash.
```

2022-11-11 11:54 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/calling-contracts/ether.md
> +Exit function on **_RootChainManager_** contract has to be called to unlock and receive the tokens back from **_EtherPredicate_**. This function takes a single bytes argument that proves the burn tra
```suggestion
The exit function on `RootChainManager` contract has to be called to unlock and receive the tokens back from `EtherPredicate`. This function takes a single bytes argument that proves the burn transaction. Wait for the checkpoint containing the burn transaction to be submitted before calling this function. The Proof is generated by RLP-encoding the following fields:
```

2022-11-11 11:56 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/deposit-withdraw-event-pos.md
> +All transactions that occur on Polygon chain are checkpointed to the Ethereum chain in frequent intervals of time by the validators. This time is around 10 mins on Mumbai and around 30 mins on Polygo
```suggestion
All transactions that occur on the Polygon chain are checkpointed to the Ethereum chain at frequent intervals of time by the validators. This time is around 10 mins on Mumbai and around 30 mins on Polygon Mainnet. The checkpoint occurs on a contract called the `RootChainContract` deployed on the Ethereum chain. The following script can be used to listen to real-time checkpoint inclusion events.
```

2022-11-11 11:58 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/getting-started.md
> +  2. Once the approval is given, the next step is to **deposit the asset**. A function call has to be made on the **RootChainManager** contract which in turn triggers the **ChildChainManager** contra
```suggestion
  2. Once the approval is given, the next step is to **deposit the asset**. A function call has to be made on the `RootChainManager` contract which in turn triggers the `ChildChainManager` contract on the Polygon chain.
```

2022-11-11 11:59 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/getting-started.md
> +Then, the first step to using the PoS bridge is mapping the **Root Token** and **Child Token**. It means that the token contract on the root chain and the token contract on the child chain have to ma
```suggestion
Then, the first step to using the PoS bridge is mapping the **Root Token** and **Child Token**. It means that the token contract on the root chain and the token contract on the child chain have to maintain a connection (called mapping) to transfer assets between themselves. If you're interested in submitting a mapping request, please do that using [this guide](/docs/develop/ethereum-polygon/submit-mapping-request/).
```

2022-11-11 11:59 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/getting-started.md
> +  3. This happens through a state sync mechanism which can be understood in detail from [here](https://docs.polygon.technology/docs/pos/state-sync/state-sync/).
```suggestion
  3. This happens through a state sync mechanism which can be understood in detail from [here](/docs/pos/state-sync/state-sync/).
```

2022-11-11 12:00 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/getting-started.md
> +  4. The **ChildChainManager** internally calls the **deposit** function of the child token contract and the corresponding amount of asset tokens are **minted to the users account**. It is important
```suggestion
  4. The `ChildChainManager` internally calls the `deposit` function of the child token contract and the corresponding amount of asset tokens are **minted to the user's account**. It is important to note that only the `ChildChainManager` can access the `deposit` function on the child token contract.
```

2022-11-11 12:01 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/getting-started.md
> +  3. Once the transaction has been added to the checkpoint, a proof of the burn transaction can be submitted on the **RootChainManager** contract on Ethereum by calling the **exit** function.
```suggestion
  3. Once the transaction has been added to the checkpoint, proof of the burn transaction can be submitted on the `RootChainManager` contract on Ethereum by calling the `exit` function.
```

2022-11-11 12:02 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc1155.md
> +This tutorial uses the Polygon Testnet ( Mumbai ) which is mapped to the Goerli Network to demonstrate the asset transfer to and fro the two blockchains. An **important thing to be noted** while foll
```suggestion
This tutorial uses the Polygon Testnet (Mumbai) which is mapped to the Goerli Network to demonstrate the asset transfer to and fro the two blockchains. An **important thing to be noted** while following this tutorial is that you should always use a Proxy address whenever it is available. For example, the `RootChainManagerProxy` address has to be used for interaction instead of the `RootChainManager` address. The **PoS contract addresses, ABI, Test Token Addresses**, and other deployment details of the PoS bridge contracts can be found [here](/docs/develop/ethereum-polygon/pos/deployment).
```

2022-11-11 12:03 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc1155.md
> +2. Call **_exit_** function on **_RootChainManager_** to submit proof of the burn transaction. This call can be made **_after checkpoint_** is submitted for the block containing the burn transaction.
```suggestion
2. Call the `exit()` function on `RootChainManager` to submit proof of the burn transaction. This call can be made after the checkpoint is submitted for the block containing the burn transaction.
```

2022-11-11 12:03 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc1155.md
> +[Deposit method](https://maticnetwork.github.io/matic.js/docs/pos/erc1155/deposit/) can be done by calling `depositFor` on the `RootChainManager` contract. Note that token needs to be mapped and appr
```suggestion
[Deposit method](https://maticnetwork.github.io/matic.js/docs/pos/erc1155/deposit/) can be done by calling `depositFor` on the `RootChainManager` contract. Note that the token needs to be mapped and approved for transfer beforehand. Once the tokens are transferred, the deposit proceeds using the `StateSync` mechanism. The Polygon `POSClient` exposes the [`depositSingleERC1155ForUser`](https://github.com/maticnetwork/matic.js/blob/4bf4fa9438d56c9b5c282f456aa2c24f6ff6083d/src/index.ts#L245) & [`depositBatchERC1155ForUser`](https://github.com/maticnetwork/matic.js/blob/4bf4fa9438d56c9b5c282f456aa2c24f6ff6083d/src/index.ts#L259) methods to make this call.
```

2022-11-11 12:04 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc1155.md
> +Deposits from Ethereum to Polygon happen using a **State Sync** mechanism and takes about ~22-30 minutes. After waiting for this time interval, it is recommended to check the balance using web3.js/ma
```suggestion
Deposits from Ethereum to Polygon happen using a **State Sync** mechanism and take about 22-30 minutes. After waiting for this time interval, it is recommended to check the balance using the web3.js/matic.js library or using Metamask. The explorer will show the balance only if at least one asset transfer has happened on the child chain. This [link](/docs/develop/ethereum-polygon/pos/deposit-withdraw-event-pos) explains how to track the deposit events.
```

2022-11-11 12:04 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc1155.md
> +Once the `checkpoint` has been **_submitted_** for the block containing the burn transaction, a user should call the `exit` function of the `RootChainManager` contract and submit the proof of burn. U
```suggestion
Once the `checkpoint` has been submitted for the block containing the burn transaction, a user should call the `exit` function of the `RootChainManager` contract and submit the proof of burn. Upon submitting valid proof, tokens are transferred to the user. Polygon PoS client exposes the `exitBatchERC1155` & `exitSingleERC1155` methods to make this call. These functions can be called only after the checkpoint is included in the main chain. The checkpoint inclusion can be tracked by following [this guide](/docs/develop/ethereum-polygon/pos/deposit-withdraw-event-pos.md#checkpoint-events).
```

2022-11-11 12:05 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc20.md
>  1. **_Burn_** tokens on Polygon chain.
```suggestion
1. Burn tokens on the Polygon chain.
```

2022-11-11 12:05 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc20.md
>  2. Call **_exit_** function on **_RootChainManager_** to submit proof of burn transaction. This call can be made **_after checkpoint_** is submitted for the block containing burn transaction.
```suggestion
2. Call `exit()` function on `RootChainManager` to submit proof of burn transaction. This call can be made after the checkpoint is submitted for the block containing the burn transaction.
```

2022-11-11 12:06 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc20.md
> +Note that the token needs to be mapped and approved for transfer beforehand. Polygon POS client exposes **_deposit_** method to make this call.
```suggestion
Note that the token needs to be mapped and approved for transfer beforehand. Polygon PoS client exposes `deposit()` method to make this call.
```

2022-11-11 12:06 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc20.md
> +Deposits from Ethereum to Polygon happen using a **State Sync** mechanism and takes about ~22-30 minutes. After waiting for this time interval, it is recommended to check the balance using web3.js/ma
```suggestion
Deposits from Ethereum to Polygon happen using a **State Sync** mechanism and take about 22-30 minutes. After waiting for this time interval, it is recommended to check the balance using the web3.js/matic.js library or using Metamask. The explorer will show the balance only if at least one asset transfer has happened on the child chain. This [<ins>link</ins>](/docs/develop/ethereum-polygon/pos/deposit-withdraw-event-pos) explains how to track deposit events.
```

2022-11-11 12:07 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc20.md
> +*withdrawStart* method can be used to initiate the withdraw process which will burn the specified amount on Polygon chain.
```suggestion
The `withdrawStart()` method can be used to initiate the withdrawal process which will burn the specified amount on the Polygon chain.
```

2022-11-11 12:07 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc20.md
> +Once the **_checkpoint_** has been **_submitted_** for the block containing the burn transaction, the user should call the **_exit_** function of the **_RootChainManager_** contract and submit the pr
```suggestion
Once the checkpoint has been submitted for the block containing the burn transaction, the user should call the `exit()` function of the `RootChainManager` contract and submit the proof of burn. Upon submitting valid proof, tokens are transferred to the user. Polygon PoS client exposes the `withdrawExit` method to make this call. This function can be called only after the checkpoint is included in the main chain. The checkpoint inclusion can be tracked by following [this guide](/docs/develop/ethereum-polygon/pos/deposit-withdraw-event-pos.md#checkpoint-events).
```

2022-11-11 12:08 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc721.md
> +This tutorial uses the Polygon Testnet ( Mumbai ) which is mapped to the Goerli Network to demonstrate the asset transfer to and from the two blockchains. An **important thing to be noted** while fol
```suggestion
This tutorial uses the Polygon Testnet ( Mumbai ) which is mapped to the Goerli Network to demonstrate the asset transfer to and from the two blockchains. An **important thing to be noted** while following this tutorial is that you should always use a Proxy address whenever it is available. For example, the `RootChainManagerProxy` address has to be used for interaction instead of the `RootChainManager` address. The **PoS contract addresses, ABI, Test Token Addresses**, and other deployment details of the PoS bridge contracts can be found [here](/docs/develop/ethereum-polygon/pos/deployment).
```

2022-11-11 12:09 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc721.md
> +2. Call **_exit_** function on **_RootChainManager_** to submit proof of burn transaction. This call can be made **_after checkpoint_** is submitted for the block containing the burn transaction.
```suggestion
2. Call the `exit` function on `RootChainManager` to submit proof of burn transaction. This call can be made after the checkpoint is submitted for the block containing the burn transaction.
```

2022-11-11 12:09 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc721.md
> +[Approve Method](https://maticnetwork.github.io/matic.js/docs/pos/erc721/approve/) is a normal ERC721 approval so that **_ERC721Predicate_** can call **_transferFrom_** function. Polygon POS client e
```suggestion
[Approve Method](https://maticnetwork.github.io/matic.js/docs/pos/erc721/approve/) is a normal ERC721 approval so that `ERC721Predicate` can call `transferFrom` function. Polygon PoS client exposes the **_approve_** method to make this call.
```

2022-11-11 12:09 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc721.md
> +[Deposit method](https://maticnetwork.github.io/matic.js/docs/pos/erc721/deposit/) can be done by calling **_depositFor_** on RootChainManager contract. Note that token needs to be mapped and approve
```suggestion
[Deposit method](https://maticnetwork.github.io/matic.js/docs/pos/erc721/deposit/) can be done by calling `depositFor` on `RootChainManager` contract. Note that the token needs to be mapped and approved for transfer beforehand. Once the tokens are transferred, the deposit proceeds using the State Sync mechanism. Polygon PoS client exposes **_depositERC721ForUser_** method to make this call.
```

2022-11-11 12:10 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc721.md
> +Deposits from Ethereum to Polygon happen using the **State Sync** mechanism and this takes about 22-30 minutes. After waiting for this time interval, it is recommended to check the balance using web3
```suggestion
Deposits from Ethereum to Polygon happen using the **State Sync** mechanism and this takes about 22-30 minutes. After waiting for this time interval, it is recommended to check the balance using the web3.js/matic.js library or using Metamask. The explorer will show the balance only if at least one asset transfer has happened on the child chain. This [<ins>link</ins>](docs/develop/ethereum-polygon/pos/deposit-withdraw-event-pos/) explains how to track deposit events.
```

2022-11-11 12:11 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/erc721.md
> +Once the **_checkpoint_** has been **_submitted_** for the block containing the burn transaction, the user should call the **_exit_** function of **_RootChainManager_** contract and submit the proof
```suggestion
Once the checkpoint has been submitted for the block containing the burn transaction, the user should call the `exit()` function of `RootChainManager` contract and submit the proof of burn. Upon submitting valid proof tokens are transferred to the user. Polygon PoS client exposes the  `withdrawExit` method to make this call. This function can be called only after the checkpoint is included in the main chain. The checkpoint inclusion can be tracked by following [this guide](/docs/develop/ethereum-polygon/pos/deposit-withdraw-event-pos/#checkpoint-events).
```

2022-11-11 12:12 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/eth.md
> +For example, please use the **RootChainManagerProxy** address for interactions instead of the **RootChainManager** address. Deployment details like the PoS contract addresses, ABI, Test Token Address
```suggestion
For example, please use the `RootChainManagerProxy` address for interactions instead of the `RootChainManager` address. Deployment details like the PoS contract addresses, ABI, and Test Token Addresses can be found [here](/docs/develop/ethereum-polygon/pos/deployment/).
```

2022-11-11 12:13 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/eth.md
> +Deposits from Ethereum to Polygon happen using the **State Sync** Mechanism and this takes about 22-30 minutes. After waiting for this time interval, it is recommended to check the balance using web3
```suggestion
Deposits from Ethereum to Polygon happen using the **State Sync** Mechanism and this takes about 22-30 minutes. After waiting for this time interval, it is recommended to check the balance using the web3.js/matic.js library or using Metamask. The explorer will show the balance only if at least one asset transfer has happened on the child chain. This [<ins>link</ins>](/docs/develop/ethereum-polygon/pos/deposit-withdraw-event-pos/) explains how to track deposit events.
```

2022-11-11 12:13 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/eth.md
> +**_ETH_** is deposited as an **_ERC20_** token on Polygon chain. For withdrawing it follow the same process as withdrawing ERC20 tokens.
```suggestion
ETH is deposited as an ERC20 token on the Polygon chain. Withdrawing follows the same process as withdrawing ERC20 tokens.
```

2022-11-11 12:15 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/pos/using-sdk/eth.md
> +Once the **checkpoint** has been submitted for the block containing the burn transaction, the user should call the **exit** function of `RootChainManager` contract and submit the proof of burn. Upon
```suggestion
Once the **checkpoint** has been submitted for the block containing the burn transaction, the user should call the **exit** function of `RootChainManager` contract and submit the proof of burn. Upon submitting valid proof tokens are transferred to the user. Polygon POS client `erc20` exposes `withdrawExit` method to make this call. This function can be called only after the checkpoint is included in the main chain. The checkpoint inclusion can be tracked by following this [guide](/docs/develop/ethereum-polygon/pos/deposit-withdraw-event-pos.md#checkpoint-events).
```

2022-11-11 12:16 UTC, ashucoder9 commented on docs/develop/ethereum-polygon/submit-mapping-request.md
> +4. The `mint` function on the ***root*** contract can only be called by the corresponding token, **PredicateProxyAddress**. (PredicateProxyAddress for each token type can be found [here](/docs/develo
```suggestion
4. The `mint` function on the `root` contract can only be called by the corresponding token, `PredicateProxyAddress`. (`PredicateProxyAddress` for each token type can be found [here](/docs/develop/ethereum-polygon/mintable-assets.md#contract-to-be-deployed-on-ethereum))
```

2022-11-11 12:17 UTC, ashucoder9 commented on docs/develop/l1-l2-communication/fx-portal.md
> +- `deposit(address rootToken, address user, uint256 amount, bytes memory data)` Call deposit() with the address of the mapped token, the address that can withdraw with a corresponding amount (along w
```suggestion
- `deposit(address rootToken, address user, uint256 amount, bytes memory data)` call deposit() method with the address of the mapped token, the address that can withdraw with a corresponding amount (along with data if needed). You must have approved the contract using the standard ERC20 `approve` function to spend your tokens first.
```

2022-11-11 12:18 UTC, ashucoder9 commented on docs/develop/l1-l2-communication/fx-portal.md
> +After you have performed `deposit()` on the root chain, it will take 22-30 minutes for state sync to happen. Once  state sync happens, you will get the tokens deposited at the given address.
```suggestion
After you have performed `deposit()` on the root chain, it will take 22-30 minutes for state sync to happen. Once state sync happens, you will get the tokens deposited at the given address.
```

2022-11-11 12:18 UTC, ashucoder9 commented on docs/develop/l1-l2-communication/fx-portal.md
> +After you have performed `deposit()` on the root chain, it will take 22-30 minutes for state sync to happen. Once  state sync happens, you will get the tokens deposited at the given address.
```suggestion
After you have performed `deposit()` on the root chain, it will take 22-30 minutes for state sync to happen. Once state sync happens, you will get the tokens deposited at the given address.
```

2022-11-11 12:19 UTC, ashucoder9 commented on docs/develop/l1-l2-communication/state-transfer.md
> +Polygon validators also periodically submit a hash of all transactions on Polygon chain to Ethereum chain. This **_Checkpoint_** can be used to verify any transaction that happened on Polygon. Once a
```suggestion
Polygon validators also periodically submit a hash of all transactions on the Polygon chain to the Ethereum chain. This **Checkpoint** can be used to verify any transaction that happened on Polygon. Once a transaction is verified to have happened on the Polygon chain, an action can be taken accordingly on Ethereum.
```

2022-11-11 12:19 UTC, ashucoder9 commented on docs/develop/l1-l2-communication/state-transfer.md
> +These 2 mechanisms can be used together to enable two-way data(state) transfer between Ethereum and Polygon. To abstract out all these interactions, you can directly inherit our **_FxBaseRootTunnel_*
```suggestion
These 2 mechanisms can be used together to enable two-way data (state) transfer between Ethereum and Polygon. To abstract out all these interactions, you can directly inherit our `FxBaseRootTunnel` (on Ethereum) and `FxBaseChildTunnel` (on Polygon) contracts.
```

2022-11-11 12:20 UTC, ashucoder9 commented on docs/develop/l1-l2-communication/state-transfer.md
> +- `function _processMessageFromRoot(uint256 stateId, address sender, bytes memory data)`: This is a virtual function that needs to implement the logic to handle messages sent from the RootTunnel.
```suggestion
- `function _processMessageFromRoot(uint256 stateId, address sender, bytes memory data)`: This is a virtual function that needs to implement the logic to handle messages sent from the `RootTunnel`.
```

2022-11-11 12:21 UTC, ashucoder9 commented on docs/develop/plasma-using-metamask.md
> +For the mainnet, Ethereum is the root chain and Polygon Mainnet is the child chain and for the testnet, Goerli is the root chain and Mumbai is the child chain. The values in config.json file should b
```suggestion
For the mainnet, Ethereum is the root chain and Polygon Mainnet is the child chain and for the testnet, Goerli is the root chain and Mumbai is the child chain. The values in the `config.json` file should be set accordingly. Goerli and Mumbai networks are used as the root and child chain in this tutorial.
```

2022-11-11 12:22 UTC, ashucoder9 commented on docs/develop/plasma-using-metamask.md
> +Deposits from Ethereum to Polygon happen using a state sync mechanism and takes about 22-30 minutes After waiting for this time interval, it is recommended to check the balance using web3.js/matic.js
```suggestion
Deposits from Ethereum to Polygon happen using a state sync mechanism and take about 22-30 minutes. After waiting for this time interval, it is recommended to check the balance using the web3.js/matic.js library or using Metamask. The explorer will show the balance only if at least one asset transfer has happened on the child chain. This [link](/docs/develop/ethereum-polygon/plasma/deposit-withdraw-event-plasma/) explains how to track the deposit events.
```

2022-11-11 12:23 UTC, ashucoder9 commented on docs/develop/plasma-using-metamask.md
>  MATIC is native token on Polygon. So we support transfer of Matic tokens without any token address.
```suggestion
MATIC is the native token of the Polygon network. So we support the transfer of MATIC tokens without any token address.
```

2022-11-11 12:24 UTC, ashucoder9 commented on docs/develop/pos-using-metamask.md
> +For the mainnet, Ethereum is the root chain and Polygon Mainnet is the child chain and for the testnet, Goerli is the root chain and Mumbai is the child chain. The values in config.json file should b
```suggestion
For the mainnet, Ethereum is the root chain and Polygon Mainnet is the child chain and for the testnet, Goerli is the root chain and Mumbai is the child chain. The values in the `config.json` file should be set accordingly. Goerli and Mumbai networks are used as the root and child chain in this tutorial.
```

2022-11-11 12:24 UTC, ashucoder9 commented on docs/develop/pos-using-metamask.md
> +posClientParent() and posClientChild are used to initialize the root and child chain matic.js object for PoS bridge. Code snippets mentioned below, under each step, can be found in the [tutorial](htt
```suggestion
`posClientParent()` and `posClientChild` are used to initialize the root and child chain matic.js object for the PoS bridge. Code snippets mentioned below, under each step, can be found in the [tutorial](https://github.com/maticnetwork/pos-plasma-tutorial) repo as well.
```

2022-11-11 12:25 UTC, ashucoder9 commented on docs/develop/pos-using-metamask.md
> +The **withdrawStart()** method can be used to initiate the withdraw process which will burn the specified amount on Polygon chain.
```suggestion
The `withdrawStart()` method can be used to initiate the withdrawal process which will burn the specified amount on the Polygon chain.
```

2022-11-11 12:25 UTC, ashucoder9 commented on docs/develop/pos-using-metamask.md
> +The **_withdrawExit_** function in PoS bridge involves block proof generation by querying the child chain multiple times and hence it may take 4-5 seconds for Metamask to pop up as it consumes time t
```suggestion
The `withdrawExit()` function in the PoS bridge involves block proof generation by querying the child chain multiple times and hence it may take 4-5 seconds for Metamask to pop up as it consumes time to build the transaction object.
```

2022-11-11 12:26 UTC, ashucoder9 commented on docs/develop/pos-using-metamask.md
> +You can also use the **_withdrawExitFaster_** method to exit the withdraw process faster. For more details please visit this [guide](https://maticnetwork.github.io/matic.js/docs/pos/erc20/withdraw-ex
```suggestion
You can also use the `withdrawExitFaster()` method to exit the withdrawal process faster. For more details please visit this [guide](https://maticnetwork.github.io/matic.js/docs/pos/erc20/withdraw-exit-faster/).
```

2022-11-11 12:28 UTC, ashucoder9 requested changes
Hey @cerberushades, thanks for the audit. Just added suggestions to make the Bridge section more consistent with Wiki content.

2022-11-15 14:21 UTC, cerberushades commented
> Hey @cerberushades, thanks for the audit. Just added suggestions to make the Bridge section more consistent with Wiki content.

thx for the suggestions. I applied all of them and they'll surely improve consistency throughout our wiki. Can you give it a second look now?

2022-11-15 14:58 UTC, merged