Added a testnet and mainnet deployment stage
maticnetwork/matic-docs pull request #1237
Opened 2022-12-02 05:15 UTC by shelleyolivia

Added in a deployment section that distinguished between Mumbai testnet and Polygon mainnet. I work at Alchemy and based on our own developers' questions and ask for tutorials, thought the rewritten section would be much more clear to follow for developers in terms of connecting your Metamask wallet and deploying on testnet and mainnet. Lmk of any questions, thanks!

2022-12-05 04:49 UTC, shelleyolivia commented
@DannyS03 thanks for reviewing. Anything else you need from me here? Cheers,

2022-12-05 07:47 UTC, ashucoder9 commented on docs/develop/remix.md
> +To deploy to the Mumbai testnet, we have to connect to the Web3 world which can be accomplished by using any of the services like Metamask, Brave, Portis etc. We will be using Metamask in this tutori
```suggestion
To deploy to the Mumbai testnet, we have to connect to the Web3 world which can be accomplished by using any of the services like Metamask, Brave, Portis, etc. We will be using Metamask in this tutorial. Please follow this [guide to set up a Metamask Account](/docs/develop/metamask/hello).
```

2022-12-05 07:49 UTC, ashucoder9 commented on docs/develop/remix.md
> +- Open Metamask. Click on the network dropdown menu (set to **Ethereum Mainnet** by default) and click on **Add Network** button. MaticVigil provides a public endpoint and is rate-limited. Therefore,
```suggestion
- Open Metamask. Click on the network dropdown menu (set to **Ethereum Mainnet** by default) and click on the **Add Network** button. MaticVigil provides a public endpoint and is rate-limited. Therefore, most developers use a free blockchain provider like [Alchemy](https://docs.alchemy.com/docs/how-to-add-polygon-to-metamask) or [Quicknode](https://quicknode.com) to have a dedicated RPC endpoint with faster throughput AKA **computing units per second (CUPs)**. You need to create a free account to get your private API key from one of these providers to put into the dedicated RPC endpoint URL below. 
```

2022-12-05 07:54 UTC, ashucoder9 commented on docs/develop/remix.md
> +- Head over to [Faucet](https://faucet.polygon.technology/) and request test MATIC - you will need this pay for gas on Polygon network. Select **Mumbai** as the network and **MATIC Token** as the tok
```suggestion
- Head over to [Faucet](https://faucet.polygon.technology/) and request test MATIC - you will need this to pay for gas on the Polygon network. Select **Mumbai** as the network and **MATIC Token** as the token in the faucet. You can also use this free [Mumbai faucet](https://mumbaifaucet.com)
```

2022-12-05 07:55 UTC, ashucoder9 commented on docs/develop/remix.md
> +After you can deploy on the Mumbai testnet withnot any errors (i.e., the purpose of the testnet), let's deploy the Smart Contract on Polygon mainnet. Remember this will cost real $ in the form of MAT
```suggestion
After you can deploy on the Mumbai testnet without any errors (i.e., the purpose of the testnet), let's deploy the Smart Contract on the Polygon Mainnet. Remember this will cost real $ in the form of MATIC tokens.
```

2022-12-05 07:56 UTC, ashucoder9 commented on docs/develop/remix.md
> +Now, we have to deploy our smart contract on Mumbai, Polygon Network's testnet. Not only does it cost money (e.g., gas fees) to deploy a smart contract on Polygon mainnet, but also, the contract is i
```suggestion
Now, we have to deploy our smart contract on Mumbai, Polygon Network's Testnet. Not only does it cost money (e.g., gas fees) to deploy a smart contract on Polygon Mainnet, but also, the contract is immutable and can't be changed once deployed. Therefore, it's best to first deploy your smart contract to the Testnet first. 
```

2022-12-05 07:58 UTC, ashucoder9 commented on docs/develop/remix.md
> +Similar to the steps above when you deployed to Mumbai, you open your Metamask wallet. Click on the network dropdown menu (set to **Ethereum Mainnet** by default) and click on **Add Network** button.
```suggestion
Similar to the steps above when you deployed to Mumbai, you open your Metamask wallet. Click on the network dropdown menu (set to **Ethereum Mainnet** by default) and click on the **Add Network** button. Make sure to have your [Alchemy API key](https://docs.alchemy.com/docs/alchemy-quickstart-guide).
```

2022-12-05 07:58 UTC, shelleyolivia commented
Committed the changes, appreciate you going through things thoroughly @ashucoder9. Let me know if there is anything else, thanks

2022-12-05 07:58 UTC, ashucoder9 commented on docs/develop/remix.md
> +- Make sure your Metamask wallet has Matic tokens to pay the deployment / gas fees
```suggestion
- Make sure your Metamask wallet has MATIC tokens to pay the deployment / gas fees
```

2022-12-05 07:59 UTC, ashucoder9 commented on docs/develop/remix.md
> +In both testnet and mainnet, you do the below to deploy your smart contract using Remix. The below step will use the connect Metamask API keys you set up in the previous steps.
```suggestion
In both Testnet and Mainnet, you do the below to deploy your smart contract using Remix. The below step will use the connect Metamask API keys you set up in the previous steps. 
```

2022-12-05 08:01 UTC, ashucoder9 requested changes
Hey @shelleyolivia thanks for the contribution! Please add these changes.

2022-12-05 09:59 UTC, shelleyolivia commented
thanks @ashucoder9, all commits have been accepted and submitted. Appreciate you, let me know if there's anything else :)

2022-12-05 11:07 UTC, ashucoder9 approved these changes
Thank you @shelleyolivia !

2022-12-05 11:07 UTC, merged

2022-12-06 07:29 UTC, ashucoder9 commented
Yeah, there were some build issues due to a bug in deployment. I can see it's working fine now with your updates!