Update overview.md
maticnetwork/matic-docs pull request #1255
Opened 2022-12-09 19:38 UTC by Hitisha-G

Extended description / introduction of GRPC to be understandable to beginners, exempting the need to go through other sources for basic information.

2022-12-11 20:04 UTC, DannyS03 requested changes
thanks @Hitisha-G

2022-12-11 20:04 UTC, DannyS03 commented on docs/edge/architecture/overview.md
>  ## GRPC
```suggestion
## gRPC
```

2022-12-11 20:04 UTC, DannyS03 commented on docs/edge/architecture/overview.md
> +GRPC or Google Remote Procedure Call is a robust open-source RPC framework used to build scalable and fast APIs.It was initially created by Google.
```suggestion
gRPC, or Google Remote Procedure Call, is a robust open-source RPC framework that Google initially created to build scalable and fast APIs.
```

2022-12-11 20:04 UTC, DannyS03 commented on docs/edge/architecture/overview.md
> +The GRPC layer is vital for operator interactions. Through it, node operators can easily interact with the client, providing an enjoyable UX.
```suggestion
The gRPC layer is vital for operator interactions. Through it, node operators can easily interact with the client, providing an enjoyable UX.
```

2022-12-22 08:35 UTC, ashucoder9 approved these changes

2022-12-22 12:13 UTC, DannyS03 approved these changes

2022-12-25 01:18 UTC, merged