Add md-file of Intro-to-zkEVM-Wiki
maticnetwork/matic-docs pull request #1269
Opened 2022-12-16 18:18 UTC by EmpieichO

Adding an md-file to Introduction to the Polygon zkEVM Wiki, plus modification to sidebar.js

2022-12-16 23:35 UTC, DannyS03 requested changes
thank you @EmpieichO, can we also please remove the extra whitespaces on the page, and format the metadata so that "id" starts at line 2.

2022-12-16 23:35 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +# Polygon zkEVM Documentation
I'd reconsider the header namings on the page:
- "Polygon zkEVM Documentation" is implied by the content already. A simple "Introduction to zkEVM" or "Overview" would work better.

2022-12-16 23:35 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +This documentation presents
```suggestion
> Polygon Hermez, the predecessor of zkEVM,  was launched in March 2021. Its goal was to scale payments
> and transfers of ERC-20 tokens. It currently achieves up to 2000 transactions per second (TPS). See
> [Ethereum Live TPS](https://ethtps.info/Network/Ethereum) to track Ethereum's TPS.

The zkEVM carries out state changes, which come from executions of Ethereum's Layer 2 transactions that
users send to the network and subsequently produces validity proofs attesting to the correctness of the
state change computations carried out off-chain.

> Although taking on this revolutionary design approach was hard, the objective is to minimize the users and
> dApps friction when using the solution, which requires the recreation of all EVM opcodes for the transparent deployment of existing Ethereum smart contracts. As a result, the team has created and engineered a new set of technologies and tools.

This documentation presents: 
```

2022-12-16 23:35 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +- What Polygon zkEVM is
Would suggest reorganizing the list to showcase a better flow, that is, starting with "What is" -> "How tos" -> "Participate/Get Involved"
```
- What Polygon zkEVM is
- The architecture of Polygon zkEVM (I wouldn't limit this to an overview as there is solid material at describing the various features and components:) )
- zkEVM's design approach to state machines
- How to run a local zkNode
- How to participate in the zkEVM testnet, and ultimately build on the mainnet

2022-12-16 23:35 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +The document then cascades step-by-step into the finer details of zkEVM's sub-components, such as the zero-knowledge Prover (zkProver), the state machines used in the zkProver, the Layer X to Layer Y
```suggestion
The documentation cascades into the finer details of zkEVM's sub-components, including the zero-knowledge Prover (zkProver), the state machines used in the zkProver, the Layer X <> Layer Y bridge smart contract, and the special toolings that enable the zkEVM to achieve its objectives. 
```

2022-12-16 23:35 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +We however emphasise that this documentation is still **Work In Progress** (WIP). Some aspects have been covered in more detail, while others still need further expansion. Also, sections of this docu
I'd put this as an alert at the top

```
:::caution Documentation status
This documentation is still **Work In Progress** (WIP). Some aspects have been covered in more detail, while others still need further expansion. Also, sections of this documentation might later be reorganized in order to achieve a better flow.
:::
```

2022-12-16 23:35 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +Polygon zkEVM is a powerful, decentralized technology developed to provide Layer 2 scalability solutions to Ethereum blockchain users. It is therefore designed to seamlessly integrate with the Ethere
The content under "About Polygon zkEVM" and "What is Polygon zkEVM" are redundant and can be compiled into one section,

2022-12-16 23:35 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +Polygon zkEVM is a decentralized Ethereum Layer 2 scalability solution based on cryptographic proofs to provide validation and fast finality to transactions.
```suggestion
Polygon zkEVM is a decentralized Ethereum Layer 2 scalability solution based on cryptographic proofs to provide validation and fast finality to transactions. By providing zero-knowledge rollups (zk-rollups) that sit on top Ethereum, the scalability and the transactions per second (TPS) can be dramatically improved.
```

2022-12-16 23:35 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +Polygon zkEVM is a powerful, decentralized technology developed to provide Layer 2 scalability solutions to Ethereum blockchain users. It is therefore designed to seamlessly integrate with the Ethere
```suggestion
```

2022-12-16 23:35 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +
```suggestion
zkEVM utilizes cryptographic zero-knowledge technology to provide validation and fast finality of off-chain transactions. It has been designed to emulate the Ethereum Virtual Machine (EVM) by recreating all existing EVM opcodes.

```

2022-12-16 23:35 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +In order to prove that the off-chain computations are correct, Polygon zkEVM employs easily verifiable zero-knowledge proofs. The Layer 2 zero-knowledge proofs are based on the complex polynomial com
```suggestion
```

2022-12-16 23:35 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +Polygon zkEVM, henceforth zkEVM, is a decentralized Ethereum Layer 2 scalability solution utilising cryptographic zero-knowledge technology in order to provide validation and fast finality of off-cha
```suggestion
```

2022-12-16 23:35 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +## What is Polygon zkEVM?
```suggestion
```

2022-12-16 23:35 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +## About Polygon zkEVM
```suggestion
```

2022-12-16 23:35 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +- What Polygon zkEVM is
I'd also link to a "general page" for each of these points to establish the list as an index and a way users can get started.

2022-12-19 07:19 UTC, EmpieichO commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +This documentation presents
Suggested change not clear

2022-12-19 07:34 UTC, EmpieichO commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +# Polygon zkEVM Documentation
Consider SEO, users are most likely to search for "Polygon zkEVM Documentation" and the Wiki will ultimately be the only place for documentation.

2022-12-19 07:39 UTC, EmpieichO commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +The document then cascades step-by-step into the finer details of zkEVM's sub-components, such as the zero-knowledge Prover (zkProver), the state machines used in the zkProver, the Layer X to Layer Y
Done.

2022-12-19 07:45 UTC, EmpieichO commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +We however emphasise that this documentation is still **Work In Progress** (WIP). Some aspects have been covered in more detail, while others still need further expansion. Also, sections of this docu
Done.

2022-12-19 08:20 UTC, EmpieichO commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +Polygon zkEVM is a powerful, decentralized technology developed to provide Layer 2 scalability solutions to Ethereum blockchain users. It is therefore designed to seamlessly integrate with the Ethere
Done. One section now.

2022-12-19 08:27 UTC, EmpieichO commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +Polygon zkEVM is a powerful, decentralized technology developed to provide Layer 2 scalability solutions to Ethereum blockchain users. It is therefore designed to seamlessly integrate with the Ethere
I can't spot the difference here.

2022-12-19 08:44 UTC, ashucoder9 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +# Polygon zkEVM Documentation
Hey @EmpieichO, as per SEO requirements we already have the title element as "Polygon zkEVM Documentation". If you search even now, you will find that Polygon Wiki's Architecture of zkEVM appears second on Google, which was originally crawled as the main page for zkEVM docs on Polygon Wiki. Later, we changed that to "Build on zkEVM".

As we plan to deprecate the original Hermez docs website, search results will point directly to Polygon Wiki's zkEVM article. As per Danny's suggestion, the title "Introduction to zkEVM" fits better.

2022-12-19 08:45 UTC, ashucoder9 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +
```suggestion
```

2022-12-19 08:46 UTC, ashucoder9 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +
```suggestion
```

2022-12-19 08:46 UTC, ashucoder9 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +
```suggestion
```

2022-12-19 08:46 UTC, ashucoder9 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +
```suggestion
```

2022-12-19 08:51 UTC, ashucoder9 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +
```suggestion
```

2022-12-19 08:52 UTC, ashucoder9 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +
```suggestion
```

2022-12-19 08:56 UTC, EmpieichO commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +
Not sure how to resolve this one. The idea is to start with a more general Ethereum context before coming to the specific way zkEVM provides validation.

2022-12-19 08:58 UTC, ashucoder9 requested changes
Please check the suggestions and commit them into your PR to update this document.

2022-12-19 08:58 UTC, ashucoder9 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +Polygon zkEVM is a powerful, decentralized technology developed to provide Layer 2 scalability solutions to Ethereum blockchain users. It is therefore designed to seamlessly integrate with the Ethere
That's actually a suggestion to delete the mentioned lines. You can simply click on "Commit Suggestion" for suggestions above to commit them into this doc.

2022-12-19 08:58 UTC, ashucoder9 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +The predecessor, Polygon Hermez 1.0, was launched in March 2021. Its goal was to scale payments and transfers of ERC-20 tokens. It currently achieves up to 2000 transactions per second (tps), and thu
```suggestion
The predecessor, Polygon Hermez 1.0, was launched in March 2021. Its goal was to scale payments and transfers of ERC-20 tokens. It currently achieves up to 2000 transactions per second (TPS), and thus accomplished the purpose it was designed for. See [Ethereum Live TPS](https://ethtps.info/Network/Ethereum) to keep track of Ethereum's live transactions per second.
```

2022-12-19 08:58 UTC, ashucoder9 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +The predecessor, Polygon Hermez 1.0, was launched in March 2021. Its goal was to scale payments and transfers of ERC-20 tokens. It currently achieves up to 2000 transactions per second (tps), and thu
This is a bit redundant as the content here already appears in the first paragraph after suggestions are merged.

2022-12-19 08:58 UTC, ashucoder9 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +The zkEVM carries out state changes, which come from executions of Ethereum’s Layer 2 transactions that users send to the network, and subsequently produces validity proofs attesting to the correctne
```suggestion
The zkEVM carries out state changes, which come from executions of Ethereum’s Layer 2 transactions that users send to the network and subsequently produces validity proofs attesting to the correctness of the state change computations carried out off-chain.
```

2022-12-19 08:58 UTC, ashucoder9 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +Although taking on this revolutionary design approach was a hard decision to make, the objective is to minimise the users and dApps friction when using the solution. It is an approach that requires r
```suggestion
Although taking on this revolutionary design approach was a hard decision to make, the objective is to minimize the users and dApps friction when using the solution. It is an approach that requires the recreation of all EVM opcodes for the transparent deployment of existing Ethereum smart contracts. For this purpose, a new set of technologies and tools has been created and engineered by the team.
```

2022-12-19 08:58 UTC, ashucoder9 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +
Please remove these blank lines too @EmpieichO

2022-12-19 09:07 UTC, EmpieichO commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +Polygon zkEVM, henceforth zkEVM, is a decentralized Ethereum Layer 2 scalability solution utilising cryptographic zero-knowledge technology in order to provide validation and fast finality of off-cha
See the new version.

2022-12-19 09:09 UTC, EmpieichO commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +## What is Polygon zkEVM?
I wish to retain this heading, see new version.

2022-12-19 09:13 UTC, EmpieichO commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +- What Polygon zkEVM is
Done.

2022-12-19 09:14 UTC, EmpieichO commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +Polygon zkEVM is a decentralized Ethereum Layer 2 scalability solution based on cryptographic proofs to provide validation and fast finality to transactions.
see new version first

2022-12-19 09:15 UTC, EmpieichO commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +
see new version

2022-12-19 09:23 UTC, EmpieichO commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +
Done

2022-12-19 10:46 UTC, ashucoder9 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +```
Please remove these backticks. They are not appropriate here. We only need ::: for admonitions.

2022-12-19 10:46 UTC, ashucoder9 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +```
Remove this too @EmpieichO ser!

2022-12-19 13:44 UTC, EmpieichO commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +```
removed

2022-12-19 13:44 UTC, EmpieichO commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +```
okay

2022-12-20 00:52 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +Polygon zkEVM is a powerful, decentralized technology developed to provide Layer 2 scalability solutions to Ethereum blockchain users. It is therefore designed to seamlessly integrate with the Ethere
```suggestion
Polygon zkEVM is a powerful, decentralized Layer 2 scalability solution for Ethereum. Given that Ethereum is subject to the DLT (distributed ledger technology) trilemma, it cannot scale beyond its transaction threshold without sacrificing decentralization or security. 

By providing zero-knowledge rollups (ZK rollups) that sit on top of the Ethereum Mainnet, the scalability and the transactions per second (TPS) can be dramatically improved.
```

2022-12-20 00:53 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +Polygon zkEVM, henceforth zkEVM, is a virtual machine, designed and developed to emulate the Ethereum Virtual Machine (EVM) by recreating all existing EVM opcodes for transparent deployment of existi
This should be the first statement in this section, as it introduces zkEVM for what it is, and then the section can go into capabilities.

2022-12-20 00:55 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +As a state machine, zkEVM carries out state changes, which come from executions of Ethereum’s Layer 2 transactions that users send to the network, and subsequently produces validity proofs attesting
This and line 46 can be combined into one.

2022-12-20 00:55 UTC, DannyS03 commented on docs/zkEVM/Intro-Polygon-zkEVM-Docs.md
> +
```suggestion
```

2022-12-20 07:38 UTC, ashucoder9 commented
I'm closing this PR as discussed with @EmpieichO

Will raise another PR for the same article with the required modifications and content guidelines as recommended for Polygon Wiki.

2022-12-20 07:38 UTC, closed without merging