[Polygon ID] Update PID links
maticnetwork/matic-docs pull request #1289
Opened 2022-12-23 17:05 UTC by otto-mora

Update Polygon ID links for tutorials page and discord.

2022-12-26 10:54 UTC, ashucoder9 commented on docs/polygonid/overview.md
> +For the latest technical documentation and tutorials, please head over to our [<ins>Polygon ID tutorials page</ins>](/docs/zkEVM/overview).
Why are we using zkEVM link here?

2022-12-26 10:55 UTC, ashucoder9 commented on docs/polygonid/overview.md
> +Also please refer to our [<ins>twitter page</ins>](https://twitter.com/0xpolygonid) to stay updated with the latest developments on Polygon ID.
```suggestion
Also please refer to our [<ins>Twitter page</ins>](https://twitter.com/0xpolygonid) to stay updated with the latest developments on Polygon ID. 
```

2022-12-26 10:55 UTC, ashucoder9 commented on docs/polygonid/overview.md
> +Also please refer to our [<ins>twitter page</ins>](https://twitter.com/0xpolygonid) to stay updated with the latest developments on Polygon ID.
We can club these two admonitions together.

2022-12-26 10:56 UTC, ashucoder9 requested changes
A few queries and changes.

2022-12-26 22:03 UTC, otto-mora commented on docs/polygonid/overview.md
> +For the latest technical documentation and tutorials, please head over to our [<ins>Polygon ID tutorials page</ins>](/docs/zkEVM/overview).
Good catch. Thanks I corrected to our Github Tutorials for Polygon ID.

2022-12-26 22:06 UTC, otto-mora commented
> A few queries and changes.

Thanks Ash! Corrected one and accepted your suggestion for the other. Suggest we go ahead and merge now.

2022-12-27 04:54 UTC, DannyS03 approved these changes

2022-12-27 04:54 UTC, merged