feat(zkEVM): Add Storage SM documentation
maticnetwork/matic-docs pull request #1293
Opened 2023-01-02 11:04 UTC by ashucoder9

2023-01-04 19:28 UTC, cerberushades requested changes

2023-01-04 19:28 UTC, cerberushades commented on docs/zkEVM/zkProver/storage-sm-design.md
> +   The `Set_UPDATE` zkASM code, first initialises the `LEVEL` register to `(1,0,0,0)`. Then uses the `GetLevelBit()` function to read the two least-significant bits of the leaf level, which happens i
```suggestion
   The `Set_UPDATE` zkASM code, first initialises the `LEVEL` register to `(1,0,0,0)`. Then uses the `GetLevelBit()` function to read the two least-significant bits of the leaf level, which happens in two cases, each with its own two subcases:
```

2023-01-04 19:28 UTC, cerberushades commented on docs/zkEVM/zkProver/storage-sm-design.md
> +Actions such as;
```suggestion
Actions such as:
```

2023-01-04 19:28 UTC, cerberushades commented on docs/zkEVM/zkProver/storage-sm-design.md
> +   It is for the same reason, SIF Assembly utilises special registers; the `SIBLING_VALUE_HASH` and `SIBLING_RKEY`.
```suggestion
   It is for the same reason that SIF Assembly utilizes special registers: the `SIBLING_VALUE_HASH` and `SIBLING_RKEY`. 
```

2023-01-04 19:28 UTC, cerberushades commented on docs/zkEVM/zkProver/storage-sm-design.md
> +Note also that there is only one `Get` Assembly code, for the READ SMT Action, and the rest of the secondary Assembly codes are `Set_` Assembly codes differing according to their respective SMT Actio
```suggestion
Note also that there is only one `Get` Assembly code for the READ SMT Action, and the rest of the secondary Assembly codes are `Set_` Assembly codes differing according to their respective SMT Actions. So `Get` uses `LATCH_GET` at the end of a run, while the `Set_` codes use `LATCH_SET`.
```

2023-01-04 20:59 UTC, ashucoder9 commented on docs/zkEVM/zkProver/simple-smt.md
> +5. One can then compute the root as, $\mathbf{root}_{\mathbf{ab}} = \mathbf{H}(\mathbf{L}_{\mathbf{a}} \| \mathbf{L}_{\mathbf{b}})$.
I guess it will be easier to digest the maths behind this if it's broken into steps.

2023-01-04 21:00 UTC, ashucoder9 commented on docs/zkEVM/zkProver/storage-sm-design.md
> +id: storage-sm-mechanism
Yeah, it basically refers to both design and mechanism but I tried trimming the ID down to only include mechanism.

2023-01-04 21:00 UTC, ashucoder9 commented on docs/zkEVM/zkProver/storage-sm-design.md
> +The **Storage SM** is one of zkProver's secondary state, and thus receives instructions from the Main SM called **Storage Actions**. The Storage Actions basically refers to verification of **CRUD** o
Adding that.

2023-01-04 21:01 UTC, ashucoder9 commented on docs/zkEVM/zkProver/storage-sm-design.md
> +The **Storage SM** is one of zkProver's secondary state, and thus receives instructions from the Main SM called **Storage Actions**. The Storage Actions basically refers to verification of **CRUD** o
```suggestion
The **Storage SM** is one of zkProver's secondary state machines, and thus receives instructions from the Main SM called **Storage Actions**. The Storage Actions basically refer to the verification of **CRUD** operations executed by the Main SM.
```

2023-01-04 21:02 UTC, ashucoder9 commented on docs/zkEVM/zkProver/storage-sm-design.md
> +That's all the primary Storage Assembly code does, the details of how each if the SMT Actions are stipulated in the individual secondary Assembly codes.
```suggestion
That's all the primary Storage Assembly code does and the details of how each of the SMT Actions is stipulated in the individual secondary Assembly codes.
```

2023-01-05 14:45 UTC, cerberushades approved these changes

2023-01-06 10:12 UTC, DannyS03 approved these changes
thanks @ashucoder9! Similarly, we should audit and generate consistency across the documents after migration.

2023-01-06 20:59 UTC, merged

2023-01-09 10:17 UTC, ashucoder9 commented
Sure @DannyS03. The migration process is still due but I'll start auditing them while pushing to Wiki.