Adding QuickNode faucet to docs
maticnetwork/matic-docs pull request #1326
Opened 2023-01-20 01:14 UTC by Sahilsen

2023-01-22 10:50 UTC, Ishmaello reviewed
https://ishmaello.solana-mainnet.discover.quiknode.pro/0c3f349f30884a9995f5e56b30eec975433e08fd/

2023-01-25 08:20 UTC, ashucoder9 commented on docs/develop/tools/quicknode-faucet.md
> +If you Tweet with the [drip](https://faucet.quicknode.com/drip) faucet URL along with your address and submit the tweet URL, you get 10X more MATIC.
```suggestion
If you **tweet** the [<ins>drip faucet URL</ins>](https://faucet.quicknode.com/drip) along with your wallet address and submit the tweet URL, you get 10X more MATIC testnet tokens.
```

2023-01-25 08:21 UTC, ashucoder9 commented on docs/develop/tools/quicknode-faucet.md
> +To receive MATIC Mumbai tokens, head to [QuickNode Multi-chain Faucet](https://faucet.quicknode.com/drip). Connect your wallet (MetaMask or Phantom) by clicking on **Connect Wallet**. Then select Pol
```suggestion
To receive MATIC Mumbai tokens, head to [QuickNode Multi-chain Faucet](https://faucet.quicknode.com/drip). Connect your wallet (MetaMask or Phantom) by clicking on **Connect Wallet**. Select Polygon and Mumbai Testnet from the dropdown menus, and then click on **Continue**.
```

2023-01-25 08:23 UTC, ashucoder9 commented on docs/develop/tools/quicknode-faucet.md
> +To receive 0.1 testnet MATIC click on **No thanks, just send me 0.1 MATIC** or to receive 1 MATIC do a tweet with the [drip](https://faucet.quicknode.com/drip) faucet URL along with your address, cop
```suggestion
To receive 0.1 Testnet MATIC, click on **No thanks, just send me 0.1 MATIC**. To receive 1 MATIC, post a tweet with the [drip faucet URL](https://faucet.quicknode.com/drip) along with your wallet address, and copy-paste your tweet URL in the input field and click on **Claim my 1 MATIC**.
```

2023-01-25 08:29 UTC, ashucoder9 requested changes
Hey @Sahilsen, thanks for the contribution. Added a few suggestions.

Also, can you please update the screenshots with more uniform image capturing such that the size and content padding are consistent? If not, we can go with the merge and our team will update them during regular docs audit.

2023-01-27 01:41 UTC, Sahilsen commented
> Hey @Sahilsen, thanks for the contribution. Added a few suggestions.
> 
> Also, can you please update the screenshots with more uniform image capturing such that the size and content padding are consistent? If not, we can go with the merge and our team will update them during regular docs audit.

Hey @ashucoder9 thanks for the review. Changed the images, and now they should be all same size and also changes the copy according to your feedback.

2023-01-27 13:31 UTC, ashucoder9 approved these changes
Thanks @Sahilsen 🙌🏽

2023-01-27 14:34 UTC, Sahilsen commented
> Thanks @Sahilsen 🙌🏽

Are we all good to merge? @ashucoder9

2023-01-27 14:50 UTC, ashucoder9 commented
Yeah, you may merge the PR.

2023-01-27 14:57 UTC, Sahilsen commented
> Yeah, you may merge the PR.

I don't think I can merge, can you please? @ashucoder9

2023-01-27 15:00 UTC, merged

2023-01-28 04:27 UTC, Ishmaello commented
Neither do I be able to merge