feat(zkEVM): adds arithmetic state machine docs
maticnetwork/matic-docs pull request #1353
Opened 2023-02-02 11:15 UTC by ashucoder9

2023-02-02 11:19 UTC, ashucoder9 commented on docs/zkEVM/zkProver/arithmetic-sm.md
> +The Polygon zkEVM Repo is available on [GitHub](https://github.com/0xPolygonHermez).
```suggestion
The Polygon zkEVM repository is available on [GitHub](https://github.com/0xPolygonHermez).
```

2023-02-02 15:57 UTC, cerberushades requested changes

2023-02-02 15:57 UTC, cerberushades commented on docs/zkEVM/zkProver/arithmetic-sm.md
> +Going back to our equations; $\text{EQ}_0, \text{EQ}_1, \text{EQ}_2, \text{EQ}_4$; let's see how the operation is performed in $\text{EQ}_0$.
```suggestion
Going back to our equations $\text{EQ}_0, \text{EQ}_1, \text{EQ}_2, \text{EQ}_4$; let's see how the operation is performed in $\text{EQ}_0$. 
```

2023-02-02 15:57 UTC, cerberushades commented on docs/zkEVM/zkProver/arithmetic-sm.md
> +Now, notice that the $\mathbf{eq}_i$'s do not care about the carry they generate. That means, if $\mathbf{eq}_i = 10$, then what we really want the result to be is $0$ and save $1$ as a carry for the
```suggestion
Now, notice that the carry generated by the $\mathbf{eq}_i$'s is not important for them. That means, if $\mathbf{eq}_i = 10$, then what we really want the result to be is $0$ and save $1$ as a carry for the next operation. To express this fact as a constraint, we say that the following has to be satisfied:
```

2023-02-02 15:58 UTC, cerberushades commented
@ashucoder9 you've added a few images that weren't used in the article. Is this what you planned?

2023-02-02 16:01 UTC, ashucoder9 commented on docs/zkEVM/zkProver/arithmetic-sm.md
> +**These operations are performed in the Arithmetic State Machine, with registers satisfying the following PIL relation**,
Nope, it's part of the explanation so admonition doesn't seem to fit here.

2023-02-02 16:04 UTC, ashucoder9 commented on docs/zkEVM/zkProver/arithmetic-sm.md
> +Since at most, one of $\text{EQ}_1$ and $\text{EQ}_2$ are activated in any scenario, we can afford "sharing'' the same $q_0$ for both.
Looks good to me 👀 But please commit if you have some suggestion.

2023-02-02 16:05 UTC, ashucoder9 commented
> @ashucoder9 you've added a few images that weren't used in the article. Is this what you planned?

Yes, that's intentional for upcoming articles.

2023-02-03 12:51 UTC, cerberushades approved these changes

2023-02-03 15:22 UTC, merged