Updates Validator Setup
maticnetwork/matic-docs pull request #1379
Opened 2023-02-14 20:06 UTC by cerberushades

- Adds bloXroute instructions
- Corrects checksums 
- Adds notes on 0.5 ETH minimum
- Makes some reordering and overall improvement on Validator articles

2023-02-15 11:46 UTC, ashucoder9 commented on docs/maintain/validate/bloxroute.md
> +title: BloXroute instructions
```suggestion
title: BloXroute Instructions
```

2023-02-15 11:46 UTC, ashucoder9 commented on docs/maintain/validate/bloxroute.md
> +sidebar: BloXroute instructions
```suggestion
sidebar: BloXroute Instructions
```

2023-02-15 11:47 UTC, ashucoder9 commented on docs/maintain/validate/bloxroute.md
> +description: Connect your nodes to BloXroute’s gateways.
```suggestion
description: Connect your Polygon network nodes to BloXroute gateways using BDN.
```

2023-02-15 11:51 UTC, ashucoder9 commented on docs/maintain/validate/bloxroute.md
> +As validators, we need to keep track of block propagation time, given that we offer a 2 sec block time. We are happy to announce that we are working with [bloXroute](https://bloxroute.com/), whose in
```suggestion
As validators, we need to keep track of block propagation time, given that we offer a 2 sec block time. We are working with [bloXroute](https://bloxroute.com/) to leverage their infrastructure ([the BDN](https://docs.bloxroute.com/bdn-architecture)), that would help lower the block propagation time. For this, we would need your support in connecting your Polygon network nodes to bloXroute’s gateways.
```

2023-02-15 11:51 UTC, ashucoder9 commented on docs/maintain/validate/bloxroute.md
> +To get your bloXroute endpoints please ping the validator support team on Discord.
```suggestion
To get your bloXroute endpoints, please ping the **Validator Support team** on Discord.
```

2023-02-15 11:52 UTC, ashucoder9 commented on docs/maintain/validate/bloxroute.md
> +## Steps to connect to the Blockchain Distribution Network (BDN), provided by bloXroute
```suggestion
## Connecting to the BDN
```

2023-02-15 11:56 UTC, ashucoder9 commented on docs/maintain/validate/bloxroute.md
> +**Step 1**: Create an account at bloXroute user portal and subscribe to the Introductory Plan (free of charge).
```suggestion
**Step 1**: Create an account at the **bloXroute user portal** and subscribe to the Introductory Plan (free of charge).
```

2023-02-15 11:56 UTC, ashucoder9 commented on docs/maintain/validate/bloxroute.md
> +**Step 2**: Contact the Validator Support Team for the Bloxroute endpoint.
```suggestion
**Step 2**: Contact the Validator Support Team for the bloXroute endpoint.
```

2023-02-15 11:57 UTC, ashucoder9 commented on docs/maintain/validate/bloxroute.md
> +Add the following content to /var/lib/bor/config.toml:
```suggestion
Add the following content to `/var/lib/bor/config.toml`:
```

2023-02-15 11:57 UTC, ashucoder9 commented on docs/maintain/validate/bloxroute.md
> +Now restart bor:
```suggestion
Now restart Bor: 
```

2023-02-15 11:58 UTC, ashucoder9 commented on docs/maintain/validate/bloxroute.md
> +**Step 4**: Inform the Polygon team on the Discord channel ``#mainnet-validator-queries`` once you are done adding the trusted peer. bloXroute will activate the hosted gateway and confirm the success
```suggestion
**Step 4**: Inform the Polygon team on the Discord channel **#mainnet-validator-queries** once you are done adding the trusted peer. bloXroute will activate the hosted gateway and confirm the success of the connection within the next 24 hours.
```

2023-02-15 11:58 UTC, ashucoder9 commented on docs/maintain/validate/run-validator-ansible.md
> +Please follow the steps on [<ins>bloXroute instructions</ins>](maintain/validate/bloxroute.md) to connect your nodes to the bloXroute gateways.
```suggestion
Please follow the steps on [<ins>bloXroute instructions</ins>](/maintain/validate/bloxroute.md) to connect your nodes to the bloXroute gateways.
```

2023-02-15 11:59 UTC, ashucoder9 commented on docs/maintain/validate/run-validator-ansible.md
> +Please follow the steps on [<ins>bloXroute instructions</ins>](maintain/validate/bloxroute.md) to connect your nodes to the bloXroute gateways.
@cerberushades / is mandatory otherwise links will break.

2023-02-15 12:00 UTC, ashucoder9 commented on docs/maintain/validate/run-validator-binaries.md
> +Please follow the steps on [<ins>bloXroute instructions</ins>](maintain/validate/bloxroute.md) to connect your nodes to the bloXroute gateways.
```suggestion
Please follow the steps on [<ins>bloXroute instructions</ins>](/maintain/validate/bloxroute.md) to connect your nodes to the bloXroute gateways.
```

2023-02-15 12:01 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +Please follow the steps on [<ins>bloXroute instructions</ins>](maintain/validate/bloxroute.md) to connect your nodes to the bloXroute gateways.
```suggestion
Please follow the steps on [<ins>bloXroute instructions</ins>](/maintain/validate/bloxroute.md) to connect your nodes to the bloXroute gateways.
```

2023-02-15 12:03 UTC, ashucoder9 requested changes
A few suggestions and link corrections.

2023-02-15 13:24 UTC, cerberushades commented
> A few suggestions and link corrections.

thx, man. All applied.

2023-02-20 10:52 UTC, ashucoder9 approved these changes

2023-02-20 10:52 UTC, ashucoder9 commented
Thanks @cerberushades 🫡

2023-02-20 10:52 UTC, merged