Add GetBlock Tutorial to the documentation section
maticnetwork/matic-docs pull request #1385
Opened 2023-02-17 13:53 UTC by JoGetBlock

Here's a tutorial on how to create a smart contract on Polygon using GetBlock (an RPC provider supporting Polygon Blockchain)

2023-02-23 09:53 UTC, ashucoder9 commented
Hey @JoGetBlock, this PR has some errors that need fixing before we proceed with a review. I am listing them down:
1. Incorrect JSX tags causing build failures, probably missing files too
2. Update sidebars.js file to get your document shown on the Wiki

I recommend installing the setup on your local machine and checking if everything works fine. Otherwise, let us know in the comment, and we'll help fix the issues and publish this document.

2023-02-23 09:56 UTC, ashucoder9 requested changes
Please try to include the image files instead of referencing their cloud links. Also, add the file to sidebars.js for display.

2023-03-02 17:38 UTC, cerberushades commented
@JoGetBlock Hey, are you still interested in adding your tutorials to our wiki?

2023-03-03 12:11 UTC, JoGetBlock commented
> @JoGetBlock Hey, are you still interested in adding your tutorials to our wiki?

Sorry, I've been away, yes, we're still interested
Let me fix everything with the tech team, thank you

2023-03-03 12:44 UTC, JoGetBlock reviewed
Please review the changes

2023-03-07 12:39 UTC, ashucoder9 commented
Hey @Ishmaello @JoGetBlock, I've fixed the issues and content to a good extent. But still, need your input on the below points:

- GetBlock is mainly an RPC provider which can be added to Metamask before deploying contracts. Is it necessary to deploy a sample contract? Or can we replace that with a single paragraph outlining that you may go to Remix now and deploy your contract? In my opinion, we don't need another section for that.
- The image quality is poor, would be great if you can update that.

2023-03-11 11:10 UTC, Ishmaello commented on docs/develop/getblock.md
> -  ![img](https://i.ibb.co/FHQvbb0/unnamed-3.png)
I appreciate for all your good work I'm becoming better understanding I even con

2023-03-13 14:02 UTC, JoGetBlock commented
> Hey @Ishmaello @JoGetBlock, I've fixed the issues and content to a good extent. But still, need your input on the below points:
> 
> * GetBlock is mainly an RPC provider which can be added to Metamask before deploying contracts. Is it necessary to deploy a sample contract? Or can we replace that with a single paragraph outlining that you may go to Remix now and deploy your contract? In my opinion, we don't need another section for that.
> * The image quality is poor, would be great if you can update that.

@ashucoder9 please, take a look at the changes

2023-03-13 16:17 UTC, JoGetBlock reviewed
Please review the latest changes

2023-03-15 10:20 UTC, JoGetBlock reviewed
@DannyS03 also let me know if there are any other editions here, thank you Danny!

2023-03-20 15:36 UTC, JoGetBlock commented
> Hey @JoGetBlock sorry for being so strict here, but we're striving to make the best experience for our docs users. So, to improve the article visuals, I'd centralize the screenshots and try to follow some common ground for their size as well. I'd also avoid 1 image coming after another one without any text in between. Finally, I'd suggest that you take a look at the other tutorials in the same section.

It's fine, thank you for helping, it's just that I've never done these before, that's why I simply followed the requirements sent from the Polygon team, will make the editions and come back.

2023-04-04 17:15 UTC, DannyS03 commented on docs/develop/getblock.md
> +1. The first step is to [sign up with Getblock](https://account.getblock.io/sign-in) via wallet or email
```suggestion
1. Sign up with Getblock by visiting the [official website](https://account.getblock.io/sign-in) and creating an account using your wallet or email.
```

2023-04-04 17:17 UTC, DannyS03 commented on docs/develop/getblock.md
> +2. Create an endpoint for Mumbai Testnet
I'd create a list that includes step-by-step instructions, such as:

```
Create an endpoint for the Mumbai Testnet on Getblock by following these steps:

- Go to the Getblock website and log in to your account.
- Click on "API Keys" in the left-hand menu.
- Click on "Create API Key" and select "Ethereum" as the blockchain.
- Choose "Mumbai Testnet" as the network and give your endpoint a name.
- Click "Create."
- Once your endpoint is created, copy the RPC URL.
```

2023-04-04 17:18 UTC, DannyS03 commented on docs/develop/getblock.md
> +  Then enter Metamask and choose to connect a network manually, connect your Metamask to the Mumbai Testnet adding your GetBlock endpoint in the **RPC URL** line
Same idea here, such as:

```
Connect Metamask to the Mumbai Testnet by following these steps:

- Open Metamask and click on the network dropdown.
- Click on "Custom RPC" at the bottom of the list.
- In the "RPC URL" field, paste the URL of your Getblock endpoint.
- Click "Save."

```

2023-04-04 17:19 UTC, DannyS03 commented on docs/develop/getblock.md
> +If you have zero balance in your account, you can request tokens from the [Mumbai faucet](/develop/tools/matic-faucet.md).
```suggestion
If you don't have any tokens in your account, you can request some from the Mumbai faucet through the [faucet website](https://chat.openai.com/develop/tools/matic-faucet.md).
```

2023-04-04 17:19 UTC, DannyS03 commented on docs/develop/getblock.md
> +Go to the [official Remix](https://remix.ethereum.org/) website. Remix is a Web-based IDE for Ethereum smart contract development in Solidity.
```suggestion
1. Go to the [official Remix](https://remix.ethereum.org/) website, which is a Web-based IDE for Ethereum smart contract development in Solidity.
```

2023-04-04 17:20 UTC, DannyS03 commented on docs/develop/getblock.md
> +1. Let's take `Storage.sol` from Remix as our example of a smart contract.
```suggestion
2. Open the "Storage.sol" file in Remix, which we will use as an example for our smart contract.
```

2023-04-04 17:20 UTC, DannyS03 commented on docs/develop/getblock.md
> +2. Deploy the smart contract.
```suggestion
3. Deploy the smart contract by clicking on the "Deploy & run transactions" icon in the left-hand menu.
```

2023-04-04 17:20 UTC, DannyS03 commented on docs/develop/getblock.md
> +3. Choose the Injected provider as **Metamask**.
```suggestion
4. Choose "Injected provider" as the provider and select "Metamask" as the wallet.
```

2023-04-04 17:20 UTC, DannyS03 commented on docs/develop/getblock.md
> +  Check that our smart contract has been created on the network.
```suggestion
5. Check that your smart contract has been created on the network by looking at the Remix output panel.
```

2023-04-04 17:21 UTC, DannyS03 commented on docs/develop/getblock.md
> +All done! Congratulations on deploying your smart contract.
```suggestion
Congratulations, you have successfully deployed a smart contract on the Mumbai Testnet! 
```

2023-04-04 17:23 UTC, DannyS03 commented on docs/develop/getblock.md
> +
Would also suggest transforming this section into more explicit steps, starting with something along the lines of:

```
1. Open the smart contract in Remix and locate the storage variable you want to test. In this example, we will use a variable called "storage" that initially has a value of 12."
```

Striving to create clear + direct and actionable steps.

```
2. Change the value of the variable to 14 by entering "14" in the "Store" field and saving the value on the network after confirming the operation in Metamask.
```

And so on.

2023-04-07 15:32 UTC, JoGetBlock reviewed
The required changes added, please check now.

2023-04-09 22:54 UTC, DannyS03 commented
Thank you, @JoGetBlock, for incorporating the changes. Could you please confirm if you have resolved all the suggestions, and if not, could you kindly point out which ones still need to be addressed?

2023-04-10 08:48 UTC, JoGetBlock commented
> 

Hi Danny, I've tried to accept and add all the changes you've asked for (the text corrections, more explicit explanations, the image formats), so I'd confirm that

2023-04-14 07:58 UTC, DannyS03 commented on docs/develop/getblock.md
> +- Open the smart contract in Remix and locate the storage variable you want to test. In this example, we will use a variable called "storage" that initially has a value of 12.
```suggestion
1. Open the smart contract in Remix and locate the storage variable you want to test. In this example, we will use a variable called "storage" that initially has a value of 12."
```

2023-04-14 07:58 UTC, DannyS03 commented on docs/develop/getblock.md
> +- Find the "Store" field and enter the number "14". This will change the value of the "storage" variable from 12 to 14.
```suggestion
2. Change the value of the variable to 14 by entering "14" in the "Store" field and saving the value on the network after confirming the operation in Metamask.
```

2023-04-14 07:58 UTC, DannyS03 commented on docs/develop/getblock.md
> +- Click on the "Transact" button to confirm the transaction in Metamask.
```suggestion
3. Click on the "Transact" button to confirm the transaction in Metamask.
```

2023-04-14 07:58 UTC, DannyS03 commented on docs/develop/getblock.md
> +- Wait for the transaction to be added to the network block. Once the transaction is confirmed, go to the "Read Contract" section under "Deployed Contracts".
```suggestion
4. Wait for the transaction to be added to a network block. Once the transaction is confirmed, navigate to the "Read Contract" section under "Deployed Contracts".
```

2023-04-14 07:58 UTC, DannyS03 commented on docs/develop/getblock.md
> +- Find the "storage" variable and click on the "Read" button. The new value of the variable should now be displayed as 14.
```suggestion
4. Find the "storage" variable and click on the "Read" button. The new value of the variable should now be displayed as "14".
```

2023-04-14 08:03 UTC, DannyS03 commented on docs/develop/getblock.md
> +- Go to the [official Remix](https://remix.ethereum.org/) website. Remix is a Web-based IDE for Ethereum smart contract development in Solidity.
```suggestion
1. Visit the [official Remix website](https://remix.ethereum.org/). Remix is a Web-based IDE for Ethereum smart contract development in Solidity. 
```

2023-04-14 08:03 UTC, DannyS03 commented on docs/develop/getblock.md
> +- Click on the "Create a new file" button located on the left side of the page.
```suggestion
2. Click on the "Create a new file" button located on the left side of the page.
```

2023-04-14 08:03 UTC, DannyS03 commented on docs/develop/getblock.md
> +- Select “Storage.sol” from Remix as an example of a contract.
```suggestion
3. Select “Storage.sol” from Remix as an example of a contract.
```

2023-04-14 08:03 UTC, DannyS03 commented on docs/develop/getblock.md
> +- Proceed by deploying the smart contract by clicking on the “Deploy & Run Transactions” tab.
```suggestion
4. Deploy the smart contract by clicking on the “Deploy & Run Transactions” tab.
```

2023-04-14 08:03 UTC, DannyS03 commented on docs/develop/getblock.md
> +- In Remix, click on the “Deploy & Run Transactions” tab located on the left-hand side of the screen.
```suggestion
5. Click on the “Deploy & Run Transactions” tab in Remix, located on the left-hand side of the screen. 
```

2023-04-14 08:03 UTC, DannyS03 commented on docs/develop/getblock.md
> +- In the “Contract” dropdown menu, select the name of the smart contract you want to deploy and click on the “Deploy” button to deploy the smart contract.
```suggestion
6. In the “Contract” dropdown menu, select the name of the smart contract you want to deploy and click on the “Deploy” button to deploy the smart contract.
```

2023-04-14 08:03 UTC, DannyS03 commented on docs/develop/getblock.md
> +- You can track the status of the transaction in the Metamask window or by checking the transaction hash on the Polygon explorer.
```suggestion
> You can track the status of the transaction in the Metamask window or by checking the transaction hash on the Polygon explorer.
```

2023-04-14 08:03 UTC, DannyS03 commented on docs/develop/getblock.md
> +- Once the transaction has been confirmed, you should see a green checkmark and a message indicating that the contract has been deployed successfully.
```suggestion
Once the transaction has been confirmed, you should see a green checkmark and a message indicating that the contract has been deployed successfully.
```

2023-04-14 08:03 UTC, DannyS03 commented on docs/develop/getblock.md
> +Locate the storage variable you want to test.
```suggestion
7. Locate the storage variable you want to test.
```

2023-04-14 08:03 UTC, DannyS03 commented on docs/develop/getblock.md
> +- Choose "Injected provider" as the provider and select "Metamask" as the wallet.
```suggestion
8. Choose "Injected provider" as the provider and select "Metamask" as the wallet. 
```

2023-04-14 08:03 UTC, DannyS03 commented on docs/develop/getblock.md
> +- Check that your smart contract has been created on the network by looking at the Remix output panel.
```suggestion
> Check that your smart contract has been created on the network by looking at the Remix output panel.
```

2023-04-14 08:03 UTC, DannyS03 commented on docs/develop/getblock.md
> +- Click on the "Polygon (Matic) Mainnet" dropdown menu located at the top right corner of the page and select "Mumbai Testnet" from the list of available networks. Then enter the address of your smar
```suggestion
9. Click on the "Polygon (Matic) Mainnet" dropdown menu located at the top right corner of the page and select "Mumbai Testnet" from the list of available networks. Then enter the address of your smart contract in the search bar located at the top of the page.
```

2023-04-14 08:03 UTC, DannyS03 commented on docs/develop/getblock.md
> +- Click on the search button or hit enter.
```suggestion
10. Click on the search button or hit enter.
```

2023-04-14 14:45 UTC, merged