feat(zkEVM): add differences between EVM and zKEVM
maticnetwork/matic-docs pull request #1445
Opened 2023-03-07 11:56 UTC by ashucoder9

2023-03-07 12:11 UTC, krlosMata requested changes

2023-03-07 12:11 UTC, krlosMata commented on docs/zkEVM/protocol/evm-differences.md
> +Rest of the precompiled contracts have no effects on the zkEVM state tree.
I would add that calling a precompiled that is not supported is handled as a revert:
- return all gas left to previous context
- `success` is set to 0

```suggestion
Rest of the precompiled contracts have no effects on the zkEVM state tree since it is treated as a `revert` mening that all gas is returned to previous context and `success` flag is set to 0
```

2023-03-07 21:37 UTC, krlosMata approved these changes
:smile_cat:

2023-03-08 03:52 UTC, DannyS03 requested changes
Nice! Some additional considerations (either to add additional content or to make the current content more explicit):

- A brief overview of the runtime differences + traditional deployment vs. zk deployment (or link out to a doc that already exists).
- Gas costs for each opcode and precompiled contract.
- State tree size and how it affects performance.
- Clarifying if interacting with the zkEVM is the same as interacting with the EVM through web3 libraries like ethers.js or web3.js.
- If optimizing smart contracts for the zkEVM is the same as optimizing smart contracts for the EVM.

2023-03-08 07:06 UTC, Akuamia1 approved these changes

2023-03-08 13:25 UTC, cerberushades approved these changes

2023-03-09 10:03 UTC, ashucoder9 commented
Added an admonition box to clarify development-related differences @DannyS03

2023-03-09 11:02 UTC, DannyS03 requested changes

2023-03-09 11:02 UTC, DannyS03 commented on docs/zkEVM/protocol/evm-differences.md
> +- [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718) which defines **Typed Transaction Envelope** is not supported
```suggestion
- [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718) which defines **Typed Transaction Envelope**, is not supported
```

2023-03-09 11:02 UTC, DannyS03 commented on docs/zkEVM/protocol/evm-differences.md
> +> [EIP-2930](https://eips.ethereum.org/EIPS/eip-2930) transaction type, **Optional Access Lists** is not supported
```suggestion
- [EIP-2930](https://eips.ethereum.org/EIPS/eip-2930), which defines the **Optional Access Lists** transaction type, is not supported.
```

2023-03-09 11:02 UTC, DannyS03 commented on docs/zkEVM/protocol/evm-differences.md
> +description: A guide to help developers understand the differences between EVM and Polygon zkEVM.
```suggestion
description: A guide to help developers understand the differences between the EVM and Polygon zkEVM.
```

2023-03-09 18:57 UTC, merged