Create archive-node-nodereal
maticnetwork/matic-docs pull request #1457
Opened 2023-03-14 07:06 UTC by STdevK

NodeReal support Archive Node on Polygon mainnet

2023-04-04 17:47 UTC, DannyS03 requested changes
thank you for the contribution @STdevK. I added some suggestions. In addition:

- Let's number each step and aim to make each step direct and actionable.
- I'd put important provider information about NodeReal at the beginning of the associated section, such as the note on API key pricing.

2023-04-04 17:47 UTC, DannyS03 commented on docs/operate/archive-node-nodereal
> +New to Web3 development? Don't worry, you won't have to spin up your own full node on Polygon – NodeReal has got you covered!
```suggestion
If you're new to Web3 development, [NodeReal](https://nodereal.io/) simplifies the process of setting up a full node on Polygon.
```

2023-04-04 17:47 UTC, DannyS03 commented on docs/operate/archive-node-nodereal
> +Most developers opt for a node provider – a quick and easy third-party service that handles requests and responses – because it's the fastest route to getting started on Polygon. NodeReal can help yo
```suggestion
:::tip Simplify Polygon node usage with NodeReal and its quality assurance capabilities

Many developers prefer to use a node provider when getting started on Polygon, or any chain for that matter, as it offers a quick and easy way to handle requests and responses. NodeReal offers a range of features for developers looking for a node provider on the Polygon network. These features include a Standard Interface that simplifies node usage, as well as reliability and scalability for optimal performance. Additionally, NodeReal offers Archive Data for secure data storage, and an API Marketplace that provides additional resources for developers looking to build on Polygon.

```

2023-04-04 17:47 UTC, DannyS03 commented on docs/operate/archive-node-nodereal
> +NodeReal's Standard Interface, Reliability, Scalability, Archive Data, and [API Marketplace](https://nodereal.io/api-marketplace) make it a good choice for new Polygon network developers looking for
```suggestion
```

2023-04-04 17:47 UTC, DannyS03 commented on docs/operate/archive-node-nodereal
> +:::tip Quality Assurance
```suggestion
```

2023-04-04 17:47 UTC, DannyS03 commented on docs/operate/archive-node-nodereal
> +:::
```suggestion
```

2023-04-04 17:47 UTC, DannyS03 commented on docs/operate/archive-node-nodereal
> +
```suggestion
```

2023-04-04 17:47 UTC, DannyS03 commented on docs/operate/archive-node-nodereal
> +
```suggestion
:::
```

2023-04-04 17:47 UTC, DannyS03 commented on docs/operate/archive-node-nodereal
> +We assumes you have signed up for a [MegaNode account](https://nodereal.io/meganode) and can access the [NodeReal Dashboard](https://dashboard.nodereal.io). “Where to sign up for a MegaNode account?”
```suggestion
If you haven't signed up for a MegaNode account yet, you can find a step-by-step guide to getting started [here](https://docs.nodereal.io/docs/getting-started). Once you have a MegaNode account and access to the NodeReal Dashboard, you're ready to proceed.
```

2023-04-04 17:47 UTC, DannyS03 commented on docs/operate/archive-node-nodereal
> +npm
are these here intentionally? (the npm and yarn keywords above the code block)

2023-04-04 17:47 UTC, DannyS03 commented on docs/operate/archive-node-nodereal
> +
May we please add a "testing" or "troubleshooting" section before completion? If there is a guide that already exists, we can link to it with a statement or two before referencing it to introduce the section.

2023-04-04 17:47 UTC, DannyS03 commented on docs/operate/archive-node-nodereal
> +:::Fun Fact: NodeReal Upgrade from "APP" to "API Key"
this won't work as an admonition unfortunately.

I'd advice using ::tip and something along the lines of

```
:::tip One API key for all chains

[..]

:::

I'd also move this until after the step where a user creates an API key.

2023-04-04 17:47 UTC, DannyS03 commented on docs/operate/archive-node-nodereal
> +Before you start sending RPC requests on MegaNode, you will need to create an API Key first. API Key in MegaNode is a project-based unit used to manage your API requests. You need to input a name for
```suggestion
To start sending RPC requests on MegaNode, you'll need to create an API Key. This project-based unit is used to manage your API requests, and requires you to input a name for the key and leave any notes you prefer for future reference. Here's how to get started:
```

2023-04-06 07:12 UTC, ashucoder9 commented
Hey @STdevK, a lot of changes requested are not addressed yet. Can you please take a look again and fix them before review?

2023-04-10 15:20 UTC, STdevK commented on docs/operate/archive-node-nodereal
> +:::Fun Fact: NodeReal Upgrade from "APP" to "API Key"
Thank you for highlighting, I've made the changes and shift it after user creates an API key

2023-04-11 20:02 UTC, DannyS03 requested changes
Thanks for the updates @darron.

Added a few more comments, mainly nits.

2023-04-17 06:13 UTC, DannyS03 approved these changes

2023-04-17 06:13 UTC, merged