update seeds
maticnetwork/matic-docs pull request #1530
Opened 2023-03-23 17:31 UTC by cerberushades

- Update Heimdall mainnet seeds
- Include seed nodes and bootnodes in most of the full-node/validator nodes setup docs.

2023-03-23 17:47 UTC, brixial requested changes
some changes for missing apostrophe rest LGTM

2023-03-23 17:47 UTC, brixial commented on docs/maintain/validate/run-validator.md
> +  bootnode ["enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae40
same chaneg as above

2023-03-23 17:47 UTC, brixial commented on docs/operate/full-node-docker.md
> +  bootnode ["enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae40
same change as above

2023-03-23 18:23 UTC, brixial approved these changes

2023-03-27 14:24 UTC, ashucoder9 commented on docs/operate/full-node-docker.md
> +  bootnode ["enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303","enode://88116f4295f5a31538ae
Is it `bootnode` or `bootnodes`?

2023-03-27 14:41 UTC, merged