Update issuer-overview.md
maticnetwork/matic-docs pull request #1534
Opened 2023-03-24 09:00 UTC by nunocgoncalves

Updated the Issuer overview to match the Polygon ID docs - https://0xpolygonid.github.io/tutorials/issuer/issuer-overview/

2023-03-27 13:53 UTC, cerberushades requested changes

2023-03-27 13:53 UTC, cerberushades commented on docs/polygonid/issuer/issuer-overview.md
> +Using Polygon ID an Issuer can issue Credentials to their users (or friends!).
```suggestion
Using Polygon ID, an Issuer can issue Credentials to their users.
```

2023-03-27 13:53 UTC, cerberushades commented on docs/polygonid/issuer/issuer-overview.md
> +Alternatively, you can quickly try out the Credential Issuance experience using the <a href="https://0xpolygonid.github.io/tutorials/issuer/demo-issuer/" target="_blank">Demo Issuer</a>.
```suggestion
Alternatively, you can quickly try out the Credential Issuance experience using the [Demo Issuer](https://0xpolygonid.github.io/tutorials/issuer/demo-issuer/).
```

2023-04-04 17:51 UTC, DannyS03 approved these changes

2023-04-04 17:51 UTC, merged