added thirdweb docs and references
maticnetwork/matic-docs pull request #1651
Opened 2023-05-12 16:43 UTC by saminacodes

2023-05-12 17:47 UTC, DannyS03 requested changes
Thank you for the contribution @saminacodes!

Added suggestions. Majority of them are nits

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +To create a new smart contract using thirdweb CLI, follow these steps:
Would add a quick intro for the CLI and would also link to the docs; something like:

```
[thirdweb CLI](https://portal.thirdweb.com/cli) is a command-line tool that provides developers with an interface to create, deploy, and manage smart contracts and dApps using thirdweb.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +1. In your CLI run the following command:
```suggestion
1. In your CLI, run the following command to create a contract:
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +To create a new smart contract using thirdweb CLI, follow these steps:
```suggestion
To create a new smart contract using thirdweb CLI, follow the step below.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +2. Input your preferences for the command line prompts:
```suggestion
2. Enter your preferred values for the command line prompts:
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +   2. Choose your preferred framework: Hardhat or Foundry
```suggestion
   ii. Choose your preferred framework: [Hardhat](https://hardhat.org/) or [Foundry](https://getfoundry.sh/).
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +   1. Give your project a name
```suggestion
   i. Give your project a name.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +   3. Name your smart contract
```suggestion
   iii. Name your smart contract.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +   4. Choose the type of base contract: Empty, [ERC20](https://portal.thirdweb.com/solidity/base-contracts/erc20base), [ERC721](https://portal.thirdweb.com/solidity/base-contracts/erc721base), or [ER
```suggestion
   iv. Choose the type of base contract: Empty, [ERC20](https://portal.thirdweb.com/solidity/base-contracts/erc20base), [ERC721](https://portal.thirdweb.com/solidity/base-contracts/erc721base), or [ERC1155](https://portal.thirdweb.com/solidity/base-contracts/erc1155base).
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +   5. Add any desired [extensions](https://portal.thirdweb.com/solidity/extensions)
```suggestion
   v. Add any desired [extensions](https://portal.thirdweb.com/solidity/extensions).
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +3. Once created, navigate to your project’s directory and open in your preferred code editor.
```suggestion
3. Once created, navigate to your project’s root directory and open your project in your preferred code editor.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +4. If you open the `contracts` folder, you will find your smart contract; this is your smart contract written in Solidity.
```suggestion
4. If you open the `contracts` folder, you will find your smart contract; the contract you see is your smart contract written in Solidity.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +   The following is code for an ERC721Base contract without specified extensions. It implements all of the logic inside the `[ERC721Base.sol](https://github.com/thirdweb-dev/contracts/blob/main/contr
```suggestion
   The following code is for an ERC721Base contract without specified extensions. It implements all of the logic inside the `[ERC721Base.sol](https://github.com/thirdweb-dev/contracts/blob/main/contracts/base/ERC721Base.sol)` contract, which implements the `[ERC721A](https://github.com/thirdweb-dev/contracts/blob/main/contracts/eip/ERC721A.sol)` standard.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +   - Importing the ERC721Base contract
```suggestion
   - Imports the ERC721Base contract.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +   - Inheriting the contract by declaring that our contract is an ERC721Base contract
```suggestion
   - Inherits the contract by declaring that our contract is an ERC721Base contract.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +   - Implementing any required methods, such as the constructor.
```suggestion
   - Implements the required methods, including the constructor.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +5. After modifying your contract with your desired custom logic, you may deploy it to [Polygon](https://thirdweb.com/polygon) using [Deploy](https://portal.thirdweb.com/deploy).
```suggestion
5. After modifying your contract with your desired custom logic, you may deploy it to [Polygon PoS mainnet](https://thirdweb.com/polygon) using [Deploy](https://portal.thirdweb.com/deploy).
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +> For more information on different contracts available on Explore, check out [thirdweb’s documentation.](https://portal.thirdweb.com/pre-built-contracts)
```suggestion
> For more information on different contracts available on Explore, check out [thirdweb’s documentation](https://portal.thirdweb.com/pre-built-contracts).
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +Alternatively, you can deploy a prebuilt contract for NFTs, tokens, or marketplace directly from the thirdweb Explore page:
```suggestion
Alternatively, you can deploy a prebuilt contract an NFTs, token, or marketplace directly from the thirdweb Explore page. To do so, follow the steps below.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +2. Choose the type of contract you want to deploy from the available options: NFTs, tokens, marketplace, and more.
```suggestion
2. Choose the type of contract you want to deploy from the available options.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +Deploy allows you to deploy a smart contract to any EVM compatible network without configuring RPC URLs, exposing your private keys, writing scripts, and other additional setup such as verifying your
```suggestion
Deploy allows you to deploy a smart contract to any EVM-compatible network without configuring RPC URLs, exposing your private keys, writing scripts, and other additional setup such as verifying your contract.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +   - Compiling all the contracts in the current directory.
```suggestion
   - Compiles all the contracts in the current directory.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +   - Providing the option to select which contract(s) you wish to deploy.
```suggestion
   - Provides the option to select which contract(s) you wish to deploy.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +   - Uploading your contract source code (ABI) to IPFS.
```suggestion
   - Uploads your compiled smart contract code (in the form of an Application Binary Interface, or ABI) to IPFS.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +2. When it is completed, it will open a dashboard interface to finish filling out the parameters.
```suggestion
2. When deployment is complete, a dashboard interface will open to fill out the remaining parameters.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +3. Select [Polygon](https://thirdweb.com/polygon) as the network
```suggestion
3. Select [Polygon](https://thirdweb.com/polygon) as the network.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +4. Manage additional settings on your contract’s dashboard as needed such as uploading NFTs, configuring permissions, and more.
```suggestion
4. Once your smart contract is deployed, you can manage additional settings and functionalities through its dashboard. For example, you can upload NFTs, configure permissions and access control, add new features.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +Contracts deployed to [Polygon](https://thirdweb.com/polygon) are automatically verified by thirdweb. You can check the status on the Sources view in the thirdweb dashboard.
```suggestion
Contracts deployed to [Polygon](https://thirdweb.com/polygon) are automatically verified by thirdweb. You can check the status on the "Sources" view in the thirdweb dashboard.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +If you have any further questions or encounter any issues during the process, please [reach out to thirdweb support](https://support.thirdweb.com).
```suggestion
If you have any questions or encounter any issues during the process, **please reach out to the [official thirdweb support](https://support.thirdweb.com)**.
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/web3-development.md
> +- [Deploy a Smart Contract on Polygon](https://blog.thirdweb.com/guides/deploy-a-smart-contract-on-polygon-matic/)
```suggestion
- [Deploy a Smart Contract on Polygon using thirdweb](https://blog.thirdweb.com/guides/deploy-a-smart-contract-on-polygon-matic/)
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +  - alchemy
```suggestion
  - thirdweb
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +description: Guide to deploy smart contracts using thirdweb
```suggestion
description: "Lean how to deploy smart contracts on Polygon PoS mainnet using thirdweb."
```

2023-05-12 17:47 UTC, DannyS03 commented on docs/develop/thirdweb.md
> +   ```bash
If you're able to provide an example, to coincide with the template(s) and steps, that'd be great. If there is an example already available (for deploying on Polygon), we can also just link out to that.

2023-05-15 19:21 UTC, saminacodes commented
Hey @DannyS03 - made the changed. Let me know if there is anything else pending. Appreciate the help on this

2023-05-15 19:50 UTC, DannyS03 approved these changes
hey @saminacodes, thanks again! lgtm

2023-05-15 22:17 UTC, merged