Add Umbrella Network
maticnetwork/matic-docs pull request #1698
Opened 2023-06-09 20:19 UTC by ed-umb

Add Umbrella Network as an orcale in the developer's documentation.

2023-06-09 20:31 UTC, DannyS03 requested changes
Thank you for the contribution, @ed-umb.

May we:

- Please convert the subheading to lowercase.
- Ensure the document's tone is consistently in third-person. It currently alternates between perspectives.
- Revise the content to be more informational rather than promotional.
- Have consistent spacing in the document.
- Add a reference to Umbrella Network's site at the very beginning

2023-06-10 05:59 UTC, Ishmaello commented
I have submitted a request to umbrella, I hope for reply though I filled company name as Ishmaello and github url of my account I'm not sure if they will consider it. Or, if possible I think I need help with creating company name and its url.

2023-06-27 15:04 UTC, ed-umb commented
Comments addressed with commit c5ae7d1e2ac3b1664e409efea4f941cd87874dbb on Jun 26th.

2023-06-27 15:28 UTC, DannyS03 requested changes
thanks for the changes @ed-umb. Added more suggestions.

2023-06-27 15:28 UTC, DannyS03 commented on docs/develop/oracles/umbrella.md
> +Read data feeds off-chain, and verify them on-chain to safely use them on your dApp. Prices are updated off-chain at a predefined frequency, and eeb3 apps fetches them as required, and submits them o
```suggestion

Read data feeds off-chain and verify them on-chain to ensure secure utilization within your dApp. Prices are regularly updated off-chain at a predefined frequency, and web3 apps fetch this data when needed and submit it on-chain. This approach is particularly advantageous when your project necessitates handling large volumes of data, as storing it entirely on-chain would be cost-prohibitive.
```

2023-06-27 15:28 UTC, DannyS03 commented on docs/develop/oracles/umbrella.md
> +Read data feeds directly on-chain. Projects could define parameters such as deviation triggers and heartbeat to control the number of updates and the precission of the feeds. This is the most straigh
```suggestion

Retrieve data feeds directly on-chain. Projects can define parameters such as deviation triggers and heartbeat to manage the frequency and precision of the updates. This is the simplest and most straightforward approach for reading data.
```

2023-06-27 15:28 UTC, DannyS03 commented on docs/develop/oracles/umbrella.md
> +Data is not predefined. Data will be fetch and delivered upon request of the web3 app. Planned for Q3 2023
```suggestion

On-demand data fetching planned for Q3 2023.
```

2023-06-27 15:28 UTC, DannyS03 commented on docs/develop/oracles/umbrella.md
> +## Technical documentation
```suggestion
## Resources

### Technical documentation
```

2023-06-27 15:28 UTC, DannyS03 commented on docs/develop/oracles/umbrella.md
> +## Custom feeds
```suggestion
### Custom feeds
```

2023-06-27 15:28 UTC, DannyS03 commented on docs/develop/oracles/umbrella.md
> +You can find our technical documentation [<ins>here</ins>](https://umbrella-network.readme.io/docs).
```suggestion

The official technical documentation can be found [<ins>here</ins>](https://umbrella-network.readme.io/docs).
```

2023-06-27 15:28 UTC, DannyS03 commented on docs/develop/oracles/umbrella.md
> +In case your project requires a custom feed, please contact us [<ins>here</ins>](https://www.umb.network/contact#form).
```suggestion

In case your project requires a custom feed, please contact the Umbrella team [<ins>here</ins>](https://www.umb.network/contact#form).
```

2023-06-27 15:28 UTC, DannyS03 commented on docs/develop/oracles/umbrella.md
> +Umbrella Network offers 3 ways to consume data:
```suggestion

Umbrella Network provides three data consumption options: on-chain data, layer 2 data, and on-demand data.
```

2023-06-27 15:28 UTC, DannyS03 commented on docs/develop/oracles/umbrella.md
> +It leverages a network of decentralized community validators that secures the reliability of the data.
```suggestion
The service leverages a network of decentralized community validators to ensure the reliability of the oracle data.
```

2023-06-27 18:54 UTC, ed-umb commented
Hello @DannyS03. Thank you very much for your suggestions. They were accepted. Please check and confirm.

2023-06-27 21:42 UTC, DannyS03 approved these changes
thanks again @ed-umb, lgtm

2023-06-27 21:42 UTC, merged

2023-07-04 17:51 UTC, Ishmaello commented
OK it eventually makes sense to me, I appreciate it.

On Tue, 27 Jun 2023, 11:42 pm Danny Salman ***@***.***> wrote:

> Merged #1698 <https://github.com/maticnetwork/matic-docs/pull/1698> into
> master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/maticnetwork/matic-docs/pull/1698#event-9657405851>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5ACKLKWPYJQPU6YK6VGYTLXNNHWBANCNFSM6AAAAAAZBCNZRM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>