feat(pos): consolidate and polish content
maticnetwork/matic-docs pull request #1733
Opened 2023-06-23 20:35 UTC by DannyS03

## Context

...

2023-06-26 14:51 UTC, cerberushades requested changes

2023-06-26 14:51 UTC, cerberushades commented on docs/governance/index.mdx
> +                  <a href="https://polygon.technology/polygon-supernets" className="landing-page-link">
@DannyS03 is this supposed to go to Supernets?

2023-06-26 14:51 UTC, cerberushades commented on docs/tools/index.mdx
> +                  <a href="https://polygon.technology/polygon-supernets" className="landing-page-link">
going to supernets too @DannyS03

2023-06-26 14:51 UTC, cerberushades commented on docs/specs/features.js
> +        title: "What Do We Mean by Pre-Specs?",
@DannyS03 maybe we're not offering an answer to the question we're showing here just by sending people to this link

2023-06-26 14:56 UTC, cerberushades approved these changes

2023-06-27 09:06 UTC, ashucoder9 approved these changes

2023-06-27 22:12 UTC, merged