Update metatransactions-gsn.md to discuss GSNv1 and GSNv2
maticnetwork/matic-docs pull request #282
Opened 2020-09-28 10:22 UTC by JUDOKICK

Added and extended docs to include deployed GSNv1 that is deployed in matic testnet and mainnet and links to help new users onboard

2020-09-30 06:44 UTC, itzmeanjan requested changes
Can you please make these changes @JUDOKICK ? Let me know you view.

And good work @JUDOKICK .

2020-09-30 06:44 UTC, itzmeanjan commented on docs/develop/metatransactions/metatransactions-gsn.md
> +For those looking to run your own relayer, the folks at [Creol.io](Creol.io) have created a very simple guide and tutorial for doing so on one of their github pages. [Running your own GSNv1 Relayer](
Can you please remove last sentence from this paragraph ? 

@JUDOKICK

2020-09-30 06:44 UTC, itzmeanjan commented on docs/develop/metatransactions/metatransactions-gsn.md
> +For those looking to run your own relayer, the folks at [Creol.io](Creol.io) have created a very simple guide and tutorial for doing so on one of their github pages. [Running your own GSNv1 Relayer](
Also please replace `folks at Creol.io` with `our friends at Creol.io`. Sounds better, right @JUDOKICK ?

2020-09-30 06:44 UTC, itzmeanjan commented on docs/develop/metatransactions/metatransactions-gsn.md
> +For those looking to run your own relayer, the folks at [Creol.io](Creol.io) have created a very simple guide and tutorial for doing so on one of their github pages. [Running your own GSNv1 Relayer](
This one is not required here.

2020-10-02 09:53 UTC, JUDOKICK reviewed
Fixed as suggested!

2020-10-02 11:47 UTC, itzmeanjan approved these changes
Looks great +1

2020-10-02 11:48 UTC, merged