Export Seed Phrase
maticnetwork/matic-docs pull request #326
Opened 2020-12-30 06:53 UTC by itzmeanjan

- Guide for exporting seed phrase from Matic Mobile Wallet.
- Build issue resolved.

cc @vidyaakrishna @ryegineni

2021-01-02 16:24 UTC, anurag-arjun approved these changes

2021-01-03 04:06 UTC, anurag-arjun requested changes

2021-01-03 04:06 UTC, anurag-arjun commented on sidebars.js
> +        "develop/wallets/exporting-seed-phrase",
Put it under a new category `Matic Wallet`

2021-01-03 06:57 UTC, itzmeanjan commented on sidebars.js
> +        "develop/wallets/exporting-seed-phrase",
Ok, doing so.

2021-01-03 07:05 UTC, itzmeanjan commented on sidebars.js
> +        "develop/wallets/exporting-seed-phrase",
Done.

2021-01-03 07:10 UTC, itzmeanjan commented on sidebars.js
> +        "develop/wallets/exporting-seed-phrase",
Conflict resolved.

2021-01-04 08:28 UTC, anurag-arjun approved these changes

2021-01-04 08:29 UTC, merged