Adding QuickNode section to the develope, adding resources, and updating QuickNode links.
maticnetwork/matic-docs pull request #764
Opened 2022-02-01 14:34 UTC by Sahilsen

2022-02-01 20:46 UTC, stephenplusplus reviewed
Great guide!

2022-02-01 20:46 UTC, stephenplusplus commented on docs/develop/quicknode.md
> +Line 3: We are declaring our contract here and naming it as `Simplestorage`.
```suggestion
Line 3: We are declaring our contract here and naming it as `SimpleStorage`.
```

2022-02-01 20:46 UTC, stephenplusplus commented on docs/develop/quicknode.md
> +To input a value, enter a number in the field near the `set` button, click on set and approve the transaction from the MetaMask pop-up. Once the transaction is approved, value of the **storedData** w
```suggestion
To input a value, enter a number in the field near the `set` button, click on set and approve the transaction from the MetaMask pop-up. Once the transaction is approved, value of the **storedData** will be the input number. To verify this, click on `get`, and the inputted value will be printed.
```

2022-02-01 20:46 UTC, stephenplusplus commented on docs/develop/quicknode.md
> +We hope this guide was helpful. We'll be happy to hear from you. DM us or tag us on Twiiter [@QuickNode](https://twitter.com/QuickNode)
```suggestion
We hope this guide was helpful. We'll be happy to hear from you. DM us or tag us on Twitter [@QuickNode](https://twitter.com/QuickNode).
```

2022-02-03 01:22 UTC, Sahilsen commented
Hey, @stephenplusplus thank you so much for the review. I've changed the guide to use Brownie instead of REMIX as a REMIX guide was already in place as suggested by Nazim and Sandipan from Polygon, thanks.

Please check:
https://github.com/maticnetwork/matic-docs/pull/764/commits/790583c3ffde56b6ea400e6caf54a753746b43d4

2022-02-03 17:21 UTC, abunsen requested changes

2022-02-03 17:21 UTC, abunsen commented on docs/develop/quicknode.md
> +Copy the HTTP URL, which will be needed in the next step.
We should add a bit here that exposes the free/public RPC node QuickNode runs for Matic? Along with a note that says if they're rate limited to buy a node?

2022-02-03 23:18 UTC, Sahilsen commented on docs/develop/quicknode.md
> +Copy the HTTP URL, which will be needed in the next step.
Done, added a line to mention the public RPC.

2022-02-07 15:51 UTC, Nazeim approved these changes

2022-02-07 15:56 UTC, merged