Added JSON-RPC Polygon methods to Polygon Docs
maticnetwork/matic-docs pull request #820
Opened 2022-03-17 22:34 UTC by pileofscraps

The current docs are missing links to RPC methods; added a JSON-RPC docs page a few other getting-started guides

2022-03-18 08:52 UTC, ssandeep approved these changes

2022-03-21 18:49 UTC, DannyS03 requested changes
Thank you, left some suggestions.

The file name also has an additional "t" in "getting"

2022-03-21 18:49 UTC, DannyS03 commented on docs/develop/api-documentation/gettting-started.md
> +JSON-RPC is a stateless, light-weight remote procedure call (RPC) protocol that is commonly used for interacting with the Polygon network layer. As an integral part of the Blockchain Interaction Laye
Can extend the definition of JSON-RPC to be more clear, as in: 
```
JSON-RPC is a stateless, light-weight remote procedure call (RPC) protocol that is encoded in JSON.
```
I also think if we are adding an intro-level guide, it should point out some additional fundamentals. For example, a user would benefit from:
- general info about RPCs, then lead into JSON-RPC (perhaps on other approaches)
- pointing out if there is a difference between a call and method
- why the Polygon network uses JSON-RPC (e.g. easy to implement)

Better practice would be using internal docs or written pieces to reference the Web3 ecosystem, instead of using the alchemy blog post

2022-03-21 18:49 UTC, DannyS03 commented on docs/develop/api-documentation/gettting-started.md
> +To get started with the API, [visit a complete set of API documentation for standard Polygon JSON-RPC calls](https://docs.alchemy.com/alchemy/apis/polygon-api/?a=matic-docs).
same idea here, should link to internal docs

2022-03-23 08:40 UTC, Nazeim approved these changes

2022-03-23 12:50 UTC, DannyS03 reviewed
Would still advocate for the previous suggestions and if not, please let us know. The file name still has an extra "t" in "getting".

2022-03-23 13:04 UTC, Nazeim commented
Hi @ssandeep and @pileofscraps,
Please check the previous suggestions for us to be able to review and merge:

- [Suggestion 1](https://github.com/maticnetwork/matic-docs/pull/820#discussion_r831433347)
- [Suggestion 2](https://github.com/maticnetwork/matic-docs/pull/820#discussion_r831433584)
- [Suggestion 3](https://github.com/maticnetwork/matic-docs/pull/820#discussion_r831434114)

2022-03-25 14:37 UTC, Peeraphat9 commented
> เอกสารปัจจุบันไม่มีลิงก์ไปยังวิธี RPC เพิ่มหน้าเอกสาร JSON-RPC และคู่มือการเริ่มต้นใช้งานอื่นๆ อีกสองสามรายการ

2022-04-11 04:32 UTC, DannyS03 commented
@pileofscraps wondering if you had a chance to revisit

2022-04-25 18:57 UTC, DannyS03 commented
Going to merge so the update isn't hanging and have the team revisit

2022-04-25 18:57 UTC, DannyS03 approved these changes
pending additional enhancements but core content update lgtu

2022-04-25 18:59 UTC, DannyS03 commented on docs/develop/api-documentation/gettting-started.md
> +JSON-RPC is a stateless, light-weight remote procedure call (RPC) protocol that is commonly used for interacting with the Polygon network layer. As an integral part of the Blockchain Interaction Laye
```suggestion
JSON-RPC is a stateless, light-weight remote procedure call (RPC) protocol that is commonly used for interacting with the Polygon network layer. Polygon JSON-RPC methods allow developers to query for data, write to the blockchain, and build dApps.
```

2022-04-25 19:00 UTC, DannyS03 commented on docs/develop/api-documentation/gettting-started.md
> +To get started with the API, visit the complete set of API documentation for standard [Polygon JSON-RPC calls](https://docs.alchemy.com/alchemy/apis/polygon-api/?a=matic-docs).
```suggestion
To get started with the API, visit the complete set of API documentation for standard [Polygon JSON-RPC calls](https://edge-docs.polygon.technology/docs/get-started/json-rpc-commands/).
```

2022-04-25 19:03 UTC, DannyS03 commented on docs/develop/api-documentation/gettting-started.md
> +Composer allows developers to save hours of debugging and building time while also providing a friendly UI for sharing API calls.
```suggestion
```

2022-04-25 19:03 UTC, DannyS03 commented on docs/develop/api-documentation/gettting-started.md
> +If you want to get started with API requests with no set-up, fix failing requests, or explore new methods on the Polygon network, try out the [Composer App](https://composer.alchemyapi.io?composer_st
```suggestion
If you want to get started with API requests that require no set-up, fix failing requests, or, explore new methods on the Polygon network, try out the [Composer App](https://composer.alchemyapi.io?composer_state=%7B%22chain%22%3A2%2C%22network%22%3A401%2C%22methodName%22%3A%22eth_getBlockByNumber%22%2C%22paramValues%22%3A%5B%22latest%22%2Cfalse%5D%7D).
```

2022-04-26 14:42 UTC, merged