feat: add SettleMint to the RPC providers
maticnetwork/matic-docs pull request #827
Opened 2022-03-24 06:13 UTC by roderik

2022-03-24 13:28 UTC, DannyS03 requested changes
- Should link to the right RPC docs instead of the general SettleMint page
- Should be listed after QuickNode

2022-03-25 08:17 UTC, roderik commented
@DannyS03 fixed the comments

2022-03-25 13:08 UTC, DannyS03 reviewed
Thanks @roderik, just need to put it after QuickNode for the WebSocket section too

2022-03-28 13:24 UTC, DannyS03 approved these changes

2022-03-28 14:31 UTC, merged