added questions to general and wallet-bridge FAQs
maticnetwork/matic-docs pull request #830
Opened 2022-03-25 16:10 UTC by cerberushades

2022-03-29 13:04 UTC, DannyS03 requested changes
Thanks @cerberushades, left some comments

2022-03-29 13:04 UTC, DannyS03 commented on docs/faq/wallet-bridge-faq.md
> +As we never ask for your private keys or use them in any way, we can’t revert unwanted transactions.
Would benefit from rewording as it seems we are claiming that if we did have access to your keys we could revert the transaction

2022-03-30 04:43 UTC, DannyS03 requested changes
few more comments
- should be consistent if bolding the options that appear when transacting, such as Approve, Cancel, etc.
- doc would benefit from formatting (as in, prettify)

2022-03-30 04:43 UTC, DannyS03 commented on docs/faq/wallet-bridge-faq.md
> +Unfortunately, we can’t revert unwanted transactions.
would be even more clear here and state "the network cannot revert unwanted transactions"

2022-03-30 04:43 UTC, DannyS03 commented on docs/faq/wallet-bridge-faq.md
> +If you have started the transaction, it is important not to cancel it. Instead, you can wait for it to lower or add more Ether to your account.
- unclear about what is waiting to lower (gas fees)
- a user may ask if they need to add more ETH or MATIC, do both work?
- the case for when a user is stuck -> we should clearly state if this is the only option

2022-04-04 13:56 UTC, Nazeim approved these changes

2022-04-04 14:01 UTC, DannyS03 commented on docs/faq/wallet-bridge-faq.md
> +Unfortunately, we can’t revert unwanted transactions.
```suggestion
Unfortunately, the network cannot revert unwanted transactions. 
```

2022-04-04 14:08 UTC, merged