[WIP - Don't merge] Update node binary installation guide
maticnetwork/matic-docs pull request #874
Opened 2022-04-26 22:20 UTC by cffls

This doc update will ask users to install binaries with an installation script, instead of building binaries from source code.
It will make node binary installation and update easier for users.

The [new installation script](https://github.com/maticnetwork/install) hasn't been open sourced yet. We will hold this PR until the script is open sourced.

2022-04-27 05:10 UTC, DannyS03 commented
Hi @cffls, thanks for this - I'd advise us to keep the existing documentation instead of replacing it

2022-04-27 05:12 UTC, cffls commented
Thanks Danny, that is a good point. I will try keeping existing docs and add new things on top of it.

2022-05-05 16:33 UTC, cffls commented
@Nazeim Thanks for pushing this forward! ☺️ However, I am still working on this PR, as some components are not finalized yet. I will remove "WIP" tag once the work has completed.

2022-05-12 21:33 UTC, cffls commented
@Nazeim @vcastellm I've completed the first version of this draft. Please review. Thank you!

2022-05-17 21:05 UTC, DannyS03 commented
Adding DNM until we push https://github.com/maticnetwork/matic-docs/pull/882

2022-05-23 07:48 UTC, DannyS03 requested changes
many thanks @cffls

@Nazeim we should test end-to-end

2022-05-23 07:48 UTC, DannyS03 commented on docs/maintain/validate/run-validator-binaries.md
> +[Full Node](run-validator).
```suggestion
the latest [Validator guide](run-validator).
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/maintain/validate/run-validator.md
> +
```suggestion
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/maintain/validate/run-validator.md
> +This guide only applies to Bor and Heimdall version >= 0.3.0. For older versions, please follow the guides in
```suggestion
This guide only applies to Bor and Heimdall version >= 0.3.0. For older versions, please follow
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/maintain/validate/run-validator.md
> +[Full Node Binaries (Legacy)](run-validator-binaries.md).
```suggestion
the legacy [Validator guide](run-validator-binaries.md).
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +
```suggestion
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +title: Full Node
```suggestion
title: Run a Full Node
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +description: Build your next blockchain app on Polygon.
```suggestion
description: Learn how to run a full node on Polygon using utility scripts
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +# Polygon Full Node Setup Using Packages
```suggestion
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +
```suggestion
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +
```suggestion
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +
```suggestion
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +
```suggestion
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +## Install packages
```suggestion
## Install Binaries
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +There are three different ways to install heimdall and bor binaries: [installing packages](#install-with-packages-recommended), [installing using ansible](#install-with-ansible), and [building from s
```suggestion
There are three different ways to install the Heimdall and Bor binaries: 
[installing packages via utility scripts](#install-with-packages-recommended), [installing via Ansible](#install-with-ansible), and [building from the source code](#install-from-source-code).
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +- Install the default latest version
```suggestion
- Install the default latest version:
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +    [Heimdall Github repository](https://github.com/maticnetwork/heimdall/releases)):
```suggestion
    [Heimdall GitHub repository](https://github.com/maticnetwork/heimdall/releases)):
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +    or install a specific version (all release versions could be found on
```suggestion
    or install a specific version (all release versions can be found on 
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +- Install the default latest version
```suggestion
- Install the default latest version:
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +    curl -L https://raw.githubusercontent.com/maticnetwork/install/main/bor.sh | bash -s -- 0.3.0
```suggestion
    # curl -L https://raw.githubusercontent.com/maticnetwork/install/main/bor.sh | bash -s -- 0.3.0
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +### Install with ansible
```suggestion
### Install with Ansible
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +* Three machines — one local machine on which you will run the Ansible playbook; two remote machines — one [sentry](../glossary#sentry) and one [validator](../glossary#validator).
on using the terms *local* and *remote* here as "prerequisites"; if this should be worded to better fit "the recommended/common approach" (i.e. the most common way to run a full node is by using cloud servers through a VPS)

because technically, can't ansible playbook run remotely and can't a user run a sentry node & validator node on their local machines?

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +* On the remote machines, make sure Go is *not* installed.
```suggestion
* On the remote machines, make sure Go is **not** installed.
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +
```suggestion
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +
```suggestion
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +Change to the cloned repository:
```suggestion
Navigate to the root of the repository:
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +Bor and Heimdall 0.3.0 uses standardized paths for configuration files and chain data. If you have existing
```suggestion
Bor and Heimdall 0.3.0 use standardized paths for configuration files and chain data. If you have existing 
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +config files and chain data on your node, please skip [Configure Heimdall](#configure-heimdall) below, and jump directly to [Migration](#migration) section to learn about migrating configs and data t
```suggestion
config files and chain data on your node, please skip the [Configure Heimdall](#configure-heimdall) section below and jump directly to [Migration](#migration) section to learn about migrating configs and data to standardized file locations.
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +- Initialize heimdall configs
```suggestion
- Initialize Heimdall configs
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +    curl -L https://raw.githubusercontent.com/maticnetwork/install/main/heimdall.sh | bash -s -- 0.3.0
```suggestion
    # curl -L https://raw.githubusercontent.com/maticnetwork/install/main/heimdall.sh | bash -s -- 0.3.0
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +
```suggestion
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +- Stop existing heimdall and bor services
```suggestion
- Stop existing heimdall and bor services:

```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +- Create a backup folder in case something went wrong
```suggestion
- Create a backup folder in case something went wrong:

```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +- Move old binaries
```suggestion
- Move old binaries:

```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +- Move old service files
```suggestion
- Move old service files:

```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +- Migrate heimdall and bor directory to `/var/lib`
```suggestion
- Migrate heimdall and bor directory to `/var/lib`:

```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +    ```shell
```suggestion
    ```shell:
    
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +    In case data copying is too slow or original data folder is mounted on a different device, you can create symlinks
```suggestion
    In case data copying is too slow or original data folder is mounted on a different device, 
    you can create symlinks:
    
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/integrate/full-node.md
> +```
```suggestion
```shell
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/maintain/validate/run-validator.md
> +There are three different ways to install heimdall and bor binaries: [installing packages](#install-with-packages-recommended), [installing using ansible](#install-with-ansible), and [building from s
```suggestion
There are three different ways to install heimdall and bor binaries: [installing packages via utility scripts](#install-with-packages-recommended), [installing via Ansible](#install-with-ansible), and [building from source code](#install-from-source-code).
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/maintain/validate/run-validator.md
> +
```suggestion
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/maintain/validate/run-validator.md
> +
```suggestion
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/maintain/validate/run-validator.md
> +```
```suggestion
```sh
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/maintain/validate/run-validator.md
> +
```suggestion
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/maintain/validate/run-validator.md
> +
```suggestion
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/maintain/validate/run-validator.md
> +
```suggestion
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/maintain/validate/run-validator.md
> +## Configure service files for bor and heimdall
```suggestion
## Configure service files for Bor and Heimdall
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/maintain/validate/run-validator.md
> +However, if you still want to perform upgrade on existing node, you need to follow one-time migration steps
```suggestion
However, if you still want to perform an upgrade on existing node, you need to follow the one-time migration steps 
```

2022-05-23 07:48 UTC, DannyS03 commented on docs/maintain/validate/run-validator.md
> +
```suggestion
```

2022-05-23 17:16 UTC, cffls commented
Thank you @DannyS03 for proofreading and applying changes to the PR! Really appreciate your help. However, we can't merge this PR yet, because v0.3.0 of Bor and Heimdall have not been officially released. We are still in the testing phase and there still could be some changes to Bor and Heimdall in the future. Please hold this PR until we have finalized v0.3.0 and ready to notify external validators. I will remove the "DNM" tag once we are ready from our side. Thank you again for the helps!

2022-06-07 10:26 UTC, vcastellm approved these changes
LGTM

2022-06-07 11:06 UTC, vcastellm approved these changes
LGTM

2022-06-08 07:56 UTC, DannyS03 approved these changes

2022-06-11 23:14 UTC, DannyS03 commented
@cffls feel free to let us know when all desired contributions have been made

2022-06-16 09:59 UTC, vcastellm reviewed
Would be interesting to add running under docker docs? maybe in another PR?

2022-06-16 16:59 UTC, cffls commented
> Would be interesting to add running under docker docs? maybe in another PR?
Docker docs will be a good idea, but I'd put it in another PR, since this PR is mostly for changing existing docs.

@DannyS03 We are still in testing phase. I will notify you when everything is finalized. Thank you!

2022-08-15 04:38 UTC, cffls commented
Hi @Nazeim, sorry about the late response. There are some new changes coming to v0.3.0. I will update this PR within this week.

2022-09-07 18:36 UTC, cffls commented
Sorry @Nazeim, it is not ready to merge yet. We are still working on some toolings. I will update this thread once we are ready to merge. Thank you!

2022-11-15 03:12 UTC, DannyS03 commented
@cffls any new update? :)

2023-01-11 08:43 UTC, ashucoder9 commented on docs/develop/network-details/full-node-binaries.md
> +This guide only applies to Bor and Heimdall version 0.2.x and will be deprecated soon. For current mainnet version, please follow the guides in
```suggestion
This guide only applies to Bor and Heimdall version 0.2.x and will be deprecated soon. For the current Mainnet version, please follow the guides in 
```

2023-01-11 08:44 UTC, ashucoder9 commented on docs/develop/network-details/full-node-deployment.md
> +This guide only applies to Bor and Heimdall version 0.2.x and will be deprecated soon. For current mainnet version, please follow the guides in
```suggestion
This guide only applies to Bor and Heimdall version 0.2.x and will be deprecated soon. For the current Mainnet version, please follow the guides in 
```

2023-01-11 08:44 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +description: Learn how to run a full node on Polygon using utility scripts
```suggestion
description: Learn how to run a full node on the Polygon network using utility scripts.
```

2023-01-11 08:45 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +  - matic
```suggestion
  - polygon wiki
  - full node
  - mainnet
  - heimdall
  - bor
```

2023-01-11 08:46 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +This section guides you through starting and running a full node from a package.
```suggestion
This document guides you through the process of starting and running a full node on the Polygon network from a package.
```

2023-01-11 08:47 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +For the system requirements, see [Minimum Technical Requirements](https://docs.polygon.technology/docs/develop/network-details/technical-requirements).
```suggestion
For the system requirements, see [Minimum Technical Requirements](technical-requirements.md).
```

2023-01-11 08:47 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +:::note
```suggestion
:::tip
```

2023-01-11 08:49 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +- Have the one machine prepared.
```suggestion
- Prepare the Full Node machine.
```

2023-01-11 08:49 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +- Install the Heimdall and Bor packages on the Full Node machine.
```suggestion
- Install Heimdall and Bor packages on the Full Node machine.
```

2023-01-11 08:50 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +- Install the default latest version of sentry for mainnet:
```suggestion
- Install the default latest version of sentry for Mainnet:
```

2023-01-11 08:50 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +- Install the default latest version of sentry for mainnet:
```suggestion
- Install the default latest version of sentry for Mainnet:
```

2023-01-11 08:51 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +    or install a specific version,  node type (`sentry` or `validator`), and network (`mainnet` or `testnet`). All release versions could be found on
```suggestion
    or install a specific version, node type (`sentry` or `validator`), and network (`mainnet` or `testnet`). All release versions could be found on 
```

2023-01-11 08:52 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +* Three machines — one local machine on which you will run the Ansible playbook; two remote machines — one [sentry](../glossary#sentry) and one [validator](../glossary#validator).
```suggestion
* Three machines — one local machine on which you will run the Ansible playbook; two remote machines — one [sentry](/maintain/glossary.md#sentry) and one [validator](/maintain/glossary.md#validator).
```

2023-01-11 08:53 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +* We have Bloxroute available as a relay network. If you need a gateway to be added as your Trusted Peer please contact [Delroy on Discord](http://delroy/#0056).
```suggestion
* We have **Bloxroute** available as a relay network. If you need a gateway to be added as your **Trusted Peer** please contact [Delroy on Discord](http://delroy/#0056).
```

2023-01-11 08:54 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +* Two machines — one [sentry](../glossary#sentry) and one [validator](../glossary#validator).
```suggestion
* Two machines — one [sentry](/maintain/glossary.md#sentry) and one [validator](/maintain/glossary.md#validator).
```

2023-01-11 08:56 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +[Heimdall](../validator/core-components/heimdall-chain.md) is the proof-of-stake verifier layer
```suggestion
[Heimdall](/maintain/validator/core-components/heimdall-chain.md) is the proof-of-stake verifier layer
```

2023-01-11 08:56 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +responsible for checkpointing the representation of the Plasma blocks to the Ethereum mainnet.
```suggestion
responsible for checkpointing the representation of the Plasma blocks to the Ethereum Mainnet.
```

2023-01-11 08:57 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +[Bor](../../contribute/bor/) is the sidechain operator that acts as the block production layer,
```suggestion
[Bor](/pos/bor/overview.md) is the sidechain operator that acts as the block production layer,
```

2023-01-11 08:58 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +which syncs with Heimdall to select block producers and verifiers for each [span](../glossary#span)
```suggestion
which syncs with Heimdall to select block producers and verifiers for each [span](/maintain/glossary.md#span)
```

2023-01-11 08:58 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +and [sprint]((../glossary#sprint)).
```suggestion
and [sprint]((/maintain/glossary.md#sprint)).
```

2023-01-11 08:59 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +- Stop existing heimdall and bor services:
```suggestion
- Stop existing Heimdall and Bor services:
```

2023-01-11 09:00 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +  You can use [this util script](https://github.com/maticnetwork/bor/blob/develop/scripts/getconfig.sh) to convert start.sh to a config.toml file on your host. Example usage:
```suggestion
  You can use [this util script](https://github.com/maticnetwork/bor/blob/develop/scripts/getconfig.sh) to convert `start.sh` to a `config.toml` file on your host. Example usage:
```

2023-01-11 09:01 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +    ```shell
```suggestion
```bash
```

2023-01-11 09:01 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +    ```
```suggestion
```
```

2023-01-11 09:02 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +    ```
```suggestion
```
```

2023-01-11 09:02 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +After successfully installing Bor and Heimdall through [packages](#install-with-packages-recommended), their service file could be found under `/lib/systemd/system`, and bor's config
```suggestion
After successfully installing Bor and Heimdall through [packages](#install-with-packages-recommended), their service file could be found under `/lib/systemd/system`, and Bor's config 
```

2023-01-11 09:03 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +Start heimdall, heimdall rest server, and heimdall bridge.
```suggestion
Start Heimdall, Heimdall rest server, and Heimdall bridge.
```

2023-01-11 09:03 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +You check Heimdall logs vid command
```suggestion
You can also check Heimdall logs with command
```

2023-01-11 09:04 UTC, ashucoder9 commented on docs/home/new-to-matic.md
> +[Run a Validator Node](/docs/validate/validate/run-validator) guide.
```suggestion
[Run a Validator Node](/validate/validate/run-validator.md) guide.
```

2023-01-11 09:05 UTC, ashucoder9 commented on docs/home/polygon-basics/what-is-polygon.md
> +[Run a Validator Node](/docs/validate/validate/run-validator) guide.
```suggestion
[Run a Validator Node](/validate/validate/run-validator.md) guide.
```

2023-01-11 09:05 UTC, ashucoder9 commented on docs/maintain/validate/faq/how-to.md
> +You can add the persistent_peers in the following file:
```suggestion
You can add the `persistent_peers` in the following file:
```

2023-01-11 09:07 UTC, ashucoder9 commented on docs/maintain/validate/faq/validator-faq.md
> +* [Run a Validator Node](../run-validator)
```suggestion
* [Run a Validator Node](/maintain/validate/run-validator.md)
```

2023-01-11 09:10 UTC, ashucoder9 commented on docs/maintain/validate/run-validator-ansible.md
> +This guide only applies to Bor and Heimdall version 0.2.x and will be deprecated soon. For current mainnet version, please follow the guides in
```suggestion
This guide only applies to Bor and Heimdall version 0.2.x and will be deprecated soon. For the current Mainnet version, please follow the guides in 
```

2023-01-11 09:10 UTC, ashucoder9 commented on docs/maintain/validate/run-validator-binaries.md
> +This guide only applies to Bor and Heimdall version 0.2.x and will be deprecated soon. For current mainnet version, please follow the guides in
```suggestion
This guide only applies to Bor and Heimdall version 0.2.x and will be deprecated soon. For the current Mainnet version, please follow the guides in 
```

2023-01-11 09:11 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +  - matic
```suggestion
  - polygon wiki
```

2023-01-11 09:13 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +* Two machines — one [sentry](/docs/validate/glossary#sentry) and one [validator](/docs/validate/glossary#validator).
```suggestion
* Two machines — one [sentry](/maintain/glossary.md#sentry) and one [validator](/maintain/glossary.md#validator).
```

2023-01-11 09:13 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +- Install the default latest version of sentry for mainnet:
```suggestion
- Install the default latest version of sentry for Mainnet:
```

2023-01-11 09:14 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +* Three machines — one local machine on which you will run the Ansible playbook; two remote machines — one [sentry](../glossary#sentry) and one [validator](../glossary#validator).
```suggestion
* Three machines — one local machine on which you will run the Ansible playbook; two remote machines — one [sentry](/maintain/glossary.md#sentry) and one [validator](/maintain/glossary.md#validator).
```

2023-01-11 09:14 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +* We have Bloxroute available as a relay network. If you need a gateway to be added as your Trusted Peer please contact [Delroy on Discord](http://delroy/#0056).
```suggestion
* We have **Bloxroute** available as a relay network. If you need a gateway to be added as your **Trusted Peer**, please contact [Delroy on Discord](http://delroy/#0056).
```

2023-01-11 09:15 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +* Two machines — one [sentry](../glossary#sentry) and one [validator](../glossary#validator).
```suggestion
* Two machines — one [sentry](/maintain/glossary.md#sentry) and one [validator](/maintain/glossary.md#validator).
```

2023-01-11 09:16 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +[Heimdall](../validator/core-components/heimdall-chain.md) is the proof-of-stake verifier layer
```suggestion
[Heimdall](/maintain/validator/core-components/heimdall-chain.md) is the proof-of-stake verifier layer
```

2023-01-11 09:16 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +responsible for checkpointing the representation of the Plasma blocks to the Ethereum mainnet.
```suggestion
responsible for checkpointing the representation of the Plasma blocks to the Ethereum Mainnet.
```

2023-01-11 09:16 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +[Bor](../../contribute/bor/) is the sidechain operator that acts as the block production layer,
```suggestion
[Bor](/pos/bor/overview.md) is the sidechain operator that acts as the block production layer,
```

2023-01-11 09:17 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +and [sprint]((../glossary#sprint)).
```suggestion
and [sprint]((/maintain/glossary.md#sprint)).
```

2023-01-11 09:17 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +which syncs with Heimdall to select block producers and verifiers for each [span](../glossary#span)
```suggestion
which syncs with Heimdall to select block producers and verifiers for each [span](/maintain/glossary.md#span)
```

2023-01-11 09:18 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +- Initialize heimdall configs
```suggestion
- Initialize Heimdall configs
```

2023-01-11 09:18 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +- Stop existing heimdall and bor services
```suggestion
- Stop existing Heimdall and Bor services
```

2023-01-11 09:19 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +- Copy configurations in `node/bor/start.sh` to bor configuration file `/var/lib/bor/config.toml`. Note that some
```suggestion
- Copy configurations in `node/bor/start.sh` to Bor configuration file `/var/lib/bor/config.toml`. Note that some 
```

2023-01-11 09:19 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +  You can use [this util script](https://github.com/maticnetwork/bor/blob/develop/scripts/getconfig.sh) to convert start.sh to a config.toml file on your host. Example usage:
```suggestion
  You can use [this util script](https://github.com/maticnetwork/bor/blob/develop/scripts/getconfig.sh) to convert `start.sh` to a `config.toml` file on your host. Example usage:
```

2023-01-11 09:19 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +After successfully installing Bor and Heimdall through [packages](#install-with-packages-recommended), their service file could be found under `/lib/systemd/system`, and bor's config
```suggestion
After successfully installing Bor and Heimdall through [packages](#install-with-packages-recommended), their service file could be found under `/lib/systemd/system`, and Bor's config 
```

2023-01-11 09:20 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +    - To enable Archive mode you can optionally enable the following flags:
```suggestion
    - To enable Archive mode, you can optionally enable the following flags:
```

2023-01-11 09:21 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +- Stop existing heimdall and bor services
```suggestion
- Stop existing Heimdall and Bor services
```

2023-01-11 09:21 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +- Migrate heimdall and bor directory to `/var/lib` and change ownership:
```suggestion
- Migrate the Heimdall and Bor directory to `/var/lib` and change ownership:
```

2023-01-11 09:21 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +After successfully installing Bor and Heimdall through [packages](#install-with-packages-recommended), their service file could be found under `/lib/systemd/system`, and bor's config
```suggestion
After successfully installing Bor and Heimdall through [packages](#install-with-packages-recommended), their service file could be found under `/lib/systemd/system`, and Bor's config 
```

2023-01-11 09:22 UTC, ashucoder9 commented on docs/maintain/validate/run-validator.md
> +the [Staking](../validator/core-components/staking.md) guide to start backing the network.
```suggestion
the [Staking](/maintain/validator/core-components/staking.md) guide to start backing the network.
```

2023-01-11 09:23 UTC, ashucoder9 commented on docs/maintain/validate/technical-faqs.md
> +description: Build your next blockchain app on Polygon.
```suggestion
description: Frequently asked questions related to running a Validator on the Polygon network.
```

2023-01-11 09:23 UTC, ashucoder9 commented on docs/maintain/validate/technical-faqs.md
> +  - matic
```suggestion
  - polygon wiki
```

2023-01-11 09:24 UTC, ashucoder9 commented on docs/maintain/validate/technical-faqs.md
> +image: https://matic.network/banners/matic-network-16x9.png
```suggestion
image: https://wiki.polygon.technology/img/polygon-wiki.png
```

2023-01-11 09:24 UTC, ashucoder9 commented on docs/maintain/validate/technical-faqs.md
> +    heimdalld unsafe-reset-all
```suggestion
    ```heimdalld unsafe-reset-all```
```

2023-01-11 09:25 UTC, ashucoder9 commented on docs/maintain/validate/technical-faqs.md
> +Change the config to `goleveldb` in config.toml
```suggestion
Change the config to `goleveldb` in `config.toml`.
```

2023-01-11 09:30 UTC, ashucoder9 commented on docs/develop/network-details/full-node.md
> +    ```
```suggestion
```

2023-01-11 09:36 UTC, ashucoder9 approved these changes

2023-01-12 14:14 UTC, DannyS03 commented on docs/maintain/validate/run-validator.md
> +  - matic
we've been using "matic" as a generic tag

2023-01-12 14:18 UTC, DannyS03 approved these changes
thanks @cffls! LGTM mod some tweaks.

@ashucoder9 I see you added some of the suggestions already, do you mind resolving the conservations for the suggestions already resolved?

2023-01-12 14:19 UTC, ashucoder9 commented
Sure @DannyS03!

2023-01-12 14:25 UTC, ashucoder9 approved these changes

2023-01-13 09:19 UTC, DannyS03 commented
@cffls it looks like https://github.com/maticnetwork/matic-docs/pull/874/commits/c13a1d5db174858ab5b8e27a2aba1d94f3ca3a40 removed instead of kept.

2023-01-13 17:37 UTC, cffls commented
The commit removed the deprecation warning and some duplicated contents in the new package guide.

2023-01-15 10:37 UTC, merged