Landing Page Tweaks + Add Footer
maticnetwork/matic-docs pull request #915
Opened 2022-05-30 17:01 UTC by DannyS03

- Tweaks to styles
- Re-adds Footer

Overall design to be reconsidered in the near future

2022-05-30 17:09 UTC, DannyS03 commented
proposing we update the landing page tabs - while "new" and "experienced" are good categorizations, I feel they don't accurately depict all the content, and the sub-labels on the cards mention the "difficultly"

2022-05-30 17:39 UTC, cerberushades commented
> proposing we update the landing page tabs - while "new" and "experienced" are good categorizations, I feel they don't accurately depict all the content, and the sub-labels on the cards mention the "difficultly"

We might also rethink that "Scale with Polygon". I'm not sure all products by polygon deal with scaling. Polygon ID probably not

2022-05-30 17:52 UTC, cerberushades requested changes

2022-05-30 17:52 UTC, cerberushades commented on docusaurus.config.js
> +          title: "Scaling Solutions",
why not keep it only "Solutions"?

2022-05-30 17:52 UTC, cerberushades commented on src/css/custom.css
> +  background: #D0BAF5;
not sure this color provides a good contrast with black... I'd go with sth lighter or keep the current one...

2022-05-30 17:52 UTC, cerberushades commented on src/css/custom.css
> +  background: #D0BAF5;
the navbar, on the other hand, is ok in terms of contrast, but it is calling too much attention! Also, we'd have to check the polygon logo there...

2022-05-30 18:25 UTC, DannyS03 commented on docusaurus.config.js
> +          title: "Scaling Solutions",
Didn't include Polygon ID and it follows the footer list on the main site

2022-05-30 18:32 UTC, DannyS03 commented on src/css/custom.css
> +  background: #D0BAF5;
> > proposing we update the landing page tabs - while "new" and "experienced" are good categorizations, I feel they don't accurately depict all the content, and the sub-labels on the cards mention the "difficultly"
> 
> We might also rethink that "Scale with Polygon". I'm not sure all products by polygon deal with scaling. Polygon ID probably not

right we mentioned this already with Polygon ID but decided to keep it for now

2022-05-30 18:32 UTC, DannyS03 commented
> > proposing we update the landing page tabs - while "new" and "experienced" are good categorizations, I feel they don't accurately depict all the content, and the sub-labels on the cards mention the "difficultly"
> 
> We might also rethink that "Scale with Polygon". I'm not sure all products by polygon deal with scaling. Polygon ID probably not

right we mentioned this too with Polygon ID, but decided to keep it for now

2022-05-30 19:03 UTC, DannyS03 commented on src/css/custom.css
> +  background: #D0BAF5;
Addressed

2022-05-31 23:08 UTC, cerberushades commented on src/css/custom.css
> +  --ifm-color-primary: #D0BAF5;
We need to check with @Nazeim if he's ok with that new color

2022-05-31 23:44 UTC, DannyS03 commented
@Nazeim  updated - now we use the proposed shade only for dark mode, and I adjusted the color for light mode to the lightest shade instead of plain white

2022-06-01 00:08 UTC, cerberushades approved these changes

2022-06-01 00:08 UTC, merged