Initiate Revamp of Develop Section
maticnetwork/matic-docs pull request #918
Opened 2022-06-01 02:59 UTC by DannyS03

- Adds more flow and cleans up current format for the time being
- Many updates to follow

2022-06-01 03:15 UTC, DannyS03 commented
Note: Merge conflict will occur because of the sidebars being updated in the open PRs - I will address once merged

2022-06-02 18:41 UTC, cerberushades requested changes

2022-06-02 18:41 UTC, cerberushades commented on docs/develop/did-implementation.md
>  The Polygon DID method Implementation comprises of 3 packages, namely the polygon-did-registrar, polygon-did-resolver and polygon-did-registry-contract. A user who wants to incorporate the functional
```suggestion
The Polygon DID method Implementation comprises 3 packages, namely the polygon-did-registrar, polygon-did-resolver and polygon-did-registry-contract. A user who wants to incorporate the functionality to either register or read a DID on or from Polygon network can use the following guide.
```

2022-06-02 18:41 UTC, cerberushades commented on docs/develop/did-implementation.md
> +The Polygon DID method definition conforms to the DID-Core specifications and standards. A DID URI is composed of three components separated by colons, the scheme, followed by the method name and fin
```suggestion
The Polygon DID method definition conforms to the DID-Core specifications and standards. A DID URI is composed of three components separated by colons: the scheme, followed by the method name and finally a method-specific identifier. For Polygon the URI looks like
```

2022-06-02 18:41 UTC, cerberushades commented on docs/develop/did-implementation.md
> +Here the scheme is ‘did’, method name is ‘polygon’ and method specific identifier is an ethereum address.
```suggestion
Here the scheme is ‘did’, method name is ‘polygon’ and method-specific identifier is an ethereum address. 
```

2022-06-02 18:41 UTC, cerberushades commented on docs/develop/did-implementation.md
> +Polygon DID can be implemented with help of two packages, user can import the respective npm libraries and use them to incorporate Polygon DID methodologies in thier respective applications. Details
```suggestion
Polygon DID can be implemented with help of two packages, user can import the respective npm libraries and use them to incorporate Polygon DID methodologies in thier respective applications. Details for implementation are provided in the next section.
```

2022-06-02 18:41 UTC, cerberushades commented on docs/develop/did-implementation.md
>  To get started, one first needs to create a DID. Creation in case of Polygon did is an encapsulation of two steps, first where a user needs to generate a DID uri for themselves and next register it o
```suggestion
To get started, one first needs to create a DID. Creation in case of Polygon did is an encapsulation of two steps, first where a user needs to generate a DID URI for themselves and next register it on the Polygon ledger.
```

2022-06-02 18:41 UTC, cerberushades commented on sidebars.js
> -    "develop/fiat-on-ramp",
we're removing this one not transferring it to another folder?

2022-06-02 18:44 UTC, DannyS03 commented
Thanks @cerberushades - the update in this PR doesn't focus on the pages themselves which is why they aren't updated so let's leave out the suggestions as the page would likely change

2022-06-02 18:44 UTC, DannyS03 commented on sidebars.js
> -    "develop/fiat-on-ramp",
right we are removing it

2022-06-02 19:47 UTC, cerberushades approved these changes

2022-06-02 20:30 UTC, merged