Create Content for Meta Transactions
maticnetwork/matic-docs pull request #920
Opened 2022-06-01 03:14 UTC by DannyS03

Guide that explains meta transactions

2022-06-03 17:55 UTC, cerberushades requested changes

2022-06-03 17:55 UTC, cerberushades commented on docs/develop/meta-transactions/getting-started.md
> +and are then executed from a single sender (single nonce specified) in sequence.
that could be an admonition box

2022-06-03 17:55 UTC, cerberushades commented on docs/develop/meta-transactions/getting-started.md
> +The contract unwraps the tx and executes it
```suggestion
- A user (sender) signs a request with their private key and sends it to a relayer
- The relayer wraps the request into a tx and sends it to a contract 
- The contract unwraps the tx and executes it
```

2022-06-03 17:55 UTC, cerberushades commented on docs/develop/meta-transactions/getting-started.md
> +2. [Gas Station Network (GSN)](meta-transactions-gsn.md)
both links appear broken to me

2022-06-03 18:17 UTC, cerberushades commented on docs/develop/meta-transactions/getting-started.md
> +2. [Gas Station Network (GSN)](meta-transactions-gsn.md)
I think removing ".md" might solve it

2022-06-03 19:50 UTC, DannyS03 commented on docs/develop/meta-transactions/getting-started.md
> +The contract unwraps the tx and executes it
Updated

2022-06-03 19:50 UTC, DannyS03 commented on docs/develop/meta-transactions/getting-started.md
> +2. [Gas Station Network (GSN)](meta-transactions-gsn.md)
Addressed

2022-06-03 19:51 UTC, DannyS03 commented on docs/develop/meta-transactions/getting-started.md
> +and are then executed from a single sender (single nonce specified) in sequence.
Addressed

2022-06-03 19:59 UTC, DannyS03 commented
Removed pages on the specific solutions as the gsn guide is a copy of the documentation available on the openzeppelin docs and the biconomy guide isn't necessary in its current form

2022-06-07 00:55 UTC, cerberushades approved these changes

2022-06-07 01:00 UTC, cerberushades commented
@DannyS03 I think you need to delete the following lines : - develop/meta-transactions/meta-transactions-biconomy
- develop/meta-transactions/meta-transactions-gsn

2022-06-07 01:47 UTC, DannyS03 commented
@cerberushades I removed the most recent commit as it conflicts with the latest changes and build fails. Building is successful locally and passing CI with the changes in `dd5989c`

2022-06-07 01:47 UTC, merged