Add Partner Wallets and Modify Wallets Page
maticnetwork/matic-docs pull request #930
Opened 2022-06-06 15:52 UTC by DannyS03

- Wallets page can be the general getting started page for all things wallets (will follow more updates)
- Adds table for partner wallets
- Redirects prev. content to this page

2022-06-06 19:21 UTC, cerberushades requested changes

2022-06-06 19:21 UTC, cerberushades commented on docs/develop/wallets/getting-started.md
> +This guide includes wallets that support the Polygon network which Polygon Technology is in
I think we ought to rephrase this

2022-06-06 19:21 UTC, cerberushades commented on docs/develop/wallets/getting-started.md
> +| [XDeFi](https://www.xdefi.io/) 	| non-custodial 	| EOA 	| no 	| interface 	| no 	|
there is just one hiccup here: how do we know this is an extensive list that really mentions ALL wallets supporting MATIC

2022-06-06 21:23 UTC, DannyS03 commented on docs/develop/wallets/getting-started.md
> +| [XDeFi](https://www.xdefi.io/) 	| non-custodial 	| EOA 	| no 	| interface 	| no 	|
the page mentions that these are wallets polygon is in partnership with

2022-06-06 21:23 UTC, DannyS03 commented on docs/develop/wallets/getting-started.md
> +| [XDeFi](https://www.xdefi.io/) 	| non-custodial 	| EOA 	| no 	| interface 	| no 	|
addressed

2022-06-06 21:24 UTC, DannyS03 commented on docs/develop/wallets/getting-started.md
> +This guide includes wallets that support the Polygon network which Polygon Technology is in
took it out - an update will follow that gives an intro to wallets and flows into this material

2022-06-07 14:37 UTC, DannyS03 commented
> @cerberushades We need also to add the "Manual" Wallets from here (not only Native one):
> 
> https://www.notion.so/polygontechnology/Wallet-Matrix-8e699080c29f4c248bca75f40e2eb690

The ones that don't support Polygon?

2022-06-14 15:10 UTC, cerberushades requested changes

2022-06-14 15:10 UTC, cerberushades commented on docs/develop/wallets/getting-started.md
>  The overall steps would essentially remain the same for any client side application to talk to the blockchain:
```suggestion
The overall steps would essentially remain the same for any client-side application to talk to the blockchain:
```

2022-06-14 15:10 UTC, cerberushades commented on docs/develop/wallets/getting-started.md
> +1. **Set up Web3**: [web3.js](https://web3js.readthedocs.io/) is a javascript library that allows our client-side application to talk to the blockchain. We configure web3 to communicate via Metamask/
```suggestion
1. **Set up Web3**: [web3.js](https://web3js.readthedocs.io/) is a javascript library that allows our client-side application to talk to the blockchain. We configure web3 to communicate via Metamask, Wallet Connect or Portis.
```

2022-06-15 05:28 UTC, DannyS03 commented on docs/develop/wallets/getting-started.md
> +and require manual steps to add the Polygon network.
Addressed

2022-06-15 05:28 UTC, DannyS03 commented on docs/develop/wallets/getting-started.md
> +:::
made it into a general one

2022-06-15 05:30 UTC, DannyS03 commented
thanks @cerberushades, for the remaining suggestions, I did not update the rest of the content that the suggestions are made for as the plan is to change the content with a different approach when adding updates to the wallet content

2022-06-15 06:49 UTC, DannyS03 commented
came across something and going to make a few changes for how we approach the wallet content. I had made some additional updates to other pages but I think it's better to propose a new approach

2022-06-20 13:16 UTC, cerberushades requested changes

2022-06-20 13:16 UTC, cerberushades commented on docs/develop/wallets/getting-started.md
> +The following page serves as a wallet index for wallets compatiable with Polygon. Please note
```suggestion
The following page serves as a wallet index for wallets compatible with Polygon. Please note
```

2022-06-20 13:16 UTC, cerberushades commented on docs/develop/wallets/getting-started.md
> +[Polygon Support](https://support.polygon.technology/support/home) can support users and address
```suggestion
[Polygon Support](https://support.polygon.technology/support/home) can provide assistance to users and address 
```

2022-06-20 13:16 UTC, cerberushades commented on docs/develop/wallets/getting-started.md
> +[Polygon Support](https://support.polygon.technology/support/home) can support users and address
just avoiding the "support " repetition

2022-06-20 13:16 UTC, cerberushades commented on docs/develop/wallets/getting-started.md
> +Wallets denoted with * in the table below are not natively supported with the wallet software
```suggestion
Wallets denoted with * in the table above are not natively supported with the wallet software 
```

2022-06-20 13:16 UTC, cerberushades commented on docs/develop/wallets/getting-started.md
> +The following wallets are solutions that Polygon Technology has partnered with.
```suggestion
The following wallets are solutions that Polygon Technology has partnered with:
```

2022-06-20 13:16 UTC, cerberushades commented on docs/develop/wallets/getting-started.md
> +The following basic steps allow for the integratation a client-side application with Polygon:
```suggestion
The following basic steps allow for the integration a client-side application with Polygon:
```

2022-06-21 13:50 UTC, cerberushades approved these changes

2022-06-21 13:50 UTC, merged

2022-06-21 13:54 UTC, DannyS03 commented
@Nazeim @cerberushades PR was WIP as I was changing the content and I wanted to get the Wallet SME to check. Some fields aren't filled out for some wallets which need to be filled out