Add ChainIDE doc
maticnetwork/matic-docs pull request #945
Opened 2022-06-16 08:25 UTC by xiadd

Add ChainIDE doc

2022-06-21 04:07 UTC, DannyS03 requested changes
Thanks for the contribution @xiadd 

On top of the direct suggestions:
- We are in the process of updating all the developer docs and would like to include this material, but may be modified in the near future and we will ask for your input:) We are also going to add full on contribution/style/template guidelines for contributions. Still, we can enhance to make it a better tutorial. I'd request that we add an "Introduction" and "Requirements" section (or something similar) to give the doc more of the tutorial template. Introduction will be background info on ChainIDE and Requirements should be ChainIDE, MetaMask and anything else required for interacting with the tutorial.

- It should also outline the sections a bit better, so after Requirements, it can be "Setting up a Wallet" (and include "Install MetaMask") as a subsection, "Adding the Mumbai Testnet" -> "Getting test MATIC", and so on. These should match the steps outlined in the beginning, perhaps creating a "What You'll Do" section in the beginning.
- Verifying smart contract steps can go after deploying smart contract steps 
- The images are good, thank you, but would recommend using html syntax to size them equally, for example: 
```
<img src={useBaseUrl("img/avail/account.png")} width="100%" height="100%"/>
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +After successful compilation, it's time to deploy your compiled ERC-721 smart contract to the Polygon Mumbai Test Network.
```suggestion
After successful compilation, it's time to deploy your compiled ERC-721 smart contract to the Polygon Mumbai test network. 
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +For that, you need to have a MetaMask installed, Polygon Mumbai Test Network added to your MetaMask,
```suggestion
For that, you need to have a MetaMask installed, the Polygon Mumbai test network added to your wallet, 
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +and some dummy coins to pay for the transaction fee.
```suggestion
and some testnet tokens to pay for the transaction fee. 
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +You need to go to the "Deploy & Interaction" module and choose among the compiled smart contract,
```suggestion
Navigate to the "Deploy & Interaction" module and choose among the compiled smart contract. Select 
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +the smart contract you want to deploy and click the deploy button.
```suggestion
the smart contract you want to deploy and click the "deploy" button. 
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +For this tutorial, we'll use the "GameItem" smart contract to deploy.
```suggestion
For this tutorial, the `GameItem` smart contract will be deployed.
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +After the successful deployment, a message can be seen in the output section that your smart contract has been deployed successfully,
```suggestion
After successful deployment, an output message should state that your smart contract was deployed successfully. 
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +and you can verify the deployed smart contract on the Polygon Mumbai Test Network too. All the functions in the deployed smart contract can be seen in the "INTERACT" panel.
```suggestion
You can now verify the deployed contract. All the functions in the deployed smart contract can be seen in the "INTERACT" panel.
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +### 5. NFT Minting
```suggestion
## NFT Minting

```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +To mint an NFT, you need to use the award item function and use the wallet address of someone to whom you want to award an NFT,
```suggestion
To mint an NFT, you need to use the "award item" function, the wallet address of someone to whom you want to award an NFT too,
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +### 7.  Verify a Smart Contract
```suggestion
## Verify a Smart Contract

```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +Click on the verify and publish link shown under the contract section.
```suggestion
Click on the "verify and publish" link shown under the contract section. 
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +### 6. Create a Flattened File using Flattener Library
```suggestion
## Create a Flattened File using Flattener Library
```

2022-06-21 04:07 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:22 UTC, xiadd commented
@DannyS03 Thanks for review, I have updated the document!

2022-06-21 04:26 UTC, DannyS03 requested changes

2022-06-21 04:26 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:26 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:26 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:26 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:26 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:26 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:26 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-21 04:26 UTC, DannyS03 commented on docs/develop/chainide.md
> +   getApproved()
I believe this was forgotten

2022-06-21 04:26 UTC, DannyS03 commented on docs/develop/chainide.md
> + - grant address_ To has_ Token ID control. Approval event needs to be triggered after the method is successful
Not sure if this is supposed to be part of another function

2022-06-22 09:35 UTC, DannyS03 requested changes

2022-06-22 09:35 UTC, DannyS03 commented on docs/develop/chainide.md
> +## What You'll Do
can go after prerequisites

2022-06-22 09:35 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-22 09:35 UTC, DannyS03 commented on docs/develop/chainide.md
> +
```suggestion
```

2022-06-22 09:35 UTC, DannyS03 commented on docs/develop/chainide.md
> +You have minted an NFT successfully, and you're done with this tutorial.
```suggestion
Congratulations, you have successfully minted an NFT on Polygon using ChainIDE.
```

2022-06-22 17:21 UTC, DannyS03 commented on docs/develop/chainide.md
> +### Getting Testnet  Matic
```suggestion
### Getting Testnet Matic
```

2022-06-22 17:23 UTC, DannyS03 commented
thanks @xiadd, should be good after moving the "What You'll Learn" section and updating the images to use html and consistent sizing

2022-06-23 03:51 UTC, DannyS03 approved these changes
thanks again for the contribution @xiadd

2022-06-23 03:57 UTC, merged