Edited documentation
maticnetwork/matic-docs pull request #951
Opened 2022-06-20 21:59 UTC by cerberushades

2022-06-21 04:32 UTC, DannyS03 requested changes

2022-06-21 04:32 UTC, DannyS03 commented on docs/maintain/validate/run-validator-ansible.md
> +* ETHEREUM_PRIVATE_KEY — your Ethereum wallet address.
private key is correct here

2022-06-21 04:32 UTC, DannyS03 commented on docs/develop/network-details/full-node-deployment.md
> +title: Full Node Ansible
why change this to Ansible deployment?

2022-06-22 08:49 UTC, DannyS03 commented
I don't agree that we change the Full Node Deployment to Ansible as there is already a guide on deploying with Ansible (using Ansible for "full node deployment" can be presented as a tool in the steps, if anything, and the script should update the parameter name because `ETHEREUM_PRIVATE_KEY` shouldn't = "wallet address", despite SME request @Nazeim

2022-06-22 09:02 UTC, sunil0410 commented
So the names contradict the Binaries part we have clearly mentioned Full Node Binaries but in the case of Ansible the naming convention should be similar to Full Node Ansible.

![image](https://user-images.githubusercontent.com/104004697/174989128-12ab41d0-a92e-44e0-9085-0433f963a3d2.png)

2022-06-22 09:05 UTC, sunil0410 commented
![image](https://user-images.githubusercontent.com/104004697/174989768-58171daf-4ac8-4831-a40f-ba4b64b63e9d.png)

Also, that's the standard we maintain with the Validator Nodes and the Setup a Full Node keyword looks a bit odd.

2022-06-22 09:11 UTC, sunil0410 commented
For the next change regarding the wallet address again there is some contradiction

Binaries:
https://docs.polygon.technology/docs/maintain/validate/run-validator-binaries/#generating-a-heimdall-private-key

Ansible:
https://docs.polygon.technology/docs/maintain/validate/run-validator-ansible/#generate-a-heimdall-private-key

The information used must be similar for both the cases Binaries as well as Ansible steps but it's vice-versa.

It's only the wallet address that should be used.

![image](https://user-images.githubusercontent.com/104004697/174990869-b4acd504-63f5-4b2c-bd3b-7b2b78786011.png)
![image](https://user-images.githubusercontent.com/104004697/174990998-b00921c0-3802-464f-b9b7-252908907926.png)

2022-06-22 09:26 UTC, DannyS03 commented
thanks @sunil0410 - right I see what you mean with the node deployment.

For the wallet address change, isn't it contradictory having the parameter called `ETHEREUM_PRIVATE_KEY` hold the wallet address; shouldn't it be called `ETHEREUM_PUBLIC_KEY`, in that case?

2022-06-22 15:10 UTC, merged