Add to Avail System Overview
maticnetwork/matic-docs pull request #973
Opened 2022-07-07 07:39 UTC by DannyS03

Elaborating on Avail's design and approach.

Will follow other articles on consensus, Kate commitments (and more).
Will also be good to provide more technicalities for each section in their own doc, supported by diagrams

2022-08-04 02:58 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +layer, which is the approach Ethereum rollups take.
* Rollups modularize execution (execution is off-chain), but leave data availability in the monolithic chain (they submit transaction data to the L1). So they modularize _in part_.
* I don't think rollups "work best" necessarily - they make some tradeoffs, there are pros/cons. The rollup construction can be more secure (depending on the security of the data availability layer), but it is inherently more difficult to scale.

2022-08-04 03:00 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +application-specific chain for DA (data availability).
Hmm I can see what you're trying to say, but I think it's confusing to describe Avail as an app chain, because app chains can be built _on top_ of Avail. So I think it would be better not to refer to Avail in that way.

2022-08-04 03:04 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +[Avail architecture guide] for more details.
I'm not familiar with FRAME, but I would phrase this as: Although Avail is based on the Substrate codebase, it includes modifications to the block structure that prevent it from interoperating with other Substrate networks. Avail implements an independent network unrelated to Polkadot or Kusama.

2022-08-04 03:08 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +Avail provides a high guarantee of data availability to any light client.
To be more precise:
* Avail nodes do not make higher guarantees to light clients about DA than any other network.
* What Avail does provide is a way for light clients to "sample" small pieces of the block to verify it is actually there.
* Thus, the DA guarantee is something the client determines for itself—it doesn't have to trust nodes.

Also:
* As the number of light clients grows, they collectively sample the entire block (even though each client only samples a small %)
* Light clients actually form a P2P network amongst themselves
* Thus, after a block has been sampled, it becomes _highly available_—that is, even if the nodes were to go down (or attempt to censor a block), the light clients would be able to reconstruct the block by sharing the pieces amongst themselves.

2022-08-04 03:09 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +standard fraud-proof-based DA systems, which are explained [here].
Remove "standard" — fraud proofs are not really more standard than what we do.

2022-08-04 03:12 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +availability. Transaction costs are also reduced; the primary cost
...as sovereign chains can be created that rely on Avail's validators to reach consensus on transaction data and ordering.

2022-08-04 03:17 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +availability. Transaction costs are also reduced; the primary cost
As for the tx costs point - it's true, but the way it is phrased is very much about validiums, whereas the point about bootstrapping sovereign rollups is about Avail-native chains. These are very different ways to use Avail, so I'd like to put more distance between them / make it clear these are different use cases.

Fundamentally, the reason Avail can remain cheap is that it is able to grow block size with a smaller impact to validator workload than a monolithic chain. When a monolithic chain increases block size, validators have to do a lot more work, because blocks have to be executed and state has to be calculated. Since avail has no execution environment at all, it's much cheaper to increase block size. (Not zero because we do need to calculate KZG commitments and generate proofs — but cheaper).

2022-08-04 03:18 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +direct updates would need to be made to contracts, or the network requires a fork.
I'd remove 'contracts' here - we're talking about fundamental network upgrades, not contracts.

2022-08-04 03:19 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +data or reconstruction, security is not compromised.
*for

2022-08-04 03:20 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +data or reconstruction, security is not compromised.
This point about retention and the next paragraph about storage are good points, but shouldn't be mixed with the point about Avail being agnostic as to what the data is. Should be a separate point imo.

2022-08-04 03:23 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +  transaction details from neighboring full nodes as needed.
Why not just talk about what the Avail nodes/clients are? Why talk about Ethereum?

For example - the Avail validators do not execute transactions. They simply package up the transactions (whatever they are) and construct candidate blocks, generating KZG commitments for the data. Other validators check that generated blocks are correct. Similarly, Avail full nodes do not execute anything.

2022-08-04 03:25 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +  The aim is to give the same DA guarantees to a light client as a full node.
similar, not same

2022-08-04 03:48 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +ordering. A block is considered valid only if the data behind that block is available.
Not really wrong, but here's some additional context:

* Avail validators take incoming transactions, order them, construct a block, and propose it.
* The block contains special features especially for DA—erasure coding, and KZG commitments. And it's in a special format so that clients are able to do random sampling later, as well as being able to download only a single application's transactions.
* Anyway - they propose a block, and other validators verify the block is correct - well formed, KZG commitments check out, data is there, etc.

2022-08-04 03:52 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +codes; these checks are heavily used in data redundancy design.
* The DA verification is performed by clients via sampling. It's not something validators or full nodes do, exactly.
* Erasure codes effectively duplicate data in such a way that if part of a block is suppressed, clients can reconstruct that part by using another part of the block. This means that a node trying to suppress that part would actually need to suppress _a lot more_. The technique is used for example in CD-ROMs, and in multi-disk (RAID) arrays (so for example if a hard drive dies, it can be replaced and re-constructed from the data on other disks).

2022-08-04 03:59 UTC, vthunder submitted a review, later dismissed
Left a bunch of comments - please review them and make tweaks as necessary (some point out issues, others are more FYI to add context for you, in case you want to frame things differently or explain further).

2022-08-04 03:59 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +codes; these checks are heavily used in data redundancy design.
I mean—if data was indeed unavailable, then validators would not sign off on a block, that is true—but it's also true of any other chain. The thing that makes Avail unique isn't that _validators_ check the data, but rather that the chain is structured so that _anyone_ can check DA without actually downloading the data.

2022-08-04 03:59 UTC, vthunder commented on docs/avail/architecture/avail-system-overview.md
> +DA properties of Avail.
This is all correct - but note that there are different ways to use Avail, and the validium use case (referenced way above) will not use this settlement layer (validiums will settle on Ethereum). Just FYI!

2022-08-24 04:51 UTC, DannyS03 commented
@vthunder many thanks for the review. Addressed the feedback and areas that were not directly addressed were a result of the suggestions already existing in another part of the doc

2022-08-24 04:52 UTC, DannyS03 commented
@Nazeim @cerberushades can review

2022-08-31 18:08 UTC, cerberushades requested changes

2022-08-31 18:08 UTC, cerberushades commented on docs/avail/architecture/avail-system-overview.md
> +   Clients that only download block headers randomly sample small parts of
```suggestion
   Clients that only download block headers and random samples of 
```

2022-08-31 18:08 UTC, cerberushades commented on docs/avail/architecture/avail-system-overview.md
> +  Users are encouraged to use Avail light clients. However, users can run Avail
```suggestion
  Users are encouraged to use Avail light clients. However, they can still run Avail 
```

2022-08-31 18:08 UTC, cerberushades commented on docs/avail/architecture/avail-system-overview.md
> +- [Polygon Talks: Polygon Avail]
no link

2022-08-31 18:44 UTC, DannyS03 commented on docs/avail/architecture/avail-system-overview.md
> +- [Polygon Talks: Polygon Avail]
```suggestion
- [Polygon Talks: Polygon Avail](https://www.youtube.com/watch?v=okqMT1v3xi0)
```

2022-08-31 18:45 UTC, DannyS03 commented on docs/avail/architecture/avail-system-overview.md
> +fraud-proof-based DA systems, which are explained [here].
```suggestion
fraud-proof-based DA systems, which are explained [here](https://blog.polygon.technology/the-data-availability-problem-6b74b619ffcc/).
```

2022-08-31 18:45 UTC, DannyS03 commented on docs/avail/architecture/avail-system-overview.md
> +cannot efficiently handle the execution, settlement, and data availability.
can leave "the" out

2022-08-31 18:46 UTC, DannyS03 commented on docs/avail/architecture/avail-system-overview.md
> +fraud-proof-based DA systems, which are explained [here].
updated

2022-08-31 18:46 UTC, DannyS03 commented on docs/avail/architecture/avail-system-overview.md
> +way to bootstrap [any] standalone chain, as chains can offload their data
```suggestion
way to bootstrap any standalone chain, as chains can offload their data 
```

2022-08-31 18:46 UTC, DannyS03 commented on docs/avail/architecture/avail-system-overview.md
> +way to bootstrap [any] standalone chain, as chains can offload their data
updated

2022-08-31 18:48 UTC, DannyS03 commented on docs/avail/architecture/avail-system-overview.md
> +what that data is. The data can be transactions but can take
we are being specific about transaction data

2022-08-31 18:49 UTC, DannyS03 commented on docs/avail/architecture/avail-system-overview.md
> +   Clients that only download block headers randomly sample small parts of
suggestion doesn't work with how random sampling is supposed to be mentioned

2022-08-31 18:50 UTC, DannyS03 commented on docs/avail/architecture/avail-system-overview.md
> +- [Polygon Talks: Polygon Avail]
updated

2022-09-01 22:53 UTC, DannyS03 commented
@cerberushades addressed feedback

2022-09-05 05:53 UTC, DannyS03 commented
@cerberushades checking if we'd like to change anything else

2022-09-05 21:55 UTC, cerberushades approved these changes

2022-09-06 04:28 UTC, merged