Audited Alchemy's Tutorial
maticnetwork/matic-docs pull request #979
Opened 2022-07-08 02:12 UTC by cerberushades

2022-07-11 03:58 UTC, DannyS03 requested changes
would also:
- add imagery for tutorial steps. Dashboard screenshots for dashboard actions, txt editor snippets (where appropriate)
- o/ps where appropriate (e.g. running this command should result in this)

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
> +# Create a Smart Contract using Alchemy
lets make this the title in the metadata and remove from here

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
> +This guide is for developers who are either new to blockchain development or want to understand how to deploy and interact with smart contracts. It will walk through creating and deploying a smart co
```suggestion
This tutorial is for developers who are either new to Ethereum blockchain development or want to understand the fundamentals of deploying and interacting with smart contracts. It will walk through creating and deploying a smart contract on the Polygon Mumbai test network using a virtual wallet ([Metamask](https://metamask.io)), [Solidity](https://docs.soliditylang.org/en/v0.8.0/), [Hardhat](https://hardhat.org), and [Alchemy](https://alchemy.com/?a=polygon-docs).
```

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
> +This guide is for developers who are either new to blockchain development or want to understand how to deploy and interact with smart contracts. It will walk through creating and deploying a smart co
Here, it can be a summary of what will happen end-to-end while introducing the tools throughout, such as: "You will start by ...., then ....finally..."

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
> +If you have questions at any point, you may contact the [Alchemy Discord Channel (https://discord.gg/gWuC7zB)](https://discord.gg/gWuC7zB).
```suggestion
If you have questions or concerns, please reach out to the [official Alchemy Discord] (https://discord.gg/gWuC7zB)](https://discord.gg/gWuC7zB).
```

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
> +There are many ways to make requests to the Polygon chain. For simplicity, we’ll use a free account on Alchemy, **a blockchain developer platform and API that allows us to communicate with the Polygo
```suggestion
There are several ways to make requests to the Polygon PoS chain. Rather than running your own node, you will use a free account on Alchemy's developer platform and interact with the Alchemy Polygon PoS API to communicate with the Polygon PoS chain. The platform includes developer tooling to monitor requests and data analytics that demonstrate what happens under the hood during smart contract deployment. If you don’t already have an Alchemy account, start by signing up for free [here](https://alchemy.com/?a=polygon-docs).
```

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
>  Once you’ve created an Alchemy account, you can generate an API key by creating an app. This will allow us to make requests to the Polygon Mumbai test network. If you’re not familiar with testnets, c
```suggestion
After successfully creating an Alchemy account, you will need to generate an API key by creating an app. This authenticates the requests made to the Polygon Mumbai testnet. 
> If you’re not familiar with testnets, check out [this testnet guide](https://docs.alchemyapi.io/guides/choosing-a-network).

To generate a new API key, navigate to the "Apps" tab on the Alchemy dashboard navigation bar and select the "Create App" sub-tab.
```

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
>  Navigate to the “Create App” page in your Alchemy Dashboard by hovering over “Apps” in the nav bar and clicking “Create App”.
```suggestion
```

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
> +Name your app “Hello World”, offer a short description, click "Polygon" for the Chain, and choose “Polygon Mumbai” for your network.
```suggestion
Name your new app “Hello World”, offer a short description, select "Polygon" for the chain, and choose “Polygon Mumbai” for your network.
```

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
>  Click “Create app” and that’s it! Your app should appear in the table below.
```suggestion
Finally, click on “Create app”. Your new app should appear in the table below.
```

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
> +After you create your account, Alchemy lets you start creating your first app before actually reaching the dashboard. You can start from there or go ahead and skip it.
```tip
After creating your account, you have the option of immediately creating your first app before reaching the dashboard.
```

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
> +After you create your account, Alchemy lets you start creating your first app before actually reaching the dashboard. You can start from there or go ahead and skip it.
should move this before the dashboard-based steps on creating a new app

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
>  Since Polygon is a Layer-2 scaling solution for Ethereum, we need to get an Ethereum wallet and add a custom Polygon URL to send and receive transactions on the Polygon network. For this tutorial, we
```suggestion
Since Polygon PoS is a layer 2 scaling solution for Ethereum, we need to get an Ethereum wallet and add a custom Polygon URL to send and receive transactions on the Polygon Mumbai testnet. For this tutorial, we will use MetaMask, a browser-compatible digital wallet used to manage your wallet address. If you want to understand more about how transactions on Ethereum work, check out [this transactions guide](https://ethereum.org/en/developers/docs/transactions/) by the Ethereum Foundation.
```

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
> +In order to deploy our smart contract to the test network, we’ll need some fake MATIC. To get MATIC, you can go to the [Polygon Mumbai Faucet](https://faucet.polygon.technology/), select "Mumbai", ch
```suggestion
In order to deploy your smart contract to the test network, you need to obtain a few testnet tokens. To get testnet tokens, visit the [Polygon Mumbai Faucet](https://faucet.polygon.technology/), select "Mumbai", choose "MATIC Token", and enter your Polygon wallet address, then click “Submit.” It may take some time to receive your testnet tokens due to network traffic. 
> At the time of writing, it took around 30 minutes.
You will see the testnet tokens in your MetaMask account soon after.
```

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
> +This result is in wei not eth. Wei is used as the smallest denomination of ether. The conversion from wei to ether is: 1 ether= 10^18 wei. So if we convert 0xde0b6b3a7640000 to decimal we get 1\*10^1
```suggestion
This result is in Wei, not ETH. Wei is used as the smallest denomination of Ether. The conversion from Wei to Ether is: 1 Ether = 10^18 Wei. So, if we convert "0xde0b6b3a7640000" to decimal, we get 1\*10^18, which equals 1 ETH. This can be mapped to 1 MATIC based on denomination.
```

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
> +Open up the hello-world project in your favorite editor, such as [VSCode](https://code.visualstudio.com). Smart contracts are written in a language called Solidity which is what we will use to write
if explaining at this level, should mention basics of solidity, developer environment, ".sol" extension, etc.

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
> +:::caution
```suggestion
:::warning
```

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
> +* To get your Alchemy HTTP API Key (RPC URL), go to your "Hello World" app in your Alchemy dashboard and click "View Key" in the top right corner.
```suggestion
* To get your Alchemy HTTP API key (RPC URL), navigate to your "Hello World" app on your account's dashboard and click "View Key" in the top right corner. 
```

2022-07-11 03:58 UTC, DannyS03 commented on docs/develop/alchemy.md
> +Hardhat makes it easy to integrate [Plugins](https://hardhat.org/plugins/) for additional tooling and extended functionality. We’ll be taking advantage of the [Ethers plugin](https://hardhat.org/plug
```suggestion
Hardhat makes it easy to integrate [plugins](https://hardhat.org/plugins/) for additional tooling and extended functionality. We’ll be taking advantage of the [Ethers plugin](https://hardhat.org/plugins/nomiclabs-hardhat-ethers.html) for contract deployment. [Ethers.js](https://github.com/ethers-io/ethers.js/) has useful contract deployment methods.
```

2022-07-12 04:21 UTC, DannyS03 commented on docs/develop/alchemy.md
> +You will see the testnet tokens in your MetaMask account soon after.
```suggestion

You will see the testnet tokens in your MetaMask account soon after.
```

2022-07-12 04:26 UTC, DannyS03 requested changes
- To adapt the template, we still need to outline the sections, such as "Overview", "What you'll learn", "What you'll do".
- This is also an opportunity for a test section, which in this case, can be contract verification: "Verify your contract", for instance: https://docs.polygon.technology/docs/develop/remix/#flatten-your-solidity-contract
- Still no imagery

2022-07-19 05:44 UTC, DannyS03 commented on docs/develop/alchemy.md
> +Following the tutorial, you will:
```suggestion

Following the tutorial, you will:
```

2022-07-19 05:44 UTC, DannyS03 commented on docs/develop/alchemy.md
> +To create a smart contract in this tutorial, you will learn how to use Alchemy's platform to:
```suggestion

To create a smart contract in this tutorial, you will learn how to use Alchemy's platform to:
```

2022-07-19 05:44 UTC, DannyS03 commented on docs/develop/alchemy.md
> +
```suggestion
```

2022-07-19 05:45 UTC, DannyS03 commented on docs/develop/alchemy.md
> +- create a smart contract application
```suggestion
- Create a smart contract application.
```

2022-07-19 05:45 UTC, DannyS03 commented on docs/develop/alchemy.md
> +- check the wallet's balance
```suggestion
- Check a wallet's balance.
```

2022-07-19 05:45 UTC, DannyS03 commented on docs/develop/alchemy.md
> +- verify calls in the explorer.
```suggestion
- Verify contract calls in an explorer. 
```

2022-07-19 07:46 UTC, DannyS03 requested changes
lets add a test section (smart contract verification)

2022-07-25 16:32 UTC, DannyS03 requested changes
after testing section is finalized and merge conflict addressed, should be good to merge

2022-07-25 16:32 UTC, DannyS03 commented on docs/develop/alchemy.md
> +### Step 17: Veriffy our contract
```suggestion
### Step 17: Verify the contract
```

2022-07-25 16:32 UTC, DannyS03 commented on docs/develop/alchemy.md
> +Alchemy provides an explorer where you can find information about the methods deployed along with the smart contract, such as response time, HTTP status, error codes and others. It is a good environm
Doesn't flow well with the content afterwards and would link the explorer

2022-07-25 20:55 UTC, cerberushades commented on docs/develop/alchemy.md
> +Alchemy provides an explorer where you can find information about the methods deployed along with the smart contract, such as response time, HTTP status, error codes and others. It is a good environm
I see. What would you suggest then?
The explorer is linked in the next paragraph...

2022-08-03 03:40 UTC, DannyS03 approved these changes

2022-08-03 03:40 UTC, merged