Add metadata template
maticnetwork/matic-docs pull request #991
Opened 2022-07-12 14:54 UTC by DannyS03

Adds general metadata template for markdown files

2022-07-15 14:35 UTC, DannyS03 commented on docs/contribute/writing-style.md
> +- Keywords are important to increase SEO and contribute to improve search engine results. 5 to 7 words are enough to cover the most relevant words of the article.
```suggestion
- Keywords are important to increase SEO and describe the article. Try to aim for at least five keywords.
```

2022-07-22 00:41 UTC, cerberushades requested changes

2022-07-22 00:41 UTC, cerberushades commented on docs/contribute/writing-style.md
> +- The **description** can not be too lengthy, since it is used on the index tiles which has a limitation for the number of characters. The description "Blockchain is an immutable ledger for recording
@DannyS03 can you commit this suggestion of your suggestion? :)

2022-07-22 20:22 UTC, cerberushades approved these changes

2022-07-22 20:23 UTC, merged